### ISSUE TITLE
[feature] Homebrew cask for macOS

### ISSUE THREAD

**Issue by moltar** [moonrepo/moon#1008]
**Is your feature request related to a problem? Please describe.**

The installation steps require piping a shell script to bash, which is commonly associated with poor security posture.

https://moonrepo.dev/docs/install#installing

**Describe the solution you'd like**

Add a Homebrew cask.

https://docs.brew.sh/Adding-Software-to-Homebrew

**Describe alternatives you've considered**

Inspecting the bash script before executing it.

**Additional context**

N/A

**Comment by milesj** [comment]
We had homebrew support (https://github.com/moonrepo/homebrew-tap) and removed it as it's a major pain to support. We most likely won't be bringing this back anytime soon.
