### ISSUE TITLE
[bug] During `moon init` the `defaultBranch` is set to current branch

### ISSUE THREAD

**Issue by moltar** [moonrepo/moon#1010]
**Describe the bug**

I was using a non-default branch (`feat/moonrepo`) for setting up moonrepo, and that's the branch name that was set as the `defaultBranch` value.

**Steps to reproduce**

```sh
git checkout -b feat/some-branch
moon init
```

**Expected behavior**

Try to infer common branch names (`main` or `master`).

**Screenshots**

N/A

**Environment**

N/A

**Additional context**

N/A

**Comment by milesj** [comment]
Fixed in 1.13
