### ISSUE TITLE
[feature] - Ability to copy/generate binary files added to a generator's template

### ISSUE THREAD

**Issue by sybernatus** [moonrepo/moon#1034]
**Is your feature request related to a problem? Please describe.**

I'd like the possibility to add binary files like images to a template to generate them with my module/documentation.

**Describe the solution you'd like**

In my use-case, I'm generating documentation in markdown format. This markdown is referring images in a sub-folder.
I have an error while generating those images as they are not under UTF-8 format.

I think we can also extrapolate the use-case to other binaries (runnable, videos, libraries, etc.)

```
        Error: codegen::template_file::load_failed
        
          × Failed to load template file ~/[...]/libs/feats/generator-driven/src/_deps/moon/[...]/templates/my-documentation/[name]/administrate-your-cluster/images/k8s-config-local-1.png.
          ├─▶ Failed to read template '"[...]/libs/feats/generator-driven/src/_deps/moon/[...]/templates/my-documentation/[name]/administrate-your-cluster/images/k8s-config-local-1.png"'
          ╰─▶ stream did not contain valid UTF-8
```
**Additional context**

Here is my template structure :
```shell
src/
....templates/
....my-documentation/
........[name]/
............images/
................my-doc-img.png
............README.md
........template.yaml
```

EDIT: I've tried to use `.raw` extension on png files but still get the same issue.

**Comment by Jad31** [comment]
I had the same problem generating a `favicon.ico`.

**Comment by milesj** [comment]
Yeah Tera assumes everything is text based. I'll look into supporting non-text files.
