### ISSUE TITLE
[feature] Print Target Projects for `moon run --affected`

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#1052]
**Is your feature request related to a problem? Please describe.**

It's currently difficult to know which projects Moon is targeted with the `--affected` flag, without turning on verbose logging.

**Describe the solution you'd like**

I'd like to see a pretty list of projects for which the command is being run, e.g. an effective list of projects affected

**Describe alternatives you've considered**

Using verbose logging levels. This is gnarly in CI. 

**Additional context**

**Comment by milesj** [comment]
Once this lands (https://github.com/moonrepo/moon/issues/1047), it should be enough right? `moon ci` was designed for all this kind of information, and I want to keep a distinction between it and `run`.

**Comment by shellscape** [comment]
@milesj yeah I think we're in good shape. Thanks!
