### ISSUE TITLE
[docs] `project` vs `projectName` in Query documentation

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#1053]
There's a funky ambiguation (is that a word?) between `project` and `projectName` on the Query language docs here: https://moonrepo.dev/docs/concepts/query-lang

<img width="1127" alt="Screenshot 2023-09-18 at 10 32 03 AM" src="https://github.com/moonrepo/moon/assets/76371/468ca61b-d25c-4310-93a1-d94099049859">

I made the mistake of not navigating to the `projectName` section before trying to use it, and attempted `projectName~svc-*` because the `fields` list shows `projectName`. Turns out that it's not `projectName` but `project`. 

I'd like to suggest that the list of fields and section header reflect the actual value that needs to be used. I'd wager that others will get bit by that as well.

**Comment by milesj** [comment]
@shellscape `project` and `projectName` are supported fields, the latter is just more specific.

What about `projectName~svc-*` didn't work exactly? If that's the project name, it should work?

**Comment by milesj** [comment]
@shellscape Ok that just looks like a bug, will fix.

**Comment by shellscape** [comment]
ah cool. happy accident

**Comment by milesj** [comment]
@shellscape Can you give 1.13.5 a shot
