### ISSUE TITLE
[bug] `moon dep-graph` behavior is inconsistent with `moon run`

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#1076]
When in a moon workspace, I can run `moon run thing` without specifing the project name. 

However, if you run `moon dep-graph thing`, you get:
```
Error: target::run_context::no_self_scope

  × Self scope (~:) is not supported in run contexts.
```

Of course it does work if you specify the fully qualified target, but this can be confusing as you'd expect both commands accept similar input.

**Comment by milesj** [comment]
@mrobinsn The `moon run thing` form is basically "traverse the file system and find a project". Are you running this in a sub folder, or have a root project?

**Comment by mrobinsn** [comment]
Yeah I have a root project, so maybe what I'm asking for is that `moon dep-graph` also "traverse the file system and find a project" in the same way.

**Comment by milesj** [comment]
Yeah just making sure. Fair request, shouldn't be difficult.
