### ISSUE TITLE
[bug][regression] moon now fails if there are non-json/yaml config files present

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#1077]
After upgrading to `1.14.0` all moon commands in my repo now fail with:
```
Error: config::format::unsupported

  × Unsupported format for <path-to-workspace>/.moon/tasks/<name>.<ext>, expected JSON, YAML.
```

This is a breaking change because we write moon config in a different format and then compile/translate it down to YAML.

**Comment by milesj** [comment]
@mrobinsn Can you paste the `--log trace` output. This is interesting, because we should only be loading `.yml` files.

**Comment by mrobinsn** [comment]
Nothing stands out to me in the trace log, but rather than try to redact that, here is a super simple repro:
```bash
moon init --yes
mkdir .moon/tasks
touch .moon/tasks/example.txt
moon query tasks
```
This will fail with that `× Unsupported format` error ^
