### ISSUE TITLE
Arguments for git hooks

### ISSUE THREAD

**Issue by ochan12** [moonrepo/moon#1078]
**Is your feature request related to a problem? Please describe.**

I was surprised to see that when I tried to add the hook `commit-msg` to moon hooks it was missing the $1 argument (normally .git/COMMIT_EDITMSG). As I could see in the script created by moon, none of the arguments of the original git hook are passed down to the moon hook.

**Describe the solution you'd like**

I would like that moon hooks, behave like git hooks in the sense that they make use of the original hooks arguments or at least have the option to use it so they can be drop-in replacements . In the case of `commit-msg` $1 is the location of the commit message. 

**Describe alternatives you've considered**

Only temporary solution, which worked was, syncing the hook and then manually edit the `.git/hooks/commit-msg` to use the original parameter

```./.moon/hooks/commit-msg.sh $1```

**Additional context**

**Comment by milesj** [comment]
Whoops, oversight.
