### ISSUE TITLE
[bug] main thread panicked windows 11

### ISSUE THREAD

**Issue by jcjpsa** [moonrepo/moon#1094]
**Describe the bug**

Windows 11:

```
➜ moon app:serve
Error:   × Main thread panicked.
  ├─▶ at C:
  │   \Users\runneradmin\.cargo\registry\src\index.crates.
  │   io-6f17d22bba15001f\starbase_utils-
  │   0.3.2\src\json.rs:112:8
  ╰─▶ called `Result::unwrap()` on an `Err` value:
      Kind(InvalidData)
  help: set the `RUST_BACKTRACE=1` environment variable
        to display a backtrace.
```

Windows 11 WSL:

```
▪▪▪▪ installing pnpm 8.8.0
Error:   × Main thread panicked.
  ├─▶ at /app/crates/core/runner/src/inputs_collector.rs:135:75
  ╰─▶ called `Result::unwrap()` on an `Err` value: StripPrefixError(())
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.

Aborted
```

**Steps to reproduce**

On Windows 11:

1. Run `moon app:serve`

On Windows 11 WSL Ubuntu:

1. Clone repo
2. Install NVM, install and use Node version `18.18.0`
3. Install PNPM
4. Install moonrepo using `pnpm add @moonrepo/cli@latest -g`
5. Run the app in error `moon app:serve`

**Expected behavior**

It should be able to run other apps within a monorepo but it only runs one app correctly.

**Environment**

Windows 11:

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 7940HS w/ Radeon 780M Graphics
    Memory: 14.40 GB / 31.21 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.8.0 - C:\Program Files\nodejs\pnpm.CMD
  Utilities:
    Git: 2.41.0. - C:\Program Files\Git\cmd\git.EXE
    Curl: 8.0.1 - C:\Windows\system32\curl.EXE
  Virtualization:
    Docker: 24.0.2 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.82.3 - C:\...\Microsoft VS Code\bin\code.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.47)
    Internet Explorer: 11.0.22621.1
```

Windows 11 WSL:

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 9 7940HS w/ Radeon 780M Graphics
    Memory: 14.33 GB / 15.23 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    pnpm: 8.8.0 - ~/.local/share/pnpm/pnpm
  Managers:
    Apt: 2.4.9 - /usr/bin/apt
  Utilities:
    Git: 2.34.1 - /usr/bin/git
    Curl: 7.81.0 - /usr/bin/curl
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    VSCode: 1.82.3 - /mnt/c/Users/tcham/AppData/Local/Programs/Microsoft VS Code/bin/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Perl: 5.34.0 - /usr/bin/perl
    Python3: 3.10.6 - /usr/bin/python3
```

**Additional context**

Works on a single app (e.g. core) within the monorepo but only on that app (e.g. core) for others app (e.g. desktop, mobile) it throws the same error. I am on Windows 11 using PowerShell 7 our project has been migrated from NX.

**Comment by milesj** [comment]
@jcjpsa Can you paste the `--log trace` output?

The `inputs_collector` is very suspect. It's failing on this line `project_root.strip_prefix(workspace_root).unwrap()`, but it panicing should not be possible, because a project root _should always be within_ the workspace root.

**Comment by jcjpsa** [comment]
> @jcjpsa Can you paste the `--log trace` output?
> 
> The `inputs_collector` is very suspect. It's failing on this line `project_root.strip_prefix(workspace_root).unwrap()`, but it panicing should not be possible, because a project root _should always be within_ the workspace root.

I think it logs a lot data, I don't think I'm allowed to share it what do you think would be the best logs to show?

**Comment by milesj** [comment]
@jcjpsa I can't really debug it without the logs. You can DM me on discord if that helps.

If paths are a problem, you can replace the path prefix up to the workspace root.

**Comment by jcjpsa** [comment]
> @jcjpsa I can't really debug it without the logs. You can DM me on discord if that helps.
> 
> If paths are a problem, you can replace the path prefix up to the workspace root.

Okay gotcha, i've sent the logs result on discord thanks!

**Comment by milesj** [comment]
Discussed offline. Was caused by a Unix symlink on Windows.

**Comment by shellscape** [comment]
@milesj is there documentation about this limitation? haven't run into a problem with it before

**Comment by milesj** [comment]
The problem was that this part was happening:

> In Windows, the symbolic link is converted to a text file with a path to the file it points to.

Which I'm assuming means that the automatic symlink resolution via git wasn't happening.

**Comment by shellscape** [comment]
Yeah I'd never run into that before. I still think it's an edge case, but the larger issue I believe is the target machine not being setup right for symlinks (see SO link above)

Could moon catch this bad symlink, warn, and exit gracefully?

**Comment by milesj** [comment]
I'm not sure what kind of overhead that would add, if every fs call was also checking symlinks. I'll keep it in mind though.

**Comment by shellscape** [comment]
Right on. maybe just in the event of that kind of error. just spitballing

**Comment by milesj** [comment]
At minimum, I'll fix this panic so it then fails on the JSON parse, bubbling up an appropriate error.
