### ISSUE TITLE
[bug] Postinstall with bun fails

### ISSUE THREAD

**Issue by elmpp** [moonrepo/moon#1103]
**Describe the bug**

Installing @moonrepo/cli via bun fails at the postinstall stage

**Steps to reproduce**

 - `bun add @moonrepo/cli'
 - add moon as trusted - "trustedDependencies": ["@moonrepo/cli"] - https://bun.sh/guides/install/trusted
 - rm -rf node_modules
 - rm bun.lockb
 - bun install
 - // leads to below error

```
Error: Cannot find module '@moonrepo/core-macos-x64/package.json'
Require stack:
- /Users/matt/dev/org-repo-moonrepo/node_modules/@moonrepo/cli/postinstall.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at Object.<anonymous> (/Users/matt/dev/org-repo-moonrepo/node_modules/@moonrepo/cli/postinstall.js:35:38)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/matt/dev/org-repo-moonrepo/node_modules/@moonrepo/cli/postinstall.js'
  ]
}
```

**Expected behavior**

Moon installs via bun

**Screenshots**

**Environment**

```
System:
    OS: macOS 13.0.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 22.47 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/dev/org-repo-moonrepo/node_modules/.bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    pnpm: 7.30.0 - /usr/local/bin/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    Composer: 1.5.2 - /usr/local/bin/composer
    Homebrew: 4.0.10 - /usr/local/bin/brew
    pip3: 22.3.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 14.0.3 - /usr/bin/gcc
    Git: 2.39.0 - /usr/local/bin/git
    Clang: 14.0.3 - /usr/bin/clang
    Curl: 7.84.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.54 - /usr/sbin/apachectl
  Virtualization:
    Docker: 18.09.0 - /usr/local/bin/docker
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    PhpStorm: 2017.3.3
    Sublime Text: 4143 - /usr/local/bin/subl
    VSCode: 1.78.2 - /usr/local/bin/code
    Vim: 9.0 - /usr/local/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 5.2.15 - /usr/local/bin/bash
    Java: 11.0.2 - /usr/bin/javac
    Perl: 5.36.0 - /usr/local/bin/perl
    PHP: 8.2.0 - /usr/local/bin/php
    Python3: 3.11.2 - /usr/local/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.39.4 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 99.1.36.117
    Chrome: 117.0.5938.149
    Edge: 117.0.2045.55
    Safari: 16.1
  Monorepos:
    Yarn Workspaces: 1.22.19
```

**Additional context**

**Comment by elmpp** [comment]
It seems to be related to the process being provided by the bun runtime?

This line `const pkgPath = path.dirname(require.resolve(`@moonrepo/core-${triple}/package.json`));`
is interpreted as `@moonrepo/core-macos-x64/package.json`

My machine is an M1 mac, and therefore an 'arm64' platform. However, it seems bun is installing the optional dep as `core-macos-arm64` (see screenshot)

<img width="1229" alt="Screenshot 2023-10-07 at 16 29 18" src="https://github.com/moonrepo/moon/assets/864612/1e529011-4f96-4fc4-9dee-59f4f33072ac">

**Comment by milesj** [comment]
@elmpp The postinstall just uses `process.arch`, and if that's showing `x64` in Bun, that sounds like a Bun bug?

**Comment by elmpp** [comment]
It's a tough one to debug my suspicion because bun doesn't support patch protocol and postinstall only triggers after node_modules are removed

I'll dig into it some more

**Comment by elmpp** [comment]
Is a node/bun mismatch ☝️

**Comment by milesj** [comment]
Nice find, it's surprising that this doesn't work for bun v1.

**Comment by amvFrontendMonkey** [comment]
I know it's on bun to fix this but would you accept a PR for a simple workaround in `postinstall.js` ?

Patch protocol isn't an option when using bun as a PM :(

**Comment by milesj** [comment]
@amvFrontendMonkey What would the patch be exactly?

**Comment by elmpp** [comment]
I would perhaps do a tryResolve() wrapper when the runtime is bun and fallback to 'arm64' for the arch
