### ISSUE TITLE
[bug] project root is not supported as project

### ISSUE THREAD

**Issue by dec0dOS** [moonrepo/moon#1107]
**Describe the bug**

1. Create the following `workspace.yml`:
```yml
projects:
  root: "."
```
2. Run `yarn moon project root`
Output:
```
❯ yarn moon project root
Error: id::invalid_format

  × Invalid format for //, may only contain alpha-numeric characters, dashes
  │ (-), slashes (/), underscores (_), and dots (.), and must start with an alpha
  │ character.
```

**Expected behavior**

Project root could be used as a project

**Additional context**

I want to utilize specific tasks that should only be run from the project's root directory. Placing these tasks in tasks.yml without specifying the project makes them available globally.

**Comment by milesj** [comment]
@dec0dOS Hrmm something weird is going on here. It thinks the project name is `//`, but I was able to use `root: '.'` locally just now without issue.

Can you paste the `--log trace` output? Also, if you clear `.moon/cache` does it resolve itself?
