### ISSUE TITLE
[feature] globs patterns for running commands

### ISSUE THREAD

**Issue by dec0dOS** [moonrepo/moon#1108]
**Is your feature request related to a problem? Please describe.**

Allow globs patterns for running commands.

Current behaviour:
```
❯ yarn moon run "*:build"
error: invalid value '*:build' for '<TARGETS>...': Invalid target *:build, must be in the format of "scope:task", with acceptable identifier characters.

For more information, try '--help'.
```

Expected: running `build` command for all projects.

**Describe the solution you'd like**

I would like to have the ability to execute commands in different projects using a pattern-based approach. For example, I'd like to be able to run a command like:

```sh
moon run "test-*:run"
```

**Comment by milesj** [comment]
@dec0dOS You can use `moon run --query` for this: https://moonrepo.dev/docs/commands/run

More info on the query language: https://moonrepo.dev/docs/concepts/query-lang
