### ISSUE TITLE
[feature] ability to run multiple interactive commands

### ISSUE THREAD

**Issue by dec0dOS** [moonrepo/moon#1109]
**Is your feature request related to a problem? Please describe.**

Currently, running something like this is not possible:
```
❯ yarn moon run :upgrade-deps -i
Error:   × Only 1 target can be ran as interactive. Requires a fully qualified project
  │ target.
```

**Describe the solution you'd like**

I'd like to be able to run the specified command in random order, with displaying the current active project as a prerequisite.

**Comment by milesj** [comment]
The `--interactive` option is kind of a brute force path, so there's not much to do here at the moment.

However, you can maybe use the `interactive` task option? https://moonrepo.dev/docs/config/project#interactive

**Comment by milesj** [comment]
This should work now in 1.15.2
