### ISSUE TITLE
[feature] The possibility to hide tasks in Moon Console

### ISSUE THREAD

**Issue by darkyelox** [moonrepo/moon#1111]
**Is your feature request related to a problem? Please describe.**

I want the option for hiding tasks in the Moon Console extension, if there are too many global tasks inherited by many projects each time I open an project I see a mix of project and global tasks, that could be too verbose and a waste of space ( visualizing all in the same group) and time (trying to find a project task that is not a global task can be cumbersome ). 

In my case I will have many global tasks that must be extended by project tasks, those global tasks shouldn't be executed alone and only be extended, so it would be nice to hide them from the console.

**Describe the solution you'd like**

It could be a good idea to create a new options group in the tasks structure of the moon.yml and tasks.yml files, maybe something like a `console` block where users might put options for the Moon Console, one of them could be the `visible: boolean` option, if false the task should not be visible in the Moon Console view.

```yml
tasks:
  test:
    # ...
    console:
      visible: false
```

**Describe alternatives you've considered**

N/A

**Additional context**

![image](https://github.com/moonrepo/moon/assets/8183191/8e780943-e38b-489f-a443-5ccdc27e0aa2)

**Comment by milesj** [comment]
@darkyelox I made this change in the vscode extension itself. In v0.7.0, there's now a `moon.hideTasks` setting.

Simply add targets to hide them in the panel.
