### ISSUE TITLE
[bug] disable No targets to run based on touched files when running moon ci

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#1119]
Is there a way to disable `No targets to run based on touched files` and always run all targets when running `moon ci`. I have noticed that usually when I use `git tag` to publish a new release, `moon ci` doesn't do anything due to `No targets to run based on touched files`.

**Comment by milesj** [comment]
`moon ci` is powered entirely by touched files. You probably just want to use `moon run` in this case.

**Comment by milesj** [comment]
Yeah the more I think about this, I think `moon run` or `moon check` is a better choice here.

If you're using GH actions, you can control this with the `if: ${{ }}` statement.
