### ISSUE TITLE
[feature] Use global node in docker

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/moon#1124]
**Is your feature request related to a problem? Please describe.**

```dockerfile
FROM node:19.1.0 AS base
```
I have this in my dockerfile, yet moon goes through the `installing node 19.1.0` procedure which often fails becuase the nodejs website is down (or whatever reason). Can I have moon use this global node installation instead?

**Describe the solution you'd like**

The install node and yarn steps will not run at all,

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by milesj** [comment]
In 1.16!

**Comment by IgnisDa** [comment]
The env variable is `MOON_TOOLCHAIN_FORCE_GLOBALS=true`.
