### ISSUE TITLE
[bug] interactive commands doesn't allocate tty

### ISSUE THREAD

**Issue by dec0dOS** [moonrepo/moon#1131]
1. Use yarn package manager
2. Install moon via yarn
3. Add the following content to package json to scripts section:
```
    "upgrade:deps:root": "yarn upgrade-interactive"
```
4. Run `yarn moon run --interactive :upgrade-deps-root`

Output:
```
❯ yarn moon run --interactive :upgrade-deps-root
▪▪▪▪ root:upgrade-deps-root
Internal Error: Interactive commands can only be used inside a TTY environment
```

**Expected behaviour**

Interactive commands allocate TTY successfully

**Additional context**

Refers to https://github.com/moonrepo/moon/issues/1109

**Comment by milesj** [comment]
Can you paste the log output.

**Comment by milesj** [comment]
Ok figured it out. Will patch soon.

**Comment by milesj** [comment]
PR https://github.com/moonrepo/moon/pull/1132
