### ISSUE TITLE
[feature] Add support for installing rust targets

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#1136]
I would like to support cross compilation for rust to different targets from the same machine. Right now I need to ask folks to copy paste from docs to add targets such as `rustup target add aarch64-unknown-linux-gnu`.

More details at https://doc.rust-lang.org/rustc/platform-support.html.

**Comment by milesj** [comment]
https://github.com/moonrepo/moon/pull/1152

**Comment by milesj** [comment]
In 1.16!
