### ISSUE TITLE
[feature] Allow to install rustup components

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#1137]
I use vim which requires rust-analyzer components to be installed to get LSP working.

Add support for adding components such as rust-analyzer. Right now every time I update rust version I need to run the following command. Having moon take care of this automatically would be beneficial.

```
rustup component add rust-analyzer
```

**Comment by milesj** [comment]
https://github.com/moonrepo/moon/pull/1152

**Comment by milesj** [comment]
In 1.16!
