### ISSUE TITLE
[feature] Multiple commands for a task

### ISSUE THREAD

**Issue by Hecatron** [moonrepo/moon#1138]
As a suggestion it might be handy to be able to run multiple commands for a given task
One idea would be to allow for the `commands` as well as `command` keyword the same way nx does it
Something like this:
```ts

tasks:

  panda.build.cssfile:
    commands:
      - 'mkdirp dist/panda'
      - 'panda cssgen --outfile dist/panda/styles.css'
```

The current workaround is to have each command as a seperate task, linked by deps
Or the use of concurrently
```ts
tasks:

  panda.build.cssfile:
    platform: 'system'
    command: 'pnpm concurrently \"mkdirp dist/panda\" \"panda cssgen --outfile dist/panda/styles.css\"'
```

Just to add, really apreciate the project btw, yaml syntax is very nice, fast with rust and multiple language support.

**Comment by milesj** [comment]
Task inheritance + the toolchain makes this very difficult right now.

More information: https://moonrepo.dev/docs/faq#how-to-run-multiple-commands-within-a-task

**Comment by grbd** [comment]
Yep the && approach doesn't work under windows unfortunatley due to the shell being different.
The suggested options there look to be the same as what I suspected above

**Comment by milesj** [comment]
For v2, I'm hoping to redo all of this and how the toolchain finds binaries. Should make this a lot easier.

**Comment by grbd** [comment]
That sounds cool, it may be a bit of an edge use case but I wonder if adding the package manager from toolchain.yml might be useful to the list of available tokens

  * https://moonrepo.dev/docs/concepts/token

So you could do something like this
```ts
tasks:

  panda.build.cssfile:
    platform: 'system'
    command: '$packageManager exec concurrently \"mkdirp dist/panda\" \"panda cssgen --outfile dist/panda/styles.css\"'
```

since I couldn't get concurrently to work with the package manager downloaded by moon for some reason.

**Comment by milesj** [comment]
We've landed a solution for this https://moonrepo.dev/blog/moon-v1.27#new-task-scripts
