### ISSUE TITLE
[feature] Run node install during `moon setup`

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#115]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

We should run the node install action during `moon setup`, so that node modules are installed, engines are synced, etc.

Otherwise, a task needs to be ran for these to happen.

**Describe alternatives you've considered**

**Additional context**

**Comment by kination** [comment]
@milesj is `setup` means `yarn moon run <project>:build`, or are there other thing?
(because seems `node_modules` are being created when running this)

**Comment by milesj** [comment]
@kination This is for the `moon setup` command, which is a stand alone command unrelated to `moon run`.

**Comment by kination** [comment]
@milesj thanks. Want to ask few question....
- Is `setup` command to add project initiation files (such as workspace.yml, package.json...)?
- Can I build `moon` cli tool from project? Want to test in local...
- Looks like `moon setup` is setting up the codes in current directory. How about getting option for 'target directory'?

**Comment by milesj** [comment]
@kination 

A few things:

> Is setup command to add project initiation files (such as workspace.yml, package.json...)?

The `moon init` command is used to add moon to a repo. This creates the `.moon` folder and config files.

The `moon setup` command is for setting up the toolchain, after moon has been initialized and configured.

> Can I build moon cli tool from project? Want to test in local...

If you want to build moon directly, there's info in the contributing guide: https://github.com/moonrepo/moon/blob/master/CONTRIBUTING.md#development-workflow

> Looks like moon setup is setting up the codes in current directory. How about getting option for 'target directory'?

You probably want `moon init`, which does allow for a target directory.

**Comment by milesj** [comment]
Going to close this. Node install is tied to a project, so running outside the context of a project makes no sense.
