### ISSUE TITLE
[feature] Enforce toolchain versions in Dockerfile

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/moon#1158]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Since moon already syncs the version in `toolchain.yml` with `package.json`, I feel that it should also enforce and sync versions to dockerfile, i.e., version in `toolchain.yml` should act as a single source of truth.

```dockerfile
FROM node:20.5.1 AS base # this version should be updated when version in `toolchain.yml` is changed
```

**Describe alternatives you've considered**

Right now, I do this manually.

**Additional context**

This might be out of the scope of this project, but figured I should ask here.

**Comment by milesj** [comment]
Since we don't manage the Dockerfile, not sure how feasible this would be.

**Comment by IgnisDa** [comment]
I meant it more under moon's docker integration.

**Comment by milesj** [comment]
Right now none of the docker commands interact with the `Dockerfile`. 

It doesn't make sense to be in `setup` or `prune`, but maybe `scaffold`? There would be a lot of variations to be aware of.

**Comment by IgnisDa** [comment]
On further thought, I agree. Moon does not manage docker, just adds commands to be used in that context.
