### ISSUE TITLE
[bug] moon task in non-default git branch fails

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#1159]
**Describe the bug**

scenario is a github workflow/action. the action does some deploys and only runs on a push to a non-default branch (in this case `dev` is default, and set with `defaultBranch` in `workspace.yml`). we're running the workflow against `main`, and calling a moon command. the result is an obscure error message:

```
Error: process::failed

  × Process git failed with a 128 exit code.
  │ 
  │ fatal: ambiguous argument 'dev': unknown revision or path not in the
  │ working tree.
  │ Use '--' to separate paths from revisions, like this:
  │ 'git <command> [<revision>...] -- [<file>...]'
```

It looks like moon is trying to perform some kind of ref lookup on command execution. And with the action in question, `dev` is not checked out from git, but `main` is, so `dev` is actually missing. I'm going to snag you some logs here shortly and will open an issue with the log result. the command: `moon run :deploy --query "projectSource~services/* || projectSource~apps/*" --concurrency 1 --log trace`

**Steps to reproduce**

reproduction is tricky. I'm going to DM you the log trace on Discord, because it contains some sensitive information. 

**Expected behavior**

Successful run. Moon shouldn't error if the default branch is not checked out. 

**Screenshots**

**Environment**

```
Ubuntu, Github Actions
```

**Additional context**

**Comment by shellscape** [comment]
(Referencing the log trace I DM'd) This looks like the problem area:

```
[DEBUG 02:31:47] moon_process::command_inspector:run  Running command git --version  env_vars={} working_dir="/home/runner/work/repo/root"
[DEBUG 02:31:47] moon_process::command_inspector:run  Running command git branch --show-current  env_vars={} working_dir="/home/runner/work/repo/root"
[TRACE 02:31:47] moon_cli::queries::touched_files:run  Against remote using base "dev" with head "HEAD" 
[DEBUG 02:31:47] moon_process::command_inspector:run  Running command git merge-base dev HEAD  env_vars={} working_dir="/home/runner/work/repo/root"
[DEBUG 02:31:47] moon_process::command_inspector:run  Running command git merge-base origin/dev HEAD  env_vars={} working_dir="/home/runner/work/repo/root"
[DEBUG 02:31:47] moon_process::command_inspector:run  Running command git merge-base upstream/dev HEAD  env_vars={} working_dir="/home/runner/work/repo/root"
[DEBUG 02:31:47] moon_process::command_inspector:run  Running command git merge-base HEAD  env_vars={} working_dir="/home/runner/work/repo/root"
[DEBUG 02:31:47] moon_process::command_inspector:run  Running command git --no-pager diff --name-status --no-color --relative -z dev  env_vars={} working_dir="/home/runner/work/repo/root"
```

**Comment by shellscape** [comment]
Workaround:

```
      - name: Moon Fix - Ensure dev Branch is Fetched
        run: git fetch origin dev
```

This works, and moon functions normally. If I change this to `git fetch origin dev --depth` and assign any depth, moon fails with the same error as above. While this gets us unblocked, having the workflow checkout the _entire_ default branch is not ideal.

**Comment by milesj** [comment]
@shellscape All `moon run/check/ci` commands always diff against git, so this is expected. The error I'm guessing is because the branch/ref doesn't exist in the checkout.

You can maybe set `MOON_BASE` and `MOON_HEAD` to change the refs.

**Comment by shellscape** [comment]
In this scenario there's zero need to diff though. We're in a specific environment that's expected to be in a static state. Would it be possible to set a flag to skip those ops?

**Comment by milesj** [comment]
We run git commands to extract the touched files list. This list is used by a lot more stuff than just the task running, so no, there's currently no way to bypass it.

You can try passing `--affected` which _should_ do a `git status` instead.

**Comment by shellscape** [comment]
yeah that's tricky, in this scenario we very much don't want affected projects. Is this another gotcha with using `moon run` in CI instead of `moon ci`?

Fwiw this is also a scenario where cache doesn't apply and is completely ignored.

**Comment by milesj** [comment]
Yeah it's a bit annoying. 

`--affected` will put it in "local mode" and use `git status`, and then you can use `--force` to bypass the actual affected checks.

**Comment by shellscape** [comment]
It's me, I'm that guy. 🫠

Will give that a shot. And will give `moon ci` another look; I know you made some changes there a while back.

**Comment by milesj** [comment]
@shellscape Did that work?

**Comment by shellscape** [comment]
Been swamped and haven't been able to check just yet. This is still on my radar though 👍

**Comment by shellscape** [comment]
Ran into some other (user) issues with `moon ci` and couldn't dig into it further. The workaround above is pretty solid so far so I think we can close on that.
