### ISSUE TITLE
Project with . included in deps causes error in project graph

### ISSUE THREAD

**Issue by ethanjdiamond** [moonrepo/moon#1166]
**Describe the bug**

The moon documentation says that [. is a valid character for project names](https://moonrepo.dev/docs/concepts/project#names). However, there's an error if you have a task with deps on a project with a '.' in it. For example, if you do `moon query projects` while in this state, moon will fail with `Error: query::parse::failed`.

**Steps to reproduce**

1. In `.moon/workspace.yaml` set up a projects glob of  `apps/*`.
2. Create a folder called `causes.bug` in the apps folder with a moon.yml with a task called `see_bug`
3. Create a folder called `project` in the apps folder with a moon.yml with a task that has `causes.bug:see_bug` in it's deps
4. Run `moon query projects`
5. Note error

**Expected behavior**

I would expect this to behave as any other deps on a project's task

**Environment**

 System:
    OS: Linux 6.4 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (13) arm64 unknown
    Memory: 5.73 GB / 7.67 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.8.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Managers:
    Apt: 2.6.1 - /usr/bin/apt
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 12.2.0 - /usr/bin/gcc
    Git: 2.42.0 - /usr/local/bin/git
    Mercurial: 6.3.2 - /usr/bin/hg
    Subversion: 1.14.2 - /usr/bin/svn
    Curl: 7.88.1 - /usr/bin/curl
  IDEs:
    Nano: 7.2 - /usr/bin/nano
    VSCode: 1.83.1 - /vscode/vscode-server/bin/linux-arm64/f1b07bd25dfad64b0167beb15359ae573aecd2cc/bin/remote-cli/code
  Languages:
    Bash: 5.2.15 - /usr/bin/bash
    Perl: 5.36.0 - /usr/bin/perl
    Python3: 3.11.2 - /usr/bin/python3

**Additional context**

I'm running this in a devcontainer. Doubt that matters, but there you go.

**Comment by milesj** [comment]
@ethanjdiamond Can you paste the `--log trace` lines about `moon_query`?

I think I need to add a period here: https://github.com/moonrepo/moon/blob/f92ac8b02a388bc582201c68359923e009a4914d/nextgen/query/src/mql.pest#L4 but not positive.

**Comment by milesj** [comment]
I think I got it here https://github.com/moonrepo/moon/pull/1167

**Comment by milesj** [comment]
Ok fixed in 1.16.1

**Comment by ethanjdiamond** [comment]
Thanks!
