### ISSUE TITLE
[bug] `moon console` VSCode extension unable to find moon binary.

### ISSUE THREAD

**Issue by mctrafik** [moonrepo/moon#1170]
**Describe the bug**

No matter what I tried, the VSCode extension doesn't find the workspace root.

**Steps to reproduce**

Not sure. My dir tree:

```
/Users/user/coding/workspace/project
 - .moon
    - workspace.xml etc
 - typescript
    - node_modules
      - moon stuff
```

But moon is installed using a bash script, so it's at: `/Users/user/.moon/bin/moon`. The extension asks for relative paths. Which is all very confusing. I tried pasting absolute path as well as relative to project. Nothing happens.

I tried finding any logs in the `extensions host` but there weren't any from the extension.

**Expected behavior**

I expect it to detect the moon workspace in the root of the repo. And if not, for there to be debug logs in the extension host that would be helpful for troubleshooting.

**Screenshots**

![Screenshot 2023-11-08 at 5 05 58 PM](https://github.com/moonrepo/moon/assets/1694347/36bcb438-27b1-4d87-a849-76f3f2491cc6)

**Comment by milesj** [comment]
@mctrafik 

For the moon binary, it's probably finding it since we fallback to the global: https://github.com/moonrepo/dev/blob/master/packages/vscode-extension/src/moon.ts#L13

As for the workspace root, is the vscode root === the moon root? That should _just_ work: https://github.com/moonrepo/dev/blob/master/packages/vscode-extension/src/moon.ts#L37

**Comment by mctrafik** [comment]
I'm not sure how to answer. I have many folders in my workspace. 

But I've tried both `.` and `./my-specific-package` as workspace root var with no results. Is there a way to force re-init or see init logs?

**Comment by milesj** [comment]
I'm not entirely sure how to debug a vscode extension. There's no logging in the extension itself, so if vscode doesn't provide anything, then we have nothing at the moment.

No one else has reported this issue. What vscode and moon versions?

**Comment by mctrafik** [comment]
Okay, so I did some digging, and I'm pretty sure this is the bug: 

https://github.com/moonrepo/dev/blob/master/packages/vscode-extension/src/extension.ts#L8

```
  const workingDir = vscode.workspace.workspaceFolders?.[0];
  const workspaceRoot = workingDir ? await findWorkspaceRoot(workingDir) : null;
```

I was very confused by the whole `workspaceRoot` concept because I have many repositories in my workspace. Looks like the extension only looks at the first folder in the workspace. My moonrepo based repository isn't the first one.

Oddly enough, I did try to set my workspace root to `../myOtherFolder` but it still didn't find it. Too tired to keep troubleshooting now.

For context on making logs for the extension. In your code I was able to define a variable `const extOut = vscode.window.createOutputChannel('moon');` and then I was able to make log statements like `extOut.appendLine('INFO: Activating extension.');`

**Comment by milesj** [comment]
Can you briefly talk about/outline your repository structure, where moon is setup, and what folder youre opening with vscode, so that I can get a better picture?

**Comment by mctrafik** [comment]
Sure. I think what's missing here is that I have *many* folders in my workspace. I.e. my workspace is created by starting a blank workspace and then adding multiple folders to it via `Add folder to workspace...` button.

![image](https://github.com/moonrepo/moon/assets/1694347/a4de4845-2dd6-416f-9699-9007f1e9b4b1)

Now, for me, all of the repositories are in the same folder and I have a workspace folder for my vscode with the following structure:

```
/Users/user/workspace/
 - repo1-common/
 - repo2-apps/
 - repo3-shared-monorepo/ (using moon)
```

It is the third repo/folder that I'm trying to use `moon` at. It has structure like:

```
/Users/user/workspace/repo3-shared-monorepo/
 - .moon/
 --- workspace.yml
 --- tasks.yml
 - java/
 - shell/
 - typescript/
 --- package.json
 --- moon.yml (typescript root).
```

A tricky thing here that I'm reporting is that if my moom experiment goes well, I'll probably convert `repo1-common` to use `moon` as well eventually, which means a search for the moon binary will yield multiple resuts.

**Comment by milesj** [comment]
Ok yeah, right now the extension kind of assumes that you're opening it at the root of the moon workspace, but this is like a parent folder up. It should be easy enough to support, so let me tinker around a bit with it.

**Comment by milesj** [comment]
@mctrafik Quick question, so setting the `moon.workspaceRoot` vscode setting to "./repo3-shared-monorepo" did not work?

**Comment by mctrafik** [comment]
That's correct. That doesn't work.

**Comment by milesj** [comment]
That's wild :o

**Comment by MadsLasso** [comment]
I have about the same problem as mctrafik. We have projects nested fairly deeply nested away from the monorepo/moon root, and prefer to open the individual project folder in VSCode. So I need to go upwards in the "Workspace Root" config path, something `../../../.`, but haven't been able to get it to work. I _have_ managed to get it to work for the Bin Path, when using proto rather than npm, this path works `../../Users/Mads/.moon/bin/moon`.

**Comment by milesj** [comment]
This PR will support multiple workspace folders: https://github.com/moonrepo/dev/pull/61
