### ISSUE TITLE
[feature] One-version for core dependencies.

### ISSUE THREAD

**Issue by mctrafik** [moonrepo/moon#1171]
**Is your feature request related to a problem? Please describe.**

I want to standardize the dependency version for a huge mount of packages for my monorepy. I.e. one typescript, one react, one react-dom, one jest etc. Previously I've done this by having a root project (with npm workspaces) and other packages inherit from it. 

I can't figure out how to get that root package to be installed using moon.

I can't figure out how to prohibit other packages from overriding the package version (don't want to write another sync script).

I can't figure out how to ensure that all packages share the same version of core dependencies. 

I.e. if package/demo1/pakcage.json specifies typescript@5.0.0 and package/demo2/package.json specifies typescript@5.1.0 I'd like those to be reconciled to one version or display an error to the user. 

**Describe the solution you'd like**

From the [documentation](https://moonrepo.dev/docs/comparison) where it says `Can sync cross-project dependencies to package.json` I thought this was already implemented. But I don't see it working. In fact the root package.json is ignored, and conflicting versions in sibling packages aren't touched by moon tooling.

**Describe alternatives you've considered**

A. I can write a unit test scanning package.json files manually and error out if incompatible versions are found. I'd also need to write a tool that would remove those deps if they're specified in the root folder.
B. I think I'd also need to move my root package.json outside of the `typescript` folder (undesired) for moon to see it. Or I have to list it as a sibling project (even though it's a root).

**Additional context**

**Comment by mctrafik** [comment]
I found some settings to help define the root project:

toolchain.yml

```
typescript:
  rootConfigFileName: "typescript/tsconfig.json"
  rootOptionsConfigFileName: "typescript/tsconfig.options.json"
```

workspace.yml

```
projects:
  root: "typescript"
```

But I still see conflicting versions in each package.

**Comment by milesj** [comment]
> I can't figure out how to get that root package to be installed using moon.

The root `package.json` that has `workspaces` (for monorepo setup) can define dependencies.  Are you saying these deps don't get installed?

> I can't figure out how to prohibit other packages from overriding the package version (don't want to write another sync script).

This isn't something that moon prevents. You would need your own custom scripts to check this.

> I can't figure out how to ensure that all packages share the same version of core dependencies.

Same as the previous answer. You'll need something custom here.

> From the [documentation](https://moonrepo.dev/docs/comparison) where it says Can sync cross-project dependencies to package.json I thought this was already implemented. But I don't see it working. In fact the root package.json is ignored, and conflicting versions in sibling packages aren't touched by moon tooling.

This isn't npm dependencies, this is local packages required for monorepo setups. The `workspace:*` kind of stuff.

With all that being said, this is known as the "single version policy" or "one version policy" and is something that I want to build into moon directly, but it currently does not exist. It assumes your using workspaces for monorepos.

**Comment by milesj** [comment]
Added a setting to support the one version policy pattern. https://moonrepo.dev/blog/moon-v1.17#supporting-the-single-version-policy-pattern
