### ISSUE TITLE
[bug] changing contents of moon.yml doesn't invalidate the cache

### ISSUE THREAD

**Issue by niieani** [moonrepo/moon#1172]
**Describe the bug**

changing args in moon.yml doesn't invalidate the run cache of the command in question

**Steps to reproduce**

1. create a project called "test" 
2. create a moon.yml in a project: "test":
   ```yml
   $schema: https://moonrepo.dev/schemas/project.json
   tasks:
     echo:
       command: echo
       args:
         - test1
   ```
3. execute the task: `moon run test:echo`
4. it will echo "test1"
5. change the moon.yml to print "test2"
6. execute the task: `moon run test:echo`

**Expected behavior**

It should run "echo test2", because the task definition has changed, but it still displays "test1" from the cached run.

Additionally, failing results should never be cached if inputs aren't specified. When I use a command that exists with status code > 0, it should not store the the failing output by default. I'd like to be able to make changes to the config file and retry the command, but that's not possible.

**Environment**

```
  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.24 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - ~/.proto/bin/node
    npm: 10.2.0 - /opt/homebrew/bin/npm
    bun: 1.0.7 - ~/.bun/bin/bun
  Managers:
    Cargo: 1.74.0 - ~/.cargo/bin/cargo
    Homebrew: 4.1.18 - /opt/homebrew/bin/brew
    pip3: 23.2.1 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    CMake: 3.27.7 - /opt/homebrew/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.42.0 - /opt/homebrew/bin/git
    Clang: 17.0.4 - /opt/homebrew/opt/llvm/bin/clang
    Ninja: 1.11.1 - /opt/homebrew/bin/ninja
    FFmpeg: 6.0 - /opt/homebrew/bin/ffmpeg
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Parallels: 18.0.3 - /usr/local/bin/prlctl
  IDEs:
    VSCode: 1.82.0 - /opt/homebrew/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.21.3 - /opt/homebrew/bin/go
    Perl: 5.30.3 - /usr/bin/perl
    Protoc: 24.4 - /opt/homebrew/bin/protoc
    Python3: 3.11.6 - /opt/homebrew/bin/python3
    R: 4.3.1 - /usr/local/bin/R
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.74.0 - /Users/bbrzoska/.cargo/bin/rustc
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.0
```

**Additional context**

**Comment by milesj** [comment]
@niieani What moon version? This sounds very similar to some issues that were fixed a while back.

If the latest, what does `moon task <target> --json` show, before and after changing the argument.

You can also inspect the task hash with `moon query hash <hash>` to see what's actually included in the hash/cache.

**Comment by milesj** [comment]
I just tested the echo task and the exit code non-0 on master (1.16.1), and they all work as expected.

**Comment by niieani** [comment]
```
$ moon --version
moon 1.16.1
```

Interestingly, when I run `yarn moon task test:echo` it shows the correct, updated task. 
But when I run it, it only prints the stale stdout. 

I've tried debugging the run. Looks like the hash is generated incorrectly, because it doesn't include moon.yml. 
I think I know why. It looks like moon is creating a hash using `git hash-object`, but since my project is gitignoring all the moon.yml files - it's not picking up any changes to moon.yml. 

Note that I generate my moon.yml (and other config files) in postinstall, using my own configuration tool (soon to be open source).

**Comment by milesj** [comment]
`moon.yml` isn't included in the hash on purpose, because changing the config of a sibling task shouldn't invalidate the cache of all it's siblings.

Can you diff the hash of echo1 vs echo2 (`moon query hash-diff`) and see if the contents actually change?

**Comment by niieani** [comment]
Looks like the hash is the same even both before and after I change the task definition in moon.yml, so hash-diff doesn't really make sense, cause it's the same hash.

**Comment by milesj** [comment]
So I was thinking about this more, and I believe the `.gitignore` is the culprit.

We don't use the `moon.yml` file itself for task hashes, but we do use it for the project graph hash (https://github.com/moonrepo/moon/blob/master/nextgen/project-graph/src/project_graph_builder.rs#L382), which also feeds into tasks.

**Comment by niieani** [comment]
Any idea on how this can be solved? I'm using a config generator to dynamically generate configs for all the tools I use, hence the usage of gitignore for moon config files. Could you make it so that moon.yml is used for project graph hash, regardless of its presence in `.gitignore`?

**Comment by milesj** [comment]
Yeah, will enable it in the next path and we'll see how it works.

**Comment by milesj** [comment]
Can you try 1.16.4

**Comment by niieani** [comment]
Yup, 1.16.4 fixed it! Thanks @milesj!
