### ISSUE TITLE
[feature] allow TS root to be customized

### ISSUE THREAD

**Issue by mctrafik** [moonrepo/moon#1175]
**Describe the bug**

My folder structure (relevant files):

```
/ 
 - .moon/
 --- toolchain.yml
 --- workspace.yml
- typescript/
--- apps/demo-app/
----- tsconfig.json
--- tsconfig.json
``` 

Inside of the toolchain.yml I specify:

```
typescript:
  rootConfigFileName: "typescript/tsconfig.json"
  rootOptionsConfigFileName: "typescript/tsconfig.options.json"
```

And inside workspace.yml:

```
projects:
  root: "typescript"
  demo-app: "typescript/apps/demo-app"
```

**Steps to reproduce**

Running `moon sync projects` incorrectly updates the root `tsconfig.json` with the path to other packages.

Specificially, inside of `typescript/tsconfig.json` I see:

```
{
  "extends": "./tsconfig.options.json",
  "compilerOptions": {
    "emitDeclarationOnly": true,
    "outDir": "../.moon/cache/types/typescript"
  },
  "files": [],
  "references": [
    {
      "path": "typescript"
    },
    {
      "path": "typescript/apps/demo-app"
    }
  ]
}
```

which is wrong because it's already in the `typescript` folder, and references need to be relative to that.

**Expected behavior**

I expect the tsconfig to be:

```
{
  "extends": "./tsconfig.options.json",
  "compilerOptions": {
    "emitDeclarationOnly": true,
    "outDir": "../.moon/cache/types/typescript"
  },
  "files": [],
  "references": [
    {
      // No self-reference.
      // Note this reference is relative.
      "path": "./apps/demo-app"
    }
  ]
}
```
**Screenshots**

![Screenshot 2023-11-12 at 6 30 21 PM](https://github.com/moonrepo/moon/assets/1694347/f87859e7-f9ab-4ff3-ab83-17f1b67e76f6)

**Environment**

```
moon 1.16.1
```

**Comment by milesj** [comment]
The TS root functionality/settings were designed for it to actually be at the workspace root. Calling a project "root" doesn't actually make it root, the project _must_ be the literal root (source of `.`): https://moonrepo.dev/docs/guides/root-project

**Comment by mctrafik** [comment]
I see. Would you mind changing this to a feature request then?

My reasoning for this feature:

I'm trying to have the repo have languages separated, i.e. /typescript and /java in separate folders. The idea behind us using moon was to be able to depend on compilation or common interfaces before compiling UIs and building artifacts. Either way, the point is that I'd need the root typescript project to be under the /typescript folder. Otherwise a lot of the common code and config files for typescript *have* to be under `/` where they don't belong.

**Comment by milesj** [comment]
I don't see any reason _not_ to support it, but no guarantee when it would land.

**Comment by milesj** [comment]
Started on this here https://github.com/moonrepo/moon/pull/1190

**Comment by milesj** [comment]
Added a new setting for this: https://moonrepo.dev/blog/moon-v1.17#configure-the-root-directory
