### ISSUE TITLE
[bug] `syncProjectReferencesToPaths` doesn't work

### ISSUE THREAD

**Issue by JonDum** [moonrepo/moon#1191]
Heyo

Been experimenting with Moon today. Came across a bug with ts path syncing... it doesn't work?

Sorry if I'm missing anything but I even reduced down my repo to a barebones example and it still doesn't do anything

https://github.com/JonDum/moon-ts-paths-bug

check out repo

`moon setup`

`moon sync projects`

... check the diffs of the tsconfigs

`references` of each tsconfig get modified

but no `paths` in `compilerOptions`

Am I doing something wrong?

**Comment by milesj** [comment]
@JonDum I think the problem is that the shared package needs 1 of these files: https://github.com/moonrepo/moon/blob/master/crates/node/platform/src/actions/sync_project.rs#L133

We can probably loosen this restriction though and always insert the wildcard.

**Comment by JonDum** [comment]
Ah, that makes sense now!

Thinking it through I see how it'd be hard to interpret what the end user wants to do with the paths feature for a situation without an `index.ts`

I suppose we could assume that if there's no `index.ts`, it adds a wildcard path:

```
"paths": {
  "<package_name>/*": ["<path>/*"]
}
```

so imports can then be `import {x} from '<package_name>/subdir'`

But my use case is probably fringe and non best-practice enough that I'm totally fine if that doesn't make it in.

Feel free to close if you agree

**Comment by milesj** [comment]
Yeah I updated the PR to basically do what your example says. Looking to land it tomorrow/Monday.

**Comment by milesj** [comment]
Just released 1.17 that supports this.
