### ISSUE TITLE
[feature] add support for node.bins

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#1192]
Would be good if we can have support for node.bins or pnpm.bins so we can install tools like prettier that can be available in cli.

**Comment by milesj** [comment]
I've thought about this but the current blocker is that each package manager installs globals differently, and sometimes these are also lost when changing node/pm versions. I wish this was standardized like other tools.

On top of that, proto has its own way of handling globals too, so should that be an option? Not sure.

**Comment by prabirshrestha** [comment]
for now I'm manually installing. It is for editor use only so I'm ok. If I get another use case will reopen.
