### ISSUE TITLE
[docs] improve docs for toolchain

### ISSUE THREAD

**Issue by dec0dOS** [moonrepo/moon#1200]
**Is your feature request related to a problem? Please describe.**

I've noticed that the current documentation doesn't fully explain how to use installed toolchain tools directly. For instance, I'm looking for guidance on commands in moon, such as `nix shell`, or ways to add the declared toolchain in moon to the PATH. It appears that `moon setup` doesn't automatically add the toolchain to the PATH. The toolchain is available only when running inside moon tasks.

**Describe the solution you'd like**

Update and expansion of the documentation to thoroughly cover these aspects. Such an enhancement would greatly aid users in effectively navigating and utilizing the toolchain within moon

**Comment by milesj** [comment]
Yeah definitely. I have plans to rewrite the entire getting started section, especially the toolchain stuff, and I'll add this to the list.

For now, we do have some snippets in the cheat sheet. https://moonrepo.dev/docs/cheat-sheet#languages

**Comment by milesj** [comment]
@dec0dOS moon uses proto under the hood, so you can add proto stuff to your profile.

```
export PROTO_HOME="$HOME/.proto"
export PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$PATH"
```

_However_, I don't think this would work right now if you're not using proto, because moon doesn't download the `proto` binary (which the proto shims require).

**Comment by milesj** [comment]
Yeah that's the plan! I already have it mapped out. Just wondering whether this should be a moon 2.0 kind of change, or land it earlier. It _should_ be transparent to the user.

**Comment by prabirshrestha** [comment]
+1 for this. I have shared some of the projects to others that use moon and port and getting it up running is always a challenge for them. Always need to debug and provide instructions to them. As for me I have set the paths correctly in my dotfiles synced with git repo so isn't an issue getting moon running up from clean OS.

It should be simple as following.

```bash
curl -fsSL https://moonrepo.dev/install/moon.sh | bash
moon setup 
# now run any commands.
```

`moon setup` should install all tools of correct version including moon version and update the environment path. 

In additional to the tools mentioned above can also take learnings from  https://docs.python.org/3/library/venv.html

**Comment by milesj** [comment]
Let me look into this for the next release and see if it's feasible at this time.

**Comment by milesj** [comment]
> Is moon the only one that needs to be installed and proto is no longer required?

proto is required but moon will auto-install it, so not required to be installed manually be the user.

> Does it auto download the correct version of moon? I set this in versionConstraint: '=1.17.3' in .moon/workspace.yml.

It does not. You would need to pin moon using proto or npm.

> What is the command to manually update the env PATH without having to use moon run for my tasks.

You would need proto for this, as it handles all of that. Just ensure the proto shims/bins are in your `PATH`.

```
export PROTO_HOME="$HOME/.proto"
export PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$PATH"
```

**Comment by prabirshrestha** [comment]
If that is the case, would it be possible to also update proto to add auto update the path when using `proto use`?

Currently these are the instructions I have for my project which I think is too long and error prone.

```bash
# Install rustup - https://rustup.rs/
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install proto - https://moonrepo.dev/proto
curl -fsSL https://moonrepo.dev/install/proto.sh | bash

# Add proto to path
export PATH="$HOME/.proto/shims:$HOME/.proto/bin:$PATH"

# Install necessary tools
proto use

# Run server and client in watch mode
ppm dev
```

I would expect this to be simple as 

```bash
curl -fsSL https://moonrepo.dev/install/proto.sh | bash
proto use
pnpm dev
```

Rustup auto updates the environment path. Wondering if photo should have an optional flag to update the environment path when installing but this might require sudo.

**Comment by milesj** [comment]
@prabirshrestha The proto install script does update PATH in your profile, but you'll probably need to reload your shell.

**Comment by prabirshrestha** [comment]
I do see this in the install script.

```
$bin_path setup
```

But I don't see it persist unless `proto setup` is doing it.

For example take this example of what happens when you run ` curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`. This always automatically adds `. "$HOME/.cargo/env"` in `~/.bash_profile` and if in windows it updates the environment variables in the system.

Here is the message from rustup.

```
Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
```

When I install proto it shows the following message but where does the path get updated as I don't see any updates in my `.bash_profile`.

```
/Users/prabirshrestha/.dotfiles$ curl -fsSL https://moonrepo.dev/install/proto.sh | bash
######################################################################## 100.0%
Successfully installed proto to /Users/prabirshrestha/.proto/bin/proto
Launch a new terminal window to start using proto!
```

Ideally I would like proto to update my `.bash_profile`. This allows me to keep by dotfiles sync via git.

```bash
[[ -s ~/.proto/env ]] && . ~/.proto/env
```

**Comment by milesj** [comment]
It adds it to one of these locations, whichever it finds first: https://github.com/moonrepo/proto/blob/master/crates/cli/src/shell.rs#L22

**Comment by milesj** [comment]
New shell approach is available on canary: [1.18.0-canary.202312092028](https://www.npmjs.com/package/@moonrepo/cli/v/1.18.0-canary.202312092028)

If you want to give it a shot!

**Comment by milesj** [comment]
v1.18 is out. I also redid a lot of the docs.

**Comment by milesj** [comment]
@dec0dOS Not at the moon level, you would need to use `.prototools`.

proto is pretty much required for all of the toolchain stuff. You could just not use the toolchain if you don't want any of this.
