### ISSUE TITLE
[feature] moon generate compute destination

### ISSUE THREAD

**Issue by b4nst** [moonrepo/moon#1218]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Often when generating code, I would like moon to force the destination of the code, to keep the repo in harmony. Let's say I have a template "rustapp", it would be nice to have an option for the template to provide a computed destination (like `apps/rust/<project-id>` for example).

This would be configurable from the template definition, as any other variables.

**Describe alternatives you've considered**

No alternative for now

**Additional context**

**Comment by milesj** [comment]
Will land in v1.19 https://github.com/moonrepo/moon/pull/1252
