### ISSUE TITLE
[bug] docker scaffold <project> fails with “Unable to create shims as the proto-shim binary cannot be found”

### ISSUE THREAD

**Issue by Tolsee** [moonrepo/moon#1263]
**Describe the bug**
`moon docker scaffold <project>` fails with following error
```
8.512 ▪▪▪▪ installing node 20.0.0
20.41 Error: proto::shim::missing_binary
20.42
20.42   × Unable to create shims as the proto-shim binary cannot be found.
20.42   │ Looked in the PROTO_INSTALL_DIR environment variable and ~/.proto/bin
20.42   │ directory.
20.42
```
**Steps to reproduce**
Create a [standard multi-stage](https://moonrepo.dev/docs/guides/docker) `Dockerfile` like below
```
# https://moonrepo.dev/docs/guides/docker
FROM --platform=linux/amd64 node:20 AS base

WORKDIR /app
RUN npm install -g @moonrepo/cli

FROM base AS workspace

WORKDIR /app
COPY . .
RUN moon docker scaffold <project>

FROM base AS build

WORKDIR /app
COPY --from=workspace /app/.moon/docker/workspace .
RUN moon docker setup
COPY --from=workspace /app/.moon/docker/sources .
```
**Expected behavior**
Scaffold should be successful
**Screenshots**

**Environment**

```
docker
node@20
```
**Additional context**

**Comment by Tolsee** [comment]
Potentially related to https://github.com/moonrepo/proto/issues/357

**Comment by Tolsee** [comment]
@milesj Experiencing same issue with 1.19.1 as well.

**Comment by milesj** [comment]
@Tolsee Hrmm.... can you enable logging and see if it's installing proto?

**Comment by Tolsee** [comment]
This is the logs that I am getting:
![Screenshot 2024-01-09 at 10 02 34](https://github.com/moonrepo/moon/assets/16590492/aca24ce0-80c0-4fde-b171-73a86c3880b1)

**Comment by milesj** [comment]
Ah looks like you're right. This is actually failing on init before the actual scaffold command is ran. This was unexpected but another easy fix.

**Comment by milesj** [comment]
@Tolsee Ok can you try 1.19.2?

**Comment by Tolsee** [comment]
@milesj 1.19.3 is working as expected 🎉
