### ISSUE TITLE
[bug] moon 1.19.2 realease lists version as 1.19.1

### ISSUE THREAD

**Issue by iyefrat** [moonrepo/moon#1266]
**Describe the bug**

Seems the release commit wasn't done so the programmatic version is wrong

**Steps to reproduce**
1. `moon upgrade`
2. `moon --version`

**Expected behavior**

`moon 1.19.2`

**Screenshots**

`moon 1.19.1`

**Comment by milesj** [comment]
Yeah nice catch, looks like something is out of sync. Let me bump it to 1.19.3.

**Comment by milesj** [comment]
Ok fixed, thanks for pointing out.

**Comment by iyefrat** [comment]
Thanks!
