### ISSUE TITLE
[feature] Better support with existing nodejs ecosystem

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#1272]
Is it possible for moon to play nicely with existing node version manager such as nvm instead of having custom locations and installation of node. My primary reason for this is seems like `npm install -g package` doesn't seem to work and lot of software out there has dependencies on auto install npm packages during configuration. As soon as I go out of npm package it stops working.

This is where the rust implementation is great, because moon assume rustup is installed and delegates to it. Wondering if something similar can be done for node and npm so it plays nicely with existing ecosystem. It is also a difficult when there are new folks trying a project that use moon and need to explain why it doesn't work.

Currently my solution when using some projects that requires global npm installation is to comment out proto/moon path and restart the shell.

**Comment by milesj** [comment]
@prabirshrestha Are you referring to the intercept error that proto does? You can configure and turn that off: https://github.com/moonrepo/node-plugin#configuration

This will be changing in proto v1 since it's a breaking change.

**Comment by milesj** [comment]
In 1.20, I turned off that intercept global error.

**Comment by milesj** [comment]
Gonna close this since there's been a lot of devx improvements in the node/npm/etc proto stuff.
