### ISSUE TITLE
[bug] moon reports wrong version after upgrade via proto from 1.18.5 to 1.19.3

### ISSUE THREAD

**Issue by alexbepple** [moonrepo/moon#1274]
**Describe the bug**

moon reports wrong version after upgrade via proto from 1.18.5 to 1.19.3.

This might be a bug with `proto`, but it’s not easy for me to discern. I am more inclined to think that this is `moon` itself.

**Steps to reproduce**

I cannot reproduce this from scratch. :-( But please bear with me. The behavior is distinctly odd.

I am in a repo with the following in `.prototools`:
```
moon = "1.18.5"

[plugins]
moon = "source:https://raw.githubusercontent.com/moonrepo/moon/master/proto-plugin.toml"
```

As one would expect, `moon --version` reports `moon 1.18.5`.

Now I  upgrade moon: `proto install moon 1.19.3` and then `proto pin moon 1.19.3`. Unsurprisingly, `.prototools` now lists `moon = "1.19.3"`.

Now the surprising bit: `moon --version` still reports `moon 1.18.5`.

Related observations:
```
❯ proto bin moon
/Users/ab/.proto/tools/moon/1.19.3/moon

❯ /Users/ab/.proto/tools/moon/1.19.3/moon --version
moon 1.18.5

❯ cd   # let’s go to the home dir

❯ /Users/ab/.proto/tools/moon/1.19.3/moon --version
moon 1.19.3
```

The fact that executing `/Users/ab/.proto/tools/moon/1.19.3/moon --version` from two different working dirs yields two different results, seems extremely odd to me.

I am also very suspicious of the fact that I cannot reproduce this with a fresh repo. This makes me think that something somewhere is cached. But where?!

**Environment**

```
  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 59.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.4.0 - ~/.tea/nodejs.org/v20.4.0/bin/node
    Yarn: 1.22.19 - ~/.proto/shims/yarn
    npm: 9.7.2 - ~/.tea/npmjs.com/v9.7.2/bin/npm
    bun: 1.0.22 - ~/.proto/bin/bun
  Managers:
    Homebrew: 4.2.3 - /opt/homebrew/bin/brew
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 14.0.3 - /usr/bin/gcc
    Git: 2.39.0 - /opt/homebrew/bin/git
    Clang: 14.0.3 - /usr/bin/clang
    FFmpeg: 6.1.1 - /opt/homebrew/bin/ffmpeg
    Curl: 7.85.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.54 - /usr/sbin/apachectl
  Virtualization:
    Docker: 24.0.7 - /usr/local/bin/docker
  IDEs:
    IntelliJ: 2023.2.3
    VSCode: 1.85.1 - /opt/homebrew/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.19.4 - /opt/homebrew/bin/go
    Perl: 5.30.3 - /usr/bin/perl
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 120.1.61.114
    Chrome: 120.0.6099.216
    Safari: 16.2
```

**Comment by milesj** [comment]
@alexbepple Do you happen to have a `@moonrepo/cli` npm dependency? If so, that version will be used instead, instead of the one globally. This may be part of the confusion.

**Comment by alexbepple** [comment]
Yes, @milesj. That was it. 

I did no longer have `@moonrepo/cli` in my `package.json`. But the installation had remained in `node_modules/` from some very early first steps with `moon`.

Thanks for the resolution. It would have been seriously helpful, if there had been a way to ask `moon` which version it actually uses. Or did I miss a debugging step I could have done?

**Comment by milesj** [comment]
This functionality is kind of hidden. I'll add more logging around it so that it's apparent.
