### ISSUE TITLE
[bug] Zsh completions are tricky to setup on macOS

### ISSUE THREAD

**Issue by bradleyayers** [moonrepo/moon#1288]
**Describe the bug**

As an inexperienced Zsh user (on macOS) it was difficult how to get moon completions working.

I bumped into a few hurdles:

- In what directory do I place the completions? under Bash it seems like a `~/bash_completion.d` directory is common, but I couldn't find the equivalent for Zsh.
- What do I name the file?
- Are there any other commands I need to run to "load" it?

**Steps to reproduce**

1. Go to https://moonrepo.dev/blog/v0.24#shell-completions and see the example for bash.
2. Google around for the Zsh equivalent of bash completions.
3. …continue fumbling around for a while…
4. Search the moon GitHub repo and org for clues

**Expected behavior**

For anyone in the future wanting to know how to set it up (at least on macOS), do:

1. Install oh-my-zsh https://ohmyz.sh
2. Install the completions `moon completions > ~/.oh-my-zsh/completions/_moon` (the filename is important)
3. Reload oh-my-zsh `omz reload`

I couldn't get it working without oh-my-zsh because in the completions it expects `compdef` and `is-at-least` functions to be available, and these don't seem available in vanilla Zsh on macOS.

Hopefully this issue helps someone in the future.

**Comment by milesj** [comment]
Thanks for this, I'll update the docs.

**Comment by milesj** [comment]
Fixed here https://github.com/moonrepo/moon/pull/1291

**Comment by artsiommiksiuk** [comment]
Slight fix in the documentation is needed for this instruction (as this issue lead to this documentation page).
If users didn't have any completions before they'll have to create completions dir manually to make the instructions work.

Like this
```zsh
mkdir -p ~/.oh-my-zsh/completions                
moon completions > ~/.oh-my-zsh/completions/_moon
omz reload
```

Otherwise there will be error  ```zsh: no such file or directory: ...```
