### ISSUE TITLE
[bug] Rust not listed as supported tool in the docs

### ISSUE THREAD

**Issue by bradleyayers** [moonrepo/moon#1294]
**Describe the bug**

https://moonrepo.dev/docs/concepts/toolchain#supported-tools doesn't list Rust as one of the supported tools. I've setup moon with just a Svelte TypeScript project and was ready to add a rust project, but then got a bit lost with how to actually setup rust.

**Expected behavior**

I thought Rust would be listed on https://moonrepo.dev/docs/concepts/toolchain#supported-tools

**Comment by milesj** [comment]
@bradleyayers Thanks, the docs are out of date.

This guide should help: https://moonrepo.dev/docs/guides/rust/handbook If it's still confusing, let me know!

**Comment by milesj** [comment]
Update that page that was out of date.
