### ISSUE TITLE
[bug] docs would be better with more in context `@group(…)` examples

### ISSUE THREAD

**Issue by bradleyayers** [moonrepo/moon#1309]
**Describe the bug**

I wanted to start using file groups and could fairly quickly find the syntax for defining them, but then couldn't easily find many examples of how to actually reference them, e.g.

- https://moonrepo.dev/docs/config/project#inputs
- https://moonrepo.dev/docs/config/project#extends
- https://moonrepo.dev/docs/config/tasks#filegroups (a link to "inputs" to see usage examples would be great)

Shower thought: maybe it would be neat if the YAML keys in the code examples were hyperlinked to the relevant docs sections, e.g. if you could click `inputs:` and it takes you to that section of the docs (this would reduce the amount of text descriptions you'd need with explicit hyperlinks to relevant sections).

**Comment by milesj** [comment]
Updated docs in a few areas to make this more clear.
