### ISSUE TITLE
[bug] docs: TypeScript not listed as a tool

### ISSUE THREAD

**Issue by bradleyayers** [moonrepo/moon#1312]
**Describe the bug**

https://moonrepo.dev/docs/concepts/toolchain#supported-tools doesn't list TypeScript as one of the supported tools.

**Expected behavior**

I thought TypeScript would be listed on https://moonrepo.dev/docs/concepts/toolchain#supported-tools, and link to https://moonrepo.dev/docs/config/toolchain#typescript

**Comment by milesj** [comment]
This is technically correct. Only tools that are downloaded and installed onto a user's machine are considered part of the toolchain. Pretty much programming languages.

TypeScript is a bit weird since it's an npm package within Node/Bun, so technically doesn't count.
