### ISSUE TITLE
SIGINT (CTRL + C) immediately yields controls of the shell without waiting for the task to complete

### ISSUE THREAD

**Issue by affanshahid** [moonrepo/moon#1313]
**Describe the bug**
I have a (local/persistent/interactive) task that does some semi-complicated things which include running a few sub-processes. The task itself is a python script which intercepts CTRL+C and performs some teardown/cleanup then lets the user know when the cleanup is complete. 

Running this script directly works just fine with CTRL+C. Upon sending the signal, the teardown starts and the user is not returned control of the shell until the teardown is complete.

However, running this task through `moon run` and pressing CTRL+C immediately returns control of the shell to the user (while the actual task/script is still running in the background and performing cleanup) causing output from the actual task to intermix with the user's shell control.

I understand this may be a design choice but I feel this specific functionality for CTRL+C should be either configurable or totally disabled for interactive tasks, since interaction also includes signals and the task should have control over how it reacts.

**Steps to reproduce**

Create a python script:

```python
from time import sleep


print("Hello I am a task that is starting")

try:
    sleep(30)
except KeyboardInterrupt as ex:
    print("I am going to do some cleanup and will let you know when I am done")
    sleep(5)
    print("Clean up complete")
```

Create an associated task like:
```yml
  test:
    command: python test.py
    local: true
    options:
      interactive: true
```

Run the task `moon run test` and press CTRL+C after seeing `"Hello I am a task that is starting"`. The shell will return immediately and around 5 seconds later output from the task will overwrite the user's shell control.

**Expected behavior**
The task should be allowed to complete its clean-up after pressing CTRL+C and not yield immediately. Moon should allow disabling the built-in signal handler for interactive tasks.

**Screenshots**
The correct behavior, when running the script directly
![image](https://github.com/moonrepo/moon/assets/17955210/4e7d8737-40bd-4fc2-ab10-fee0ebafe0e1)

The behavior using `moon run`
![image](https://github.com/moonrepo/moon/assets/17955210/452fba00-7fef-4a14-8330-5fccd9ae22c0)

The moment CTRL+C was pressed is highlighted in red

**Environment**

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 10.65 GB / 15.51 GB
    Container: Yes
    Shell: 3.6.0 - /usr/bin/fish
  Binaries:
    Node: 18.19.0 - /mnt/wslg/runtime-dir/fnm_multishells/11128_1707015305320/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.3 - /mnt/wslg/runtime-dir/fnm_multishells/11128_1707015305320/bin/npm
    pnpm: 8.15.1 - /usr/bin/pnpm
  Managers:
    Apt: 2.0.9 - /usr/bin/apt
    Cargo: 1.75.0 - ~/.cargo/bin/cargo
    pip3: 20.0.2 - /usr/bin/pip3
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.4.0 - /usr/bin/gcc
    Git: 2.43.0 - /usr/bin/git
    FFmpeg: 4.2.7 - /usr/bin/ffmpeg
    Curl: 7.68.0 - /usr/bin/curl
  Virtualization:
    Docker: 20.10.12 - /usr/local/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.86.0 - /mnt/c/Users/affan.shahid/AppData/Local/Programs/Microsoft VS Code/bin/code
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Go: 1.18 - /home/affan/.go/current/bin/go
    Perl: 5.30.0 - /usr/bin/perl
    Python3: 3.8.10 - /usr/bin/python3
    Rust: 1.75.0 - /home/affan/.cargo/bin/rustc

```

**Additional context**

**Comment by mwkcoding** [comment]
I have experienced the current behavior causes hanging Node.js processes.

**Comment by milesj** [comment]
Yeah right now ctrl+c basically sends an abort to the thread: https://github.com/moonrepo/moon/blob/master/crates/core/action-pipeline/src/pipeline.rs#L237

Let me see if we can work around this.

**Comment by affanshahid** [comment]
To be on-par with other task runners I think should just forward any signals to the underlying process (which it already does) and then wait for it to exit.

**Comment by milesj** [comment]
Ok I made some changes in 1.21, can you give that a shot.

**Comment by affanshahid** [comment]
This is fixed!

**Comment by milesj** [comment]
Sweet
