### ISSUE TITLE
[bug] tsconfig.json is not parsed as JSON5(?)

### ISSUE THREAD

**Issue by bradleyayers** [moonrepo/moon#1327]
**Describe the bug**

`tsconfig.json` support comments and trailing commas, but moon does not. With such a file it reports a syntax error, e.g.:

```
Error: json::parse_file

  × Failed to parse JSON file ~/src/haohao.how/projects/emails/tsconfig.json.
  ╰─▶ trailing comma at line 42 column 3
```

In this case it refers to a trailing comma in the `includes` array, e.g.:

```
  "include": [
    ".*.ts",
    ".*.tsx", // <-- this one
  ],
```

**Comment by milesj** [comment]
The lib we use is supposed to strip them, but seems like it's not: https://crates.io/crates/json-strip-comments

Is this on the latest moon version?

**Comment by bradleyayers** [comment]
This was on `1.19.3`, it works fine on `1.21.2`. My bad!

**Comment by milesj** [comment]
Glad it works.

It should have worked before too :p I'll still dig in and see what's up.
