### ISSUE TITLE
[feature] affectedFiles should pass in all input files when there are no affected files instead of `.`

### ISSUE THREAD

**Issue by affanshahid** [moonrepo/moon#1329]
**Is your feature request related to a problem? Please describe.**

I really like how the `--affected` option behaves especially when working with pre-commit hooks for formatting/linting tasks. However when you want to format the entire project (say when you wipe the cache or another such scenario), there is an issue. By default `.` is passed in when there are no affected files regardless of what the input is, this makes it impossible to filter out certain files from the formatting. I could simply use `@files()` or another token in the command args directly to manually exclude files but then you lose the benefits of `--affected` with `affectedFiles: true`.

**Describe the solution you'd like**

When there are no affected files, moon should pass in ALL the files matched by the inputs instead of `.`. Moon should resolve the input globs as it normally does for affected and pass in the total result instead of just `.`.

**Describe alternatives you've considered**

The current solution requires using the underlying tools ignore options (i.e .prettierignore) but not all formatting tools might support something like this and it adds yet another configuration file to the repo. I'd like this to be configurable through moon since it already knows which files my task operates on.

**Additional context**

**Comment by milesj** [comment]
This seems reasonable, I can look into it.

**Comment by milesj** [comment]
Landed in 1.22

**Comment by milesj** [comment]
Reopening as this seems to cause issues with other tasks: https://github.com/moonrepo/moon/issues/1353

We may have to wrap this in a setting and be opt-in.

**Comment by milesj** [comment]
Added an option `affectedPassInputs` for this, to avoid other issues.
