### ISSUE TITLE
[bug] `moon run ___` inside a project directory panicks

### ISSUE THREAD

**Issue by bradleyayers** [moonrepo/moon#1330]
**Describe the bug**

Trying to run a task while the cwd is a project causes the main thread to panick.

**Steps to reproduce**

Inside my project's [`projects/emails`](https://github.com/bradleyayers/haohao.how/tree/7edadded9a8385370531240bc966868292276bc4/projects/emails) I run:

```
% moon run build
Error:   × Main thread panicked.
  ├─▶ at nextgen/process/src/command_inspector.rs:180:22
  ╰─▶ called `Result::unwrap()` on an `Err` value: StripPrefixError(())
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.

zsh: abort      moon run build
```

Running `moon run emails:build` from the root of the repository works:

<img width="597" alt="image" src="https://github.com/moonrepo/moon/assets/105820/e2699bf5-cd7f-4877-864b-b1ad8f50b0cb">

But even running `emails:build` within the project doesn't work.

**Environment**

```
% moon --version
moon 1.21.2
```

**Expected behavior**

I expected it would run the `build` task in the project.

**Comment by affanshahid** [comment]
Which version are you running? I believe this was fixed in a recent release

**Comment by milesj** [comment]
Yeah try 1.21.3, should be fixed

**Comment by bradleyayers** [comment]
Ah yes it works in 1.21.3, thanks!
