### ISSUE TITLE
[bug] Moon docker prune command using bun install also the dev dependencies

### ISSUE THREAD

**Issue by esciullo** [moonrepo/moon#1343]
**Describe the bug**

The `moon docker prune` command usign bun ([prune_bun](https://github.com/moonrepo/moon/blob/master/crates/cli/src/commands/docker/prune.rs#L23)), after deleted the `node_modules` folder, install also the devDependencies due to the [install_focused_dependencies](https://github.com/moonrepo/moon/blob/master/crates/bun/tool/src/bun_tool.rs#L233) have commented the code to use the `--production` option.

**Steps to reproduce**

1. Run the `moon docker scaffold` command
2. Use Dockerfile to build the Docker image:
```
# use the official Bun image, see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 
WORKDIR /app

# Install moon binary and git, moon docker setup needs git
RUN apt-get update 
RUN apt-get install -y curl
RUN curl -LJO https://moonrepo.dev/install/moon.sh 
RUN chmod +x moon.sh
RUN ./moon.sh
ENV PATH="/root/.moon/bin:$PATH"
RUN apt-get install -y git

# Copy workspace skeleton
COPY ./.moon/docker/workspace .

# Install toolchain and dependencies
RUN moon docker setup

# Copy source files
COPY ./.moon/docker/sources .

# Prune workspace
RUN moon docker prune
```

**Expected behavior**

The `moon docker prune` command using bun installs only the necessary prod dependencies.

**Comment by milesj** [comment]
We actually had the `--production` flag but it didn't work correctly: https://github.com/moonrepo/moon/blob/master/crates/bun/tool/src/bun_tool.rs#L232

Let me dig into bun issues and see if it's still a problem.

**Comment by milesj** [comment]
This looks to still be an issue:
- https://github.com/oven-sh/bun/issues/7969
- https://github.com/oven-sh/bun/issues/7842

The problem before when I first implemented it, is that it still installs dev deps.

**Comment by esciullo** [comment]
Thanks @milesj. 
I think that from moon's point of view, it's correct anyway to use the `--production` option. What do you think ?

Furthermore in my case, using `RUN moon docker prune` the size of `/app/node_modules/` is 756M,
while using the below, the size of `/app/node_modules/` is 647M.
```
#Simulate prune
RUN rm -rf /app/node_modules 
RUN bun install --production
```

**Comment by milesj** [comment]
Added back in 1.22
