### ISSUE TITLE
[feature] Support Defining Common Tasks for different stack types

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1363]
**Describe the solution you'd like**

The `stack` feature introduced in moon v1.22.3 is amazing! Together with allowing relationships between backend and frontend the feature makes it easier to maintain projects in a monorepo.

Now what is missing, is the ability to have specific task files in `.moon/tasks/` folder that can define common tasks for the stack types.

So the feature is to support defining tasks through the following files:

- .moon/tasks/stack-frontend.yml
- .moon/tasks/stack-backend.yml
- .moon/tasks/stack-infrastructure.yml
- .moon/tasks/stack-systems.yml

**Describe alternatives you've considered**

Today we can only use tags for achieving this.

**Comment by milesj** [comment]
Will be in 1.23 https://github.com/moonrepo/moon/pull/1378

**Comment by milesj** [comment]
Landed in v1.23!
