### ISSUE TITLE
[bug] vscode extension: element with id is already registered in the tags panel

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1364]
**Describe the bug**

If you have packages sharing two different tags:

- package-a
  - #a
  - #b
- package-b
  - #a
  - #b
  - #c

If you expand tag #a in the extension it opens well and shows package-a and package-b. If you expand tag #c, you see package-b. If you expand tag #b, you get an error.

**Comment by milesj** [comment]
This is fixed in extension v0.12.
