### ISSUE TITLE
[feature] Global, Project-less, Tasks

### ISSUE THREAD

**Issue by rawkode** [moonrepo/moon#1368]
**Is your feature request related to a problem? Please describe.**

I've added a global task to the `tasks.yml` file within my workspace root inside `.moon`.

I figured this would allow me to use `moon run global-task` anywhere in my workspace root, but it seems that these only work via inheritence and within a project directory.

The global command I added was to scaffold a new project.

**Describe the solution you'd like**

The ability to run global tasks outside of a project

**Comment by milesj** [comment]
@rawkode You can use a root-level project for these use cases https://moonrepo.dev/docs/guides/root-project

**Comment by rawkode** [comment]
Perfect. Thanks for the assist.
