### ISSUE TITLE
[bug] moon clean fails to clean

### ISSUE THREAD

**Issue by rcrowe** [moonrepo/moon#1405]
**Describe the bug**

I'm not sure if I've completely misunderstood how `moon clean` is supposed to work or not, but it's not cleaning up cache files I'd expect it to do so.

- Old states for removed tasks remain 
- Old hashes remain

I'd expect hashes, as computed by inputs that are no longer valid would be cleaned up & the same for tasks that have since been removed.

**Steps to reproduce**

Focusing on `.moon/cache/states` for now, but the same occurs for `.moon/cache/hashes`. I'm not currently using outputs, so haven't tested that.

1. Add the following to `moon.yml`

```yml
tasks:
  hello:
    command: echo "Hello, World!"
```

2. Run the command `moon run :hello`
3. Run again to show it's cached

4. Check `hello` exists in the states cache

```shell
rg hello .moon/cache/states/ -il | wc -l
```

5. Delete the hello task

6. Run `moon clean --lifetime '1s', waiting & re-running to double check it's been 1 second.

```shell
Deleted 0 files and saved 0 bytes
```

7. Check that everything has been cleaned up (it hasn't)

```shell
rg hello .moon/cache/states/ -il | wc -l
```

**Expected behavior**

No reference to the hello task is found, as old cache files have been cleaned up

```shell
rg hello .moon/cache/states/ -il | wc -l
```

**Screenshots**

**Environment**

```shell
$ moon -V
moon 1.23.0
```

**Comment by milesj** [comment]
Fixed in 1.23.1
