### ISSUE TITLE
[feature] Generic "Tooling Provider" Integration

### ISSUE THREAD

**Issue by castarco** [moonrepo/moon#1411]
### Context: my use case

I usually rely on [`fnm`](https://github.com/Schniz/fnm) to pin my NodeJS version, in part because it can read different "version files" (`.node-version`, and `.nvmrc`), and in part because it provides very nice shell integrations, so, when I enter into a directory that has one of those files, it automatically loads the correct NodeJS version into my `$PATH`.

Continuing with my case for `fnm`, it also provides `corepack` (which is expected to be a "standard" tool in the NodeJS ecosystem at some point), which is enough to pin the package manager and its version once its own `node` is already in scope.

Besides that, sometimes I also rely on other tools such as Meta's [DotSlash](https://dotslash-cli.com/) ("similar" to `direnv`, although it works in a different way) to define the tools available in my working environment.

### My problem

`moon` complains when it finds tools that are not "controlled" by it or its sibling `proto` (even when the reported versions provide an exact match).

Example:
```
 WARN  Unsupported engine: wanted: {"node":"== 20.12.0"} (current: {"node":"v20.12.0","pnpm":"8.15.6"})
```

And I don't want to give up very good tools such as `fnm` or `dotslash`, and I suspect this is the same for `direnv` or `asdf` fanboys.

## Describe the solution you'd like:

I'd like moon to detect the version of the tool that is being executed and to be "more accepting" if it finds that it matches the version specified in its configuration.

Because we are talking about "well known" tools, it is always possible to run a specific "query command" on them to verify their version, such as `node --version`.

I suspect that this might involve some extra runtime checks that wouldn't be necessary if the tool already comes from `proto`, but `moon` could take advantage of other metadata already present in the repository and cache it as necessary. This metadata I'm referring to are files such as:
- `.node-version`
- `.nvmrc`
- And other typical files used by "tooling providers" such as `direnv` or `asdf`.

## Describe alternatives you've considered

1. Not telling `moon` anything about the tools I'm using, so it won't complain... but I suspect that is not a good idea, because then I'll probably loose the potential benefits of certain integrations.

2. Relying on `proto` for the tools of my monorepo... but I... don't like it at all. I'm sorry, it's surely a nice tool, but it's not as nice as `moon`, and not as nice as other tools already mentioned in this same issue either.
   
   Besides that, I explicitly dislike that it is "forced" on me when I use `moon`. I prefer a more modular and flexible approach (which is why I prefer `moon` over `turbo`, because it doesn't force my to work with JS/TS tooling, and it supports other technologies as well).

## Additional context

Similar feature requests:
- https://github.com/moonrepo/moon/issues/1366

**Comment by milesj** [comment]
I'm a bit confused about this, can you clarify further?

> moon complains when it finds tools that are not "controlled" by it or its sibling proto (even when the reported versions provide an exact match).

moon doesn't do this at all. moon will just run any command that's on `PATH`. proto can do this, but if you're pinning the version of the tool in the toolchain, then this shouldn't happen.

>  WARN  Unsupported engine: wanted: {"node":"== 20.12.0"} (current: {"node":"v20.12.0","pnpm":"8.15.6"})

This isn't moon or proto, I'm pretty sure this is just pnpm.

> Relying on proto for the tools of my monorepo... but I... don't like it at all. I'm sorry, it's surely a nice tool, but it's not as nice as moon, and not as nice as other tools already mentioned in this same issue either.

You don't have to use proto. Just remove the `version` fields from `.moon/toolchain.yml`: https://moonrepo.dev/docs/guides/javascript/node-handbook#utilizing-the-toolchain

**Comment by castarco** [comment]
Ouch 🤦🏻‍♂️ . I really misunderstood a ton of things here. I'm sorry for making you lose time.
