### ISSUE TITLE
[bug] `moon` overwrites files in git's `core.hooksPath`

### ISSUE THREAD

**Issue by matthewhughes-uw** [moonrepo/moon#1449]
**Describe the bug**

`moon` overwrites files it doesn't own outside the repo it is running in when the `core.hooksPath` configuration option is set. This can cause issues as other Git repos may be using these hooks and these will now unexpectedly error when trying to run (also it feels a bit unnerving that `moon` modifies files it doesn't out outside the working directory)

As an aside, another place I've seen this is`pre-commit`, which works around this by simply not working when this setting is set https://github.com/pre-commit/pre-commit/issues/1198 (which still allows for some unsanctioned work-arounds like https://github.com/matthewhughes934/dotfiles/commit/906179ebc1d7a4f0b5f6fd39769d046c6454bdc7)

**Steps to reproduce**

```bash
# our own hooks, outside of the moon repo
mkdir /tmp/my-hooks
cat <<'EOF' >/tmp/my_hooks/pre-commit
#!/bin/sh
 
echo 'my hook says hello'
EOF
chmod 755 /tmp/my_hooks/pre-commit
# setup basic moon repo
moon init --yes
cat <<'EOF' >> .moon/workspace.yml
vcs:
  manager: 'git'
  syncHooks: true
  hooks:
    pre-commit:
      - 'echo "moon says hi!"'
EOF
mkdir -p ./apps/my-app
cat <<'EOF' > ./apps/my-app/moon.yml
tasks:
  run:
    command: echo 'running'
EOF
moon setup
git init
git add .
git commit --message 'Add moon'

# run a command with `core.hooksPath` set
GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.hooksPath GIT_CONFIG_VALUE_0=/tmp/my_hooks/ moon run my-app:run

# our hook file has been modified
cat /tmp/my_hooks/pre-commit 
```

**Expected behavior**

`moon` doesn't modify files it doesn't own outside of the repo it is running in

**Screenshots**

**Environment**

**Additional context**

**Comment by milesj** [comment]
Thanks have a potential fix here https://github.com/moonrepo/moon/pull/1450
