### ISSUE TITLE
[bug] Regression on 1.24.3 on CI environment

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1457]
**Describe the bug**

I have a big graph when running `moon ag :deploy`. I can post it as a comment if you want.

In moon 1.24.2 when i run `moon run :deploy` in CI (Github) it works fine. 

Now in 1.24.3, no task is being run. Error is:

```
No tasks found for target(s) :deploy
```

Locally in 1.24.3 `moon run :deploy` runs fine.

**Comment by milesj** [comment]
@rhuanbarreto I'm assuming these `deploy` tasks have `runInCI: false` enabled? Let me look into it.

**Comment by rhuanbarreto** [comment]
All of them have `local: true`

**Comment by milesj** [comment]
@rhuanbarreto Can you try 1.24.4

**Comment by rhuanbarreto** [comment]
Fixed! But we still have problems with proto. Will open a separate issue.
