### ISSUE TITLE
[bug] `moon ci` fails if bun is recently updated

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1486]
**Describe the bug**

Whenever bun get's released (normally every friday. specially this weekend there were 2 releases), `moon ci` command fails. This happens because in my toolchain file I use the latest version of bun:

```
bun:
  syncProjectWorkspaceDependencies: true
  version: latest
```

Error message is: 

```
▪▪▪▪ bun install
  bun install (in workspace)
  Error: proto::version::undetected
    × Failed to detect an applicable version to run Bun with. Try pinning a
    │ version or passing the version as an argument.
    help: Has the tool been installed?
  [ERROR 2024-06-01 19:44:35.491] log:ci  Encountered a critical error, aborting the action pipeline  log.target="moon_action_pipeline::pipeline" log.module_path="moon_action_pipeline::pipeline" log.file="legacy/core/action-pipeline/src/pipeline.rs" log.line=398
  Error: process::failed
```

Then I need to pin the version in order to have it working or wait some time and then it works.

**Comment by milesj** [comment]
Are you using the setup-toolchain github action?

**Comment by rhuanbarreto** [comment]
Yes

**Comment by milesj** [comment]
Has this been happening on multiple moon versions, or recently started?

**Comment by rhuanbarreto** [comment]
Looks like caching the .moon/cache folder is generating issues. When I run uncached, it works.

**Comment by milesj** [comment]
@rhuanbarreto Ah yeah, `.moon/cache/states` is not portable. Ideally you shouldn't cache any of this.

**Comment by rhuanbarreto** [comment]
Yes. but even when not caching the .moon/cache folder I was getting errors. Now disabling cache on the setup toolchain action did the trick for me.

**Comment by milesj** [comment]
I'll try to recreate but I'm not 100% sure where the actual issue is. There's a ton of layers involved here.

**Comment by milesj** [comment]
Yeah anything would help.

**Comment by milesj** [comment]
I've done some initial testing but have been unable to figure out anything wrong.

If possible, if you could capture the log output with `PROTO_LOG=debug MOON_DEBUG_PROCESS_ENV=1`, it will help uncover what variables are being set for these commands (like `bun install`), and what proto tries to use.

**Comment by rhuanbarreto** [comment]
@milesj sent the logs to your discord.

**Comment by rhuanbarreto** [comment]
@milesj now after the upgrade to bun v1.1.13 I got an error:
```
▪▪▪▪ installing bun latest
▪▪▪▪ installing bun latest
[ERROR 2024-06-12 09:30:24.691] log:run  Encountered a critical error, aborting the action pipeline  log.target="moon_action_pipeline::pipeline" log.module_path="moon_action_pipeline::pipeline" log.file="legacy/core/action-pipeline/src/pipeline.rs" log.line=398
Error: fs::read

  × Failed to read path ~/.proto/temp/bun/1.1.13/SHASUMS256.txt.
  ╰─▶ No such file or directory (os error 2)
```

**Comment by rhuanbarreto** [comment]
Also bun is trying to be installed twice.

The weirdest is that this is not possible to reproduce. If I add `--log debug` to the `moon ci` command problem is solved.

**Comment by milesj** [comment]
Ok that's weird, let me dig into it again.

**Comment by milesj** [comment]
I think this will fix it https://github.com/moonrepo/moon/pull/1502

**Comment by rhuanbarreto** [comment]
In our environment in github it works but in azure dev ops it's still hanging. Sent you the logs in discord.
