### ISSUE TITLE
[bug] Unexpected character '.' after patch version number

### ISSUE THREAD

**Issue by kikones34** [moonrepo/moon#1490]
**Describe the bug**

moon seems unable to parse the following git version:
```
git version 1.8.3.1
```

When trying to run any task, it fails with the following error:
```
Error:   × unexpected character '.' after patch version number
```

Related to https://github.com/moonrepo/moon/issues/945 and https://github.com/moonrepo/moon/issues/1281.

**Steps to reproduce**

Try to run any task.

**Expected behavior**

The task is run.

**Environment**

I'm running moon on a remote system and I cannot install Node.js on it to execute `npx envinfo`. If any additional information is required please tell me and I'll try to fetch it.

```
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

uname -a
Linux na01lclsst10 3.10.0-1160.118.1.el7.x86_64 #1 SMP Wed Apr 24 16:01:50 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by milesj** [comment]
@kikones34 I can attempt to fix it, but that git version is also super old. Are you able to upgrade it?

**Comment by kikones34** [comment]
> @kikones34 I can attempt to fix it, but that git version is also super old. Are you able to upgrade it?

I am sadly unable to upgrade it at the moment.

**Comment by milesj** [comment]
@kikones34 Just curious, do you know if moon works on that version? I know we use git commands that require 1.22 at minimum.

**Comment by kikones34** [comment]
> @kikones34 Just curious, do you know if moon works on that version? I know we use git commands that require 1.22 at minimum.

I'm unsure how to test if it would work 🤔. Also, did you mean 2.22? 1.22 doesn't seem to exist.
In any case, I have pushed to get the git version upgraded and it looks it may be happening. I completely understand if you don't want to deal with supporting such an ancient version, although perhaps the version parsing could be fixed to get and error like "unsupported git version", it took me a while to figure out that was the issue.

**Comment by kikones34** [comment]
@milesj fyi, I tried the new moon version with the ancient git and it actually works 🎉

**Comment by milesj** [comment]
That's actually surprising :p
