### ISSUE TITLE
[feature] Support `bun install --frozen-lockfile` in moon commands

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1531]
Normally when we run `moon ci` it implies that the lockfile is up to date.

Having a way to configure moon to run the sync deps tasks with the `--frozen-lockfile` flag would speed up a lot of CI time.

**Comment by milesj** [comment]
You can set this manually using this setting: https://github.com/moonrepo/moon/blob/master/crates/config/src/toolchain/bun_config.rs#L18

**Comment by rhuanbarreto** [comment]
Great! Thanks a lot!
