### ISSUE TITLE
[bug] `./` (dot-slash) prefix in `projects` does not work

### ISSUE THREAD

**Issue by latin-1** [moonrepo/moon#1532]
**Describe the bug**

`.moon/workspace.yml`:

```yaml
projects:
  - ./packages/*
```

**Steps to reproduce**

**Expected behavior**

Workspaces in `packages` folder should be recognized.

**Screenshots**

**Environment**

```
moon: 1.26.4
```

**Additional context**

**Comment by milesj** [comment]
This is weird. I think our globbing lib is treating it as literals, digging in.
