### ISSUE TITLE
[feature] Add an option to avoid touching the `packageManager` field in `package.json`

### ISSUE THREAD

**Issue by latin-1** [moonrepo/moon#1533]
Similar to the `node.syncVersionManagerConfig: none` config, but for the package manager.

**Comment by milesj** [comment]
@latin-1 What's the reasoning? This ensures other tools that rely on that field are also using the same version that the repo expects.

**Comment by latin-1** [comment]
@milesj I'd like to use `packageManager` as the single source of truth (use proto, corepack, or whatever to install the specified yarn version), but I also want to use `inferTasksFromScripts`. However, this is not currently possible.

To use `inferTasksFromScripts`, we must specify the `packageManager: yarn`; otherwise, moon will use `npm` to install packages, which does not work.

If I specify only `packageManager` but not `version`, moon will remove the `packageManager` field from the `package.json`. I'm not sure if it's a bug.

This isn't the only reason I want this option to be added. Although `packageManager` is commonly used, it is not a standard field; it is simply a custom field used by corepack. Developers may want to use something else, for example, `.prototools` or `volta.*`.

**Comment by milesj** [comment]
Will be in 1.27
