### ISSUE TITLE
[feature] Allow opting out of the `yarnPath` for the yarn package manager

### ISSUE THREAD

**Issue by latin-1** [moonrepo/moon#1534]
**Is your feature request related to a problem? Please describe.**

If our project's package manager version is managed by proto, the `yarnPath` config is completely useless.

In yarn 4.0, if corepack is enabled globally, `yarn set version` will not attempt to insert the `yarnPath` field into `.yarnrc.yml`. I believe we should do the same thing with proto managed yarn.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by milesj** [comment]
@latin-1 I'm not sure if we can handle this on our end? We don't explicitly set that `yarnPath` field. We just call `yarn` commands that in turn do it.

**Comment by latin-1** [comment]
@milesj I'm not sure why moon does not use proto to manage yarn versions.

For yarn 4, `yarn set version` will generate `yarnPath` if 1. `corepack` is not global enabled, or 2. `--no-yarn-path` is specified. Yarn 2/3 will always write it.

Using `yarn set verion` programmingly might not be a good idea IMHO.

**Comment by milesj** [comment]
yarn is managed by proto via moon, but the `yarn set version` stuff predates it. Probably best to just remove it at this point.

**Comment by milesj** [comment]
Will be in 1.27
