### ISSUE TITLE
[bug] Unable to download toolchain when behind a VPN/corporate proxy

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [moonrepo/moon#154]
**Describe the bug**

```
$ moon --log debug setup
...
[debug 12:03:15] moon:toolchain:node Tool has not been downloaded, attempting

 ERROR  Internet connection required, unable to download and install tools.
```

**Steps to reproduce**

1. git init
2. moon init
3. moon --log debug setup

**Expected behavior**

Resource should be able to be downloaded

**Environment**

```
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
    Memory: 24.10 GB / 32.00 GB
  Binaries:
    Node: 16.15.0
    Yarn: 1.22.19
    npm: 8.12.0
  Managers:
    Cargo: 1.61.0
  Utilities:
    Git: 2.36.1.
  IDEs:
    VSCode: 1.67.1
  Languages:
    Rust: 1.61.0
```

**Additional context**

I suspect a corporate proxy problem, is there a switch around self signed certs comparable to NODE_TLS_REJECT_UNAUTHORIZED?

**Comment by milesj** [comment]
@sschneider-ihre-pvs Are you on a VPN?

For the offline check, I ping Cloudflare's DNS (1.1.1.1). Is this not accessible for you?

**Comment by sschneider-ihre-pvs** [comment]
I can ping the dns
moon 0.3.1

**Comment by sschneider-ihre-pvs** [comment]
sadly there is no trace information on why download wasn't possible. A http code would be handy.
```
❯ moon --log trace setup
[trace 2022-06-21 08:06:55] moon:workspace Attempting to find workspace root at ~\code\learn\moonrepo\hello_world
[debug 08:06:55] moon:workspace Creating workspace at ~\code\learn\moonrepo\hello_world (from working directory ~\code\learn\moonrepo\hello_world)
[trace 08:06:55] moon:workspace Loading .moon/workspace.yml from ~\code\learn\moonrepo\hello_world
[trace 08:06:55] moon:workspace Attempting to find .moon/project.yml in ~\code\learn\moonrepo\hello_world
[trace 08:06:55] moon:workspace Loading package.json from ~\code\learn\moonrepo\hello_world
[trace 08:06:55] moon:workspace Attempting to find tsconfig.json in ~\code\learn\moonrepo\hello_world
[debug 08:06:55] moon:cache Creating cache engine at ~\code\learn\moonrepo\hello_world\.moon\cache
[debug 08:06:55] moon:toolchain Creating toolchain at ~\.moon
[trace 08:06:55] moon:toolchain Creating directory ~\.moon
[trace 08:06:55] moon:toolchain Creating directory ~\.moon\temp
[trace 08:06:55] moon:toolchain Creating directory ~\.moon\tools
[debug 08:06:55] moon:project-graph Creating project graph with 1 projects
[debug 08:06:55] moon:toolchain Downloading and installing tools
[debug 08:06:55] moon:toolchain:node Tool has not been downloaded, attempting

 ERROR  Internet connection required, unable to download and install tools.
```

**Comment by milesj** [comment]
@sschneider-ihre-pvs Thanks for the info. I'll disable it for now for v0.4 release since it's hard to debug as-is.

**Comment by milesj** [comment]
Released v0.4 that disables this check if you'd like to try again.

**Comment by sschneider-ihre-pvs** [comment]
![132](https://user-images.githubusercontent.com/86342787/175234813-899b9ccd-b502-4f2f-ad39-5c3e3b6954b8.png)

**Comment by milesj** [comment]
@sschneider-ihre-pvs Ah windows, what terminal are you using?

**Comment by sschneider-ihre-pvs** [comment]
that is windows-terminal running powershell, the extra window, I don't really know but I suspect something like git-bash maybe??

**Comment by milesj** [comment]
For node/npm commands to work, we must run them through `cmd.exe`. I have a feeling this is causing the other terminal to open up, but I never actually encountered this myself when testing windows. I'll try and dig further, maybe it's a setting somewhere.

**Comment by milesj** [comment]
I tested this on windows terminal + powershell mode without issue.

**Comment by milesj** [comment]
@sschneider-ihre-pvs Can you try v0.6? Landed some more windows improvements.

**Comment by sschneider-ihre-pvs** [comment]
Works
