### ISSUE TITLE
[bug] Using `MOON_OUTPUT_STYLE=buffer-only-failure` still outputs cached steps

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1548]
**Describe the bug**

If I run tasks with `MOON_OUTPUT_STYLE=buffer-only-failure` set, cached steps still gets output.

**Steps to reproduce**

1. Run `MOON_OUTPUT_STYLE=buffer-only-failure moon ci` with cached tasks
2. You will see the output for the cached tasks

**Expected behavior**

Expected to not see the output

**Comment by milesj** [comment]
I briefly looked into this, and it looks like the project graph cache is the problem. I'll have to figure out a work around.

**Comment by milesj** [comment]
Fixed in 1.26.7
