### ISSUE TITLE
[bug] Output messages are being buffered aggressively

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1549]
**Describe the bug**

I started noticing that in any moon command, the output messages are being aggressively buffered. With chunks arriving every 4-10s. I'm not sure in which version this appeared.

I'm opening an issue here only for tracking but I already sent logs to @milesj in Discord.

**Comment by milesj** [comment]
Can you try 1.26.7? Made a few changes and added some logging to see if we can catch this.

**Comment by rhuanbarreto** [comment]
Tried and it works!
