### ISSUE TITLE
[feature] Project custom key value metadata

### ISSUE THREAD

**Issue by doron-cohen** [moonrepo/moon#1571]
**Is your feature request related to a problem? Please describe.**

Hey, I was trying to add some metadata to a project's moon.yaml file but moon didn't like it.

**Describe the solution you'd like**

I would like to add custom metadata to projects. Tags are fine but it doesn't allow me to store key value data easily. Some examples for custom metadata could be the service subsystem, phase (experimental, production or deprecated) and other information.

I would also like `moon query projects --json` to return this information and that I could also use it in templates (maybe with `@metadata(key)`?).

For example, I would like to generate a file for a 3rd party tool which creates dev environments. If I could add custom metadata I could write a script which reads it from all service projects and generates that file instead of maintaining it manually.

**Describe alternatives you've considered**

Adding a separate yaml file could work but moon has a great querying tool which I would like to use for that. Also making it available in template would ease some things I would like to acheive.

**Additional context**

**Comment by milesj** [comment]
Sounds good, I could easily patch this in a few lines. I'll get it in the next release!

**Comment by artsiommiksiuk** [comment]
I'd like to extend this proposal with concept of monorepo tool must have some properties of the database (key value store should be quite enough) on workspace level and project level (which @doron-cohen basically proposed). Such key-value store on those two levels (generalized and individual) basically can eliminate the need in variables (which are planned, but idk really what they gonna be). 

In this case whole monorepo can host all required information for all the commands inside. If it is possible to have ```@metadata(key)``` and ```@workspaceMetadata(key)```, then we basically can use them everywhere for further templating in the commands (which is usually the main purpose).

@milesj Does it make sense? How hard would it be to implement this concept if it makes sense?

**Comment by milesj** [comment]
@artsiommiksiuk As mentioned [here](https://github.com/moonrepo/moon/issues/1569#issuecomment-2243258885), env vars _should_ give you want you're looking for.

**Comment by milesj** [comment]
Added the fields in 1.27.3, I'll look into a token for it in the next big release

**Comment by doron-cohen** [comment]
Cool. Is there any documentation about it?

**Comment by milesj** [comment]
https://moonrepo.dev/docs/config/project#metadata-1

**Comment by dudicoco** [comment]
Thank you for adding this @milesj.
Can we query the metadata?

**Comment by milesj** [comment]
@dudicoco Query in what sense?

**Comment by dudicoco** [comment]
@milesj we can query tags per https://moonrepo.dev/docs/concepts/query-lang#tag.
So I would expect to be able to query metadata as well.

**Comment by milesj** [comment]
Query fields must be static, and since metadata is dynamic, I don't think it will be possible.

**Comment by dudicoco** [comment]
> Query fields must be static, and since metadata is dynamic, I don't think it will be possible.

What is dynamic about metadata? How does it differ from a map of tags with key value?

**Comment by milesj** [comment]
There's 2 kinds of metadata, the moon fields like description, channel, etc: https://moonrepo.dev/docs/config/project#project And then the `metadata` field that allows consumers to add whatever they want: https://moonrepo.dev/docs/config/project#metadata-1

The former can be added to queries easily, as we can do stuff like `projectChannel=?`. The dynamic fields not so much, as all of the available fields use Rust enums, which are statically compiled. https://github.com/moonrepo/moon/blob/master/crates/query/src/builder.rs#L14

**Comment by dudicoco** [comment]
Ohh so is it because the new metadata field can accept json as values, which could mean maps/arrays?
I thought it's a simple string based key value, makes sense that querying the json values would be harder.

**Comment by milesj** [comment]
Added a `@meta` token in 1.28.
