### ISSUE TITLE
[bug] typescript (and not only) output losses cli colors

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1574]
**Describe the bug**

I'm not using yet node toolchain - different reasons. Instead I have to call custom build pipeline in moon, and the end command is of course (in moon): ```npx tsc --project tsconfig.build.json```

![image](https://github.com/user-attachments/assets/809fd4e4-97b1-4ab3-a2c0-4f0a127e590d)

I also seeing this behaviour with mikro-orm logs. But e.g. running ```redoc``` partially keeps colors, so I'm assuming there's something wrong with the output reprinting and escaping.

**Steps to reproduce**

1. Have a tsc which errors. E.g.

```typescript
function add(a: number, b: number) {
   return a + b;
}

console.log(add(1, "23"))
```

2. Add moon build task:
```yaml
tasks:
  build: 
    script: npx tsc
```

**Expected behavior**

Running color emitting commands still keeps colors. 

![image](https://github.com/user-attachments/assets/db2b99f3-a529-4cca-8c4f-f1fb87e6da34)

**Environment**

```
  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 259.23 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.6 - /opt/homebrew/bin/pnpm
  Managers:
    Homebrew: 4.3.10 - /opt/homebrew/bin/brew
    pip3: 24.0 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Bazel: 7.1.2 - /opt/homebrew/bin/bazel
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
    OpenSSL: 3.3.1 - /opt/homebrew/bin/openssl
  Servers:
    Apache: 2.4.58 - /usr/sbin/apachectl
  Virtualization:
    Docker: 25.0.4 - /opt/homebrew/bin/docker
    Docker Compose: 2.24.6 - /usr/local/bin/docker-compose
  IDEs:
    VSCode: 1.91.1 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.34.1 - /usr/bin/perl
    Python3: 3.12.4 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    PostgreSQL: 14.11 - /opt/homebrew/bin/postgres
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.4.1

```

**Comment by artsiommiksiuk** [comment]
Hm. Seems like it's typescript itself who detects the it being run as part of some scripting and disabling colors. Adding ```--pretty``` flag for tsc returns colors back.

In this case I'd propose two things:
1. Document this in troubleshooting, that programs may loos colors. Obvious, but easy to forget about it.
2. Have an option in moon to make spawned subprocesses behave as "root", so running commands also thing they are top level launches and will keep color output.

**Comment by milesj** [comment]
This is just how all programs and child processes work, this isn't a moon specific issue. We have this setting, but it doesn't work in all cases. https://moonrepo.dev/docs/commands/overview#piped-output

**Comment by artsiommiksiuk** [comment]
Well, what's interesting is if I run the same ```npx tsc``` wrapped into ```just``` - colors preserves. How is this working then?

**Comment by milesj** [comment]
My guess is Just is using a PTY, which moon does not.

Child processes are not considered a TTY, so they are probably emulating it somehow.
