### ISSUE TITLE
[feature] moon query tasks shall have a description printed for each task

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1578]
**Is your feature request related to a problem? Please describe.**

```
➜  backend git:(moon-monorepo) ✗ moon query tasks       
be
        :build | noop
        :build-orm | npx
        :build-ts | npx
```

**Describe the solution you'd like**

```
➜  backend git:(moon-monorepo) ✗ moon query tasks       
be
        :build | noop                                 global build
        :build-orm | npx                              build something orm related files
        :build-ts | npx                               build something typescript related files
```

Names of a task might not always be that descriptive, having descriptions would be nice and can be used to better overview what are the commands available.

**Describe alternatives you've considered**

None.

**Comment by milesj** [comment]
`moon query` tasks were meant more for scripts/automation/etc. If you want more readable information, you probably want `moon project` instead.

**Comment by artsiommiksiuk** [comment]
```moon project``` requires to specify target.
There's no place currently which gives overview of projects and commands, except exactly ```moon query tasks```.

**Comment by milesj** [comment]
Is listing _all_ tasks even useful? In a large monorepo, it's nothing but noise.

**Comment by artsiommiksiuk** [comment]
Well, I'd like to have some starting point embedded into the tool. Maybe you right about that it'll be mostly noise in large monorepo, but I believe in small/mid sized projects it might be beneficial.

I think also that even in large monorepo I'd might be using grep over this output to lookup tasks with certain description words.

**Comment by milesj** [comment]
Added in v1.29.
