### ISSUE TITLE
[feature] Partial / filtered inheritance

### ISSUE THREAD

**Issue by doron-cohen** [moonrepo/moon#1581]
**Is your feature request related to a problem? Please describe.**

When defining a global task it is inherited by all projects in the workspace. In our monorepo we have multiple tech stacks projects but all need some basic `build`, `test` and `lint` tasks.

Problem is, when we create a global `test` task it could only define the test for one tech stack. So if I write a command which runs `go test` not only that I can't use it for my TS projects, it will also fail when running `moon :test`.

**Describe the solution you'd like**

I am not sure what will be the best approach but I want to suggest to use MQL to define the projects which should inherit the task:
```
tasks:
  test(language=typescript):
    ...

  test(language=go):
    ...
```

Anyway we should also add some way to visualize this in `moon query tasks` to allow devs to understand which projects inherit which tasks.

**Describe alternatives you've considered**

What I can do now is define `go:test` and `ts:test` and extend the appropriate one in the project's `test` task.

**Comment by artsiommiksiuk** [comment]
I'd link these two issues here, because they are talking about the same concept: 

https://github.com/moonrepo/moon/issues/1580 (at the end of a description)
https://github.com/moonrepo/moon/issues/1538

**Comment by doron-cohen** [comment]
Thanks @artsiommiksiuk this is interesting. I think we should maybe convert these issues to a discussion if that's acceptable by the maintainers.
Adding to what you wrote in #1580, I would love tasks to have a CI mode.

**Comment by artsiommiksiuk** [comment]
> Thanks @artsiommiksiuk this is interesting. I think we should maybe convert these issues to a discussion if that's acceptable by the maintainers. Adding to what you wrote in #1580, I would love tasks to have a CI mode.

Well, there's ```options.runInCi: bool```, but it basically should prevent tasks from running locally if set. Still, it doesn't filter things depending on local/ci/somewhere running.

**Comment by milesj** [comment]
@doron-cohen You can organize your global tasks into scoped files: https://moonrepo.dev/docs/concepts/task-inheritance#scope-by-project-metadata

**Comment by doron-cohen** [comment]
Amazing. Thanks
