### ISSUE TITLE
[bug] Internal tasks can be run with `moon run`

### ISSUE THREAD

**Issue by doron-cohen** [moonrepo/moon#1582]
**Describe the bug**

I created a task with `options.internal: true` but I can still see it in `moon query tasks` and can run it with `moon run`

**Steps to reproduce**

1. Create an internal task
2. Use `moon query tasks` and `moon run` to see and run it

**Expected behavior**

Per documentation it shouldn't be seen

**Screenshots**

<img width="561" alt="Screenshot 2024-07-23 at 13 58 07" src="https://github.com/user-attachments/assets/e40dbd80-1af3-41ec-9a16-f2add0114cfa">
<img width="364" alt="Screenshot 2024-07-23 at 13 58 28" src="https://github.com/user-attachments/assets/9820a1fa-708a-472c-bae3-b7e867d2affb">

**Environment**

```
  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 22.38 MB / 16.00 GB
    Shell: 3.6.4 - /usr/local/bin/fish
```

**Comment by milesj** [comment]
@doron-cohen Are you also saying it doesn't error when doing `moon run codegen.mockery.base`?

**Comment by doron-cohen** [comment]
No. It runs normally. I can verify it tomorrow

**Comment by milesj** [comment]
@doron-cohen I tried to recreate this with no luck. Internal tasks fail for me:

<img width="363" alt="Screenshot 2024-07-29 at 3 54 33 PM" src="https://github.com/user-attachments/assets/ea9fa85c-a2f8-43b9-a9e7-2c1116a41170">

**Comment by milesj** [comment]
1.27.5 fixes the query issue.

**Comment by doron-cohen** [comment]
Thanks @milesj

**Comment by doron-cohen** [comment]
This is now solved but now I can't run tasks which extend an internal task. I must set `internal: false`. This is understandable but not fun to work with. I think task variables will solve this issue.

**Comment by milesj** [comment]
Yah that seems fair.

I'll close this for now.
