### ISSUE TITLE
[feature] Introduce cache timeout option per task

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1583]
**Is your feature request related to a problem? Please describe.**

I have a docker build which relies on built private repo base image. For this I need to login into ECR. Login session lives for 1 hour. 

**Describe the solution you'd like**

In order to not spam ECR with login requests over and over, I'd like to configure this particular login task to have a 1 hour cache setting.

**Describe alternatives you've considered**

None.

**Comment by milesj** [comment]
Added in v1.29 https://moonrepo.dev/docs/config/project#cachelifetime
