### ISSUE TITLE
[feature] Introduce root level tasks

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1584]
**Is your feature request related to a problem? Please describe.**

I have a docker build task and to execute it locally I also created globally ```ecr-login``` task. This ```ecr-login``` task is inherited by all projects and can be referenced there. The problem is that this ```ecr-login``` task is not deduplicated properly as it's considered different task per project.

E.g.

Having two projects and tasks like that 

```
how to read: task(...dependency)
             fn(dep1, dep2)

workspace: ecr-login <-- projects inherit this

p1:build-docker(ecr-login)
p1:ecr-login
p2:build-docker(ecr-login, p1:build-docker)
p2:ecr-login
```

When running ```p2:build-docker```  ```ecr-login``` is now a separate task, because on the moment of execution it belongs to different projects.

**Describe the solution you'd like**

I want to define true monorepo global task without them being inherited.
I presume I can disable inheritance per task, but there's no way to reference global tasks (as per documentation only self or dependency anchors available for targets filtering)

**Describe alternatives you've considered**

Currently ```mutex``` option can be used to serialize them and prevent error, but tasks are still running twice, not once.

**Comment by milesj** [comment]
@artsiommiksiuk You can use the root itself as a project: https://moonrepo.dev/docs/guides/root-project

**Comment by artsiommiksiuk** [comment]
@milesj you right, that worked! Thanks.
The downside, root task inherits it's name from folder in which root task is. Would be nice to have root to be reserved, so it's not mixed with other names in the repo.

```
root:task
.:task
/:task
```

I guess any of this variants would be more consistent with the rest of the target queries.

**Comment by artsiommiksiuk** [comment]
Another issue, in docker running it now can't find this task defined as the folder into which I've copied whole repo is called differently. There definitely should be some common root anchor to prevent this.

**Comment by artsiommiksiuk** [comment]
And another consequence would be that developers on different  machines might have root folder called differently - again braking the moon. 🙂

**Comment by artsiommiksiuk** [comment]
I hacked it differently. Just moved everything from root as a separate project with only ```moon.yml``` file. Called it repo-utils and referencing it as just another normal project. Seems to be more natural approach for moon.

**Comment by milesj** [comment]
@artsiommiksiuk You can customize the root name with either of these:

- https://moonrepo.dev/docs/config/workspace#using-a-map-and-globs
- https://moonrepo.dev/docs/config/project#id

**Comment by artsiommiksiuk** [comment]
@milesj Yes, you right. This works. I overlooked completely this part of docs. Closing it as it's not relevant then.
