### ISSUE TITLE
[feature] Allow MOON_TOOLCHAIN_FORCE_GLOBALS to be configured per toolchain

### ISSUE THREAD

**Issue by minht11** [moonrepo/moon#1612]
**Is your feature request related to a problem? Please describe.**

Moon simplifies toolchain installing which is great, especially for more complex cases like rust, in CI environment however that can be slow or in case of node unreliable. MOON_TOOLCHAIN_FORCE_GLOBALS is escape hatch in case you already have installed everything, to skip extra work. But rust setup is harder, node setup is easy, but installing with moon unreliable. So I would want to install rust with moon, but use global node, best of both worlds.

**Describe the solution you'd like**

Make MOON_TOOLCHAIN_FORCE_GLOBALS configurable per toolchain, so basically everything global except rust in my case, or add option `auto` so when node version matches it uses global if it doesn't exist it downloads it.

**Comment by milesj** [comment]
You can now pass names in 1.28:

```
MOON_TOOLCHAIN_FORCE_GLOBALS=node,etc
```
