### ISSUE TITLE
[bug] moon run doesn't use cache when running inside docker

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1622]
**Describe the bug**

I have noticed recently, that if I create docker image and shell into it (bash shell) and run some build command inside, they are not cached.

While same command directly on the host uses cache normally. I see that cache folder is created in .moon dir and seems like everything should work, but it doesn't. 

Setting ```--cache read-write``` explicitly doesn't make any difference.
Docker base image - ```node:20-bookworm-slim```

**Steps to reproduce**

1. Have a buildable example in docker and host and compare.

**Expected behavior**

Cache is still used inside docker

**Screenshots**

**Environment**

```
  System:
    OS: Linux 6.6 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 unknown
    Memory: 12.62 GB / 13.64 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.16.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.1 - /usr/local/bin/npm
    pnpm: 9.7.1 - /usr/local/bin/pnpm
  Managers:
    Apt: 2.6.1 - /usr/bin/apt
    pip3: 23.0.1 - /app/.venv-apps-be/bin/pip3
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 12.2.0 - /usr/bin/gcc
    Curl: 7.88.1 - /usr/bin/curl
    OpenSSL: 3.0.13 - /usr/bin/openssl
  Languages:
    Bash: 5.2.15 - /usr/bin/bash
    Perl: 5.36.0 - /usr/bin/perl
    Python: 3.10.14 - /app/.venv-apps-be/bin/python
    Python3: 3.10.14 - /app/.venv-apps-be/bin/python3
```

**Additional context**

**Comment by milesj** [comment]
@artsiommiksiuk Caching is disabled if Git is not setup in Docker, so ensure Git is (the `.git` folder exists, etc).

**Comment by artsiommiksiuk** [comment]
@milesj sounds quite strange for me that for the cache git is required. Can we overcome this somehow? I'm sure don't need git to run few co-dependent build tasks.

**Comment by milesj** [comment]
@artsiommiksiuk Caching is entirely powered by Git's `git hash-object` and other commands, so yeah Git is required.
