### ISSUE TITLE
[bug] Project map starting with dot '.' does not work and considered as a glob pattern

### ISSUE THREAD

**Issue by sybernatus** [moonrepo/moon#1628]
**Describe the bug**

in the `.moon/workspace.yml`, if a project is defined under a hidden folder (starting with a '.'), moon returns an error.
```bash
Error: config::parse::failed

  × Failed to parse .moon/workspace.yml.
  ╰─▶   × projects: expected a list of globs, a map of projects, or both
```

**Steps to reproduce**
1. Define a moon project under a hidden folder
```yaml
projects:
  .my-project/issue: .my-project/issue
```
3. Define the project in the map project list in `.moon/workspace.yml`
4. run a moon task (for example: `moon run :test`)

**Expected behavior**
The `.moon/workspace.yml` should be parsed correctly.

**Screenshots**

**Environment**

```
Windows 10
GIT bash CLI
moon: v1.27.10
```

**Comment by milesj** [comment]
@sybernatus IDs need to start with a letter, so this should work:

```
projects:
  my-project/issue: .my-project/issue
```

**Comment by sybernatus** [comment]
Thanks @milesj  for you answer.

Yes it will work, but in a big monorepo, as the path is a way to uniquely identify a project, I use it as alias. 

If an alias cannot start with a ".", I'm not able anymore to be sure that a project created is unique.
For example, giving these 2 projects:
- my-project/issue
- .my-project/issue

My project list will both give the same alias:
```yaml
# not working
projects:
  my-project/issue: .my-project/issue
  my-project/issue: my-project/issue
```

I think about temporarily replacing the `.` with a `_` in my aliases to solve my usecase but I still think it's an issue.
The `.` is used for hidden folders in directory trees and it is frequently used in a root repository

**Comment by milesj** [comment]
Loosened this requirement in 1.28.1
