### ISSUE TITLE
[bug] If Bun lockfile is malformed, moon fails without a meaningful error message

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1642]
**Describe the bug**

For some reason, my Bun lockfile was malformed. So the command `bun bun.lockb` was failing:

```
error opening lockfile: ENOENT
```

Because of this, when running `moon ci`, moon was failing without any meaningful error message. The only thing that happened was the early output showing the rest of the task pipeline as failed. 

I realized this because I enabled debug and found the last command to run is the `bun bun.lockb` command.

**Steps to reproduce**

1. Have a malformed bun.lockb file
2. Do `moon ci`
3. Pipeline will fail

**Expected behavior**

This happens a lot in package upgrade PRs done by renovatebot or dependabot. I expected to have a more meaningful error so we could easily solve the lockfile issue.

**Comment by milesj** [comment]
I'm almost positive this error is actually from Bun itself and not moon, so moon is just displaying it's stdout/stderr.

**Comment by rhuanbarreto** [comment]
But moon is not displaying this. This would be a good lead to identify the problem on the lockfile. I could only see the command on the debug logs. 

For now I switched to yarn lock outputs to avoid issues so moon doesn't run this command. 

Actually I'm not sure why this command is being run in the first place.

**Comment by milesj** [comment]
`bun bun.lockb` returns the lockfile in YAML format so that moon can parse it to resolve versions/hashes/etc.

Let me try and bubble the error up if it isn't in some cases.

**Comment by milesj** [comment]
Try 1.28.1 and see if that works.

**Comment by rhuanbarreto** [comment]
Still didn't work. I sent you logs in DM in discord.
`bun bun.lockb` is working fine now. But same behaviour is still happening. B y running an individual task, I managed to identify one underlying error that is not appearing on trace logs.

The error is related to the parsing of the text file that bun outputs.

**Comment by milesj** [comment]
Try 1.28.2.
