### ISSUE TITLE
[feature] Support state tracking without caching

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1650]
**Is your feature request related to a problem? Please describe.**

I have a task which ensures that python .venv is setup (all packages installed). Installation of .venv is more complex process than usually as I'm building also internal packages with C++ bindings, and can install them only directly into .venv.

The resulting .venv anyway is about 1Gb size, and it's starting to lag when moon tries to save/restore cache of this size. So I have to run just a normal build pipeline for python part of an app, each step of which thankfully either quick or have own caching (like C++ builds have own).

**Describe the solution you'd like**

So, the solution should be relatively easy - do state tracking and rerun when inputs state isn't matching stored, but don't cache the results.

**Describe alternatives you've considered**

Don't see any. The one I'm using can be considered such.

**Additional context**

-

**Comment by milesj** [comment]
@artsiommiksiuk Does the .venv need to be an output and stored in the cache?

**Comment by artsiommiksiuk** [comment]
@milesj nope. Ahhh, you mean that if I'm not setting the output then moon not caching things?

**Comment by milesj** [comment]
@artsiommiksiuk So moon tasks have 2 forms of caching, run caching and output caching. Run caching is checking the inputs have changed and either running or not running (cache hit). Output caching is the archiving of task outputs into tarballs, and then unpacking them on hydration (cache hit).

If you don't _need_ the outputs to be hydrated, you can just remove the outputs, and moon will still only run when inputs change.

**Comment by artsiommiksiuk** [comment]
@milesj, got it. Works for me. Thanks!
