### ISSUE TITLE
[feature] The template files that are copied/created can be filtered. Maybe with an --include or --exclude.

### ISSUE THREAD

**Issue by hadrien-toma** [moonrepo/moon#1653]
First of all, the more I use Moon, the more I like it, thank you very much for the work done here :pray:.

**Is your feature request related to a problem? Please describe.**
This feature is linked to one of the unchecked bullet points of the issue https://github.com/moonrepo/moon/issues/310 which is today closed.

I would like to add a `README.md` in my template in order to document it, as a sibling of the `template.yml` manifest, but I don't want this file to be copied in generated templates.

**Describe the solution you'd like**
It would be interesting to have an `exclude` property accepting a list of globs in order to filter the files copied/created when templating.

**Describe alternatives you've considered**
Put the `README.md` somewhere else :sweat_smile:.

**Comment by milesj** [comment]
@hadrien-toma Sorry for not responding earlier, but would `skip` work here? https://moonrepo.dev/docs/config/template#skip

**Comment by hadrien-toma** [comment]
Now it is me saying sorry for the delay, sorry @milesj and yes thank you very much, it works well! :heart_eyes:
