### ISSUE TITLE
[feature] Implementation an Open Telemetry Sender

### ISSUE THREAD

**Issue by harlequin** [moonrepo/moon#1657]
moon already collects task/job information (start time, end time, result ) and have had the ability to send these to moonbase.

For a more "open" solution, it would be beneficial that these data can be send to an Open Telemetry Collector, like Loki or similar.

**Comment by milesj** [comment]
You could maybe use webhooks for this for the time being: https://moonrepo.dev/docs/guides/webhooks

**Comment by harlequin** [comment]
This is absolute perfekt and fits complete into my workflow.

Therefore will Close the issue
