### ISSUE TITLE
[bug] Startup issues: `tool::unknown` & `SIGSEGV`

### ISSUE THREAD

**Issue by alexbepple** [moonrepo/moon#1663]
Quite frequently (in 30% to 50% of invocations), moon does not execute properly for me.

I get two kinds of errors. Firstly,
```
❯ moon :pre-commit
fish: Job 1, 'moon :pre-commit' terminated by signal SIGSEGV (Address boundary error)
```
Secondly,
```
❯ moon :pre-commit
Error: tool::unknown

  × Node has not been configured or installed, unable to proceed.
```

## Context
Apple M1 Pro
macOS 13.1

Errors happen with moon 1.25.6, 1.26.7, 1.27.6, 1.28.3.
Errors do not _not_ happen with moon 1.22.10

The issue is quite annoying. Unfortunately, I have not been able to reliably reproduce the errors.
→ What information should I collect in order to enable you to understand what’s going on and fix this?

**Comment by milesj** [comment]
That first error seems very weird, never seen that before. As for the second, what's your toolchain config look like?

If possible, it would be helpful if you can capture the `--log trace` output for one of these failures.

**Comment by alexbepple** [comment]
## Traces

[Node-not-configured-installed.trace.log](https://github.com/user-attachments/files/17134184/Node-not-configured-installed.trace.log)
[SIGSEGV.trace.log](https://github.com/user-attachments/files/17134186/SIGSEGV.trace.log)

In the trace for "Node has not been configured or installed, unable to proceed.", there is an explicit failure of something. Looking around (without any real understanding of what’s going on), I found it suspicious that there are two attempts to lock `~/.proto/tools/yarn/manifest.json`.


## Toolchain config 
It’s pretty straightforward, I think.

`.moon/toolchain.yml`:
```yaml
node:
  packageManager: 'yarn'
  yarn:
    version: '4.3.1'
```

And the Node version is specified for individual projects. `…/moon.yml`:
```yaml
toolchain:
  node:
    version: 20.14.0

…
```

**Comment by alexbepple** [comment]
I narrowed down the version that introduced this behavior: 1.25.0.
1.24.6 is still fine, but 1.25.0 exhibits this undesirable behavior.

1.25.0 also outputs this:
```
[ERROR 2024-09-25 18:11:48.967] log:run  Encountered a critical error, aborting the action pipeline  log.target="moon_action_pipeline::pipeline" log.module_path="moon_action_pipeline::pipeline" log.file="legacy/core/action-pipeline/src/pipeline.rs" log.line=398
```

Maybe it’s helpful.

I also generated the trace for 1.25.0: 
[moon.1.25.0.Node-not-configured-installed.trace.log](https://github.com/user-attachments/files/17134725/moon.1.25.0.Node-not-configured-installed.trace.log)

**Comment by milesj** [comment]
@alexbepple Sorry jumping back on this.

For the node configured one, I think the double yarn's is because you have 2 node versions (20.14, 20.9), so each has its own yarn instance. I _think_ the issue is that these are running in parallel, but there's not enough logs to tell. Let me see if I can add some locks to prevent race conditions. This will land in v1.29.

As for the sigsegv, there's not a lot of info in the logs, so hard to tell. But it is failing at a similar point to the other issue, so I wonder if they are related.

**Comment by alexbepple** [comment]
Thanks, @milesj. Looking forward to try 1.29.

Your pointing out that there are two Node versions prompted me to try reproducing the failure for individual projects. I cannot. I.e. I cannot get `moon lido:pre-commit` or `moon carneval:pre-commit` to fail in the described fashion, but `moon :pre-commit` fails as described. This substantiates your hypothesis that the two Nodes running in parallel might be the issue.

**Comment by milesj** [comment]
Ok released 1.29, give that a shot.

**Comment by alexbepple** [comment]
Thank you, @milesj. My first impression is very good. I have not a single failure out of about 20 runs. I will therefore close this for now.

**Comment by milesj** [comment]
Awesome, glad to hear it.
