### ISSUE TITLE
[feature] root-level inputs should be greedy when using moon in non-monorepo situation

### ISSUE THREAD

**Issue by niieani** [moonrepo/moon#1672]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

[Documentation of task `inputs`](https://moonrepo.dev/docs/config/project#inputs) states that:

> If not defined or inherited, then all files within a project are considered an input (`**/*`), excluding root-level tasks.

This makes sense when trying to define tasks in a monorepo situation, where there are multiple projects, including the root-level one. But it was unexpected when I setup moon in a single-project configuration, without additional workspace. 

If the only project defined is the root project, it should behave the same way as a regular workspace, rather than be treated specially as a "root-level" (because it's the _only_ level).

**Describe alternatives you've considered**

I can specify inputs manually, but this is inconsistent between monorepo and non-monorepo projects. 

**Additional context**

I was writing some automation that generates my moon configuration, for both monorepo and non-monorepo projects, and got tripped up by this.

**Comment by milesj** [comment]
Fixed in 1.29

**Comment by niieani** [comment]
Thank you Miles! Your responsiveness and support continues to be unmatched. 🙇
