### ISSUE TITLE
[feature] vscode extension: moon console to use moon from path if available

### ISSUE THREAD

**Issue by sharpepd** [moonrepo/moon#1673]
**Is your feature request related to a problem? Please describe.**

The moon console VS Code extension states:

"This extension requires moon itself to be installed within the opened VS Code workspace."

I had assumed that it would also be OK if moon is on the system path, but this is not the case.

The confusing thing is that the moon console does display the moon projects and tasks detected in the workspace, but it is not possible to run them by clicking the "play" icon. The toolbar with the refresh icon etc, is missing also in this scenario. So, the extension is partially using the moon.exe on the path, but not fully.

**Describe the solution you'd like**

I would like the option for the option to work with the moon.exe that is on the path.

**Describe alternatives you've considered**

I initially was using git submodules to get the moon.exe into my repo (and hence the workspace). But this seemed a bit too cumbersome to maintain over all our repos).

**Additional context**

We are trying to use moon as a task runner for embedded c projects, so the default node_modules, does not fit for us.
Is there an alternative way to get the exe in the workspace?
The moon installation documentation for windows is installing moon to the path, so not supporting this seems inconsistent.

Missing "toolbar": ![image](https://github.com/user-attachments/assets/db99a23a-665e-4164-8749-8c50b96a9ea3)

**Comment by milesj** [comment]
@sharpepd We do support global but looks like it's Unix only. https://github.com/moonrepo/dev/blob/master/packages/vscode-extension/src/workspace.ts#L179

Should be an easy fix.

**Comment by sharpepd** [comment]
Yes, I see that. However, I am not clear on why the extension is able to read the projects and tasks and display them. Is it not using the moon exe for that?
(Also, in my case, I do have a windows version of which on my path, so that command should have returned something. But obviously a solution is needed that will generally work on Windows).
I am afraid, I am new to Rust (and not set-up to build), so I cannot easily prepare a fix myself (yet).

**Comment by MihaiPopescu1985** [comment]
This should do the trick:
```
  findMoonBin() {
    if (!this.root) {
      return null;
    }
    let binPath = import_vscode5.default.workspace.getConfiguration("moon").get("binPath", "moon");
    if (process.platform === "win32" && !binPath.endsWith(".exe")) {
      binPath += ".exe";
    }
    if (!import_path4.default.isAbsolute(binPath)) {
      binPath = import_path4.default.join(this.root, binPath);
    }
    if (import_fs4.default.existsSync(binPath)) {
      return binPath;
    }
    try {
      let globalBin = "";
	  if (process.platform === 'win32') {
        globalBin = import_execa.default.sync('cmd', ['/c', 'where', 'moon']).stdout;
	  } else {
        globalBin = import_execa.default.sync('which', ['moon']).stdout;
	  }
      if (globalBin && import_fs4.default.existsSync(globalBin)) {
        return globalBin;
      }
    } catch(error) {
		this.logger.appendLine("moon binary could not be found");
		this.logger.appendLine(`${error}`);
    }
    return null;
  }
```

**Comment by sharpepd** [comment]
I have created https://github.com/moonrepo/dev/pull/77

**Comment by sharpepd** [comment]
@milesj The pull request is now completed and in VS Code, I see a new version of the extension available (0.13.1). But it is still behaving as before (on my windows machine), i.e. is still broken. Are the changes actually published to the marketplace - or is some action still to happen to publish the changes?

**Comment by milesj** [comment]
Published some newer fixes.

**Comment by sharpepd** [comment]
0.13.2 of the extension is also not working and the code, is now different again and does not contain the code at all now for finding the global installation - this does not match the code on the master branch of moon/dev. So where is this coming from?


![image](https://github.com/user-attachments/assets/990e9dcd-ba9c-49b4-859e-f633e3d9b6aa)
