### ISSUE TITLE
[bug] project name is empty in inherited tasks unless explictly defined

### ISSUE THREAD

**Issue by marcus-sa** [moonrepo/moon#1680]
**Describe the bug**

I have to explicitly define the project name for it to be available in the inherited tasks

**Expected behavior**

For it to use the project's folder name as the project name in inherited tasks

**Comment by milesj** [comment]
@marcus-sa I don't really follow. Do you have an example config that isn't working?

**Comment by marcus-sa** [comment]
@milesj 

> .moon/tasks/typescript.yml
```yml
tasks:
  test:
    command: 'echo $projectName'
``` 

Assume you have a project that inherits the `test` task and you run that command:
```
$ moon project:test
```
The output will be empty, whereas if you explicitly define the project name then it'll no longer be empty
> project/moon.yml
```yml
project:
  name: project
```

**Comment by milesj** [comment]
@marcus-sa I think you just want `$project`?

`$projectName` maps to `project.name` which is human-readable metadata, not the actual ID of the project.

**Comment by marcus-sa** [comment]
@milesj yeah you're right. The docs is a bit confusing.

**Comment by marcus-sa** [comment]
> @marcus-sa I think you just want `$project`?
> 
> `$projectName` maps to `project.name` which is human-readable metadata, not the actual ID of the project.

Yeah, you're right. The documentation is a bit confusing. I'm also wondering why $projectName is empty in one scenario and not the other?

**Comment by milesj** [comment]
Well `project.name` is empty by default unless explicitly configured.

The "folder name" logic is only for the project ID.

**Comment by marcus-sa** [comment]
@milesj very confusing

**Comment by milesj** [comment]
`$project` = the project ID. The thing configured in `projects` in `workspace.yml`, and the thing used on the command line, and in task targets: `moon project app`, `moon run app:lint`. Here `app` is the ID.

`$projectName` = a human readable string derived from `project.name` in `moon.yml`. This is purely metadata for developers, and is only shown in `moon project` right now. It was added for a project/code ownership feature that never released.

An example in config:

```
# moon.yml

id: 'api'

project:
  name: 'Dashboard REST API'
  description: 'Primary REST API for the dashboard.'
  channel: '#dashboard-api'
```
