### ISSUE TITLE
[bug] moon query - flags combined with --affected not respected

### ISSUE THREAD

**Issue by Blissful89** [moonrepo/moon#1684]
**Describe the bug**

I am running `touched-files` in conjunction with `query projects --affected` in my github action. Ever moon version 1.29.0, all secondary flags are not respected.

**Steps to reproduce**

```shell
moon query touched-files | moon query projects --affected --type application --tasks test
```

The only difference between running my test bash script in between the two screenshots is that I have moon 1.27.9  before, and ran `proto pin moon 1.29.0`.

**Expected behavior**

Normally it would bring me all affected projects with code changes, which are of type application, and which are testable with the "test" command.

**Screenshots**

Before `v1.29.0`, this would return "just affected applications that have the test command":
<img width="287" alt="image" src="https://github.com/user-attachments/assets/73c0cab9-8220-4358-8cae-cfeb9a4a6449">

After `v1.29.0`, I now receive a list, of which I cannot even fathom why they are in the list / affected:
<img width="273" alt="image" src="https://github.com/user-attachments/assets/f89fb36e-596e-462a-85fe-7d2566528f23">

**Environment**
Before
```shell
moon --version // 1.27.9
```

After
```shell
moon --version // 1.29.0
```

**Comment by milesj** [comment]
@Blissful89 Do the logs actually show all those extras as being affected?

**Comment by milesj** [comment]
Figured it out, will patch soon!

**Comment by Blissful89** [comment]
> @Blissful89 Do the logs actually show all those extras as being affected?

Yes

**Comment by Blissful89** [comment]
> Figured it out, will patch soon!

Super thank you for the quick response!
