### ISSUE TITLE
[bug] pkl - allowedResources = null disallows reading env variables

### ISSUE THREAD

**Issue by harlequin** [moonrepo/moon#1715]
**Describe the bug**

The current version of rpkl disallows reading the environment variables.
Issue already raised and also resolved yesterday evening

https://github.com/z-jxy/rpkl/issues/21
https://github.com/z-jxy/rpkl/pull/22

**Steps to reproduce**

Somewhere in a *.pkl file
```
...
command = read("env:CI")
...
```

Problem solution would be to update the crate to 0.3.5 which includes the properties settings, 
It is implemented that the default properties are fitting to the [cli](https://pkl-lang.org/main/current/pkl-cli/index.html) interface defaults from pkl, which is including the possibilities of reading env variables.

**Comment by milesj** [comment]
Updated in v1.30.0.
