### ISSUE TITLE
[bug] Tasks with no inputs are always considered affected

### ISSUE THREAD

**Issue by kikones34** [moonrepo/moon#1743]
**Describe the bug**

If a task has an empty inputs list, it is always considered affected by the affected tracker. The use case for an empty list of inputs is for tasks whose inputs are solely dictated by their dependencies. In such a case, the intent is for the task to be affected iff its dependencies are affected.

**Steps to reproduce**

Define the following task:
```yaml
lint:
  deps:
    - format
    - typecheck
  inputs: []
```

Commit everything. Then change any file that does _not_ affect either of the dependencies.
Run `moon query tasks --affected --downstream deep` or `moon ci`. The `lint` task will be considered affected with the reason "other":

```
Task proj1:lint is affected by  env=[] files=[] upstream=[] downstream=[] other=true
```

**Expected behavior**

The task is only considered affected when `format` or `typecheck` are affected.

**Environment**

Moon version: 1.30.2 (linux musl)

**Comment by milesj** [comment]
@kikones34 What if the task has no dependencies?

**Comment by kikones34** [comment]
> @kikones34 What if the task has no dependencies?

@milesj Same behavior, it always gets triggered by any touched file anywhere.
In this case I guess it would make sense for it to never be affected, although it's hard for me to see a use case of a task with no deps and no inputs (unless it's some local dev utility not meant for CI anyway).

**Comment by milesj** [comment]
Yeah let me think about this a bit. I'm not 100% sure what the best approach is and what users expect here. I can see it going both ways.

**Comment by milesj** [comment]
Couldn't figure out a way to accomplish all scenarios without introducing new features, so removing the always affected for now.
