### ISSUE TITLE
[bug] Git Hooks not working when using Git Worktrees

### ISSUE THREAD

**Issue by b-dreissigacker** [moonrepo/moon#1756]
**Describe the bug**

When using Git Worktrees the Git Hooks are not set up properly.

**Steps to reproduce**

**Expected behavior**

The pre-commit hook should run.

**Additional context**
Before using moon to manage the Git Hooks I had some hooks in my project set up with husky(https://github.com/typicode/husky) which was working properly with git worktree.

**Comment by milesj** [comment]
@b-dreissigacker I've never used git worktrees. Can you describe where hooks are supposed to go in the worktree if not the root `.git` folder?

**Comment by b-dreissigacker** [comment]
To be honest, I'm still pretty new to using git worktrees, too. I've been using it for about 2 months now.

There is no .git folder in the root of the repo, but  content that is normally in the .git folder there instead, the hooks folder with the example hooks too.

If you create a new worktree folder for a branch, it doesn't contain a .git folder either, just a .git file with a key gitdir and an absolute path to the repo root folder.

for example:

/home/benjamin/repos/example/branchname/.git:

```
gitdir: /home/benjamin/repos/example/branchname
```

I assume you can tell that the folder you are in is a worktree folder because the .git folder is a file with the gitdir field and I assume you can just put the hooks in the hooks folder in the root folder.

Btw the `git root` command points to the root of the branch folder when I use git worktree and not to the root of the repo.

I hope this helps, let me know if there is anything else I should test/try out.

**Comment by b-dreissigacker** [comment]
@milesj I'm on moon 1.32.5 now but this issue does not seem to be fixed?

I have `syncHooks: true` in my workspace.yml so I would expect that the hooks are now created if I run any moon comand or do I have to run a special command to make it work in worktrees?

Here are the relevant parts of the output when I run `moon sync projects --log debug` in one of the branch folders:

```
[DEBUG 12:36:07.926] moon_vcs::git  Using git as a version control system
[DEBUG 12:36:07.926] moon_vcs::git  Attempting to find a .git directory or file  starting_dir="/home/benjamin/repo/551"
[DEBUG 12:36:07.926] moon_vcs::git  Found a .git file (submodule or worktree root)  git="/home/benjamin/repo/551/.git"
⠁ Syncing projects...                                                                                                                                                                                                                                                                                                 [DEBUG 12:36:07.926] moon_vcs::git  Unable to find .git, falling back to workspace root
[DEBUG 12:36:07.926] moon_vcs::git  Loading ignore rules from .gitignore  ignore_file="/home/benjamin/repo/551/.gitignore"

...

[DEBUG 12:36:07.939] moon_actions::actions::sync_workspace  Syncing workspace
[DEBUG 12:36:07.939] moon_actions::actions::sync_workspace  Syncing config schemas
[DEBUG 12:36:07.939] moon_actions::actions::sync_workspace  Syncing git hooks (vcs.syncHooks enabled)
```

repo ist the repo root and 511 is one of the branches:
```
$ git worktree list
/home/benjamin/repo         (bare)
/home/benjamin/repo/551     2055ce850 [branch]
/home/benjamin/repo/master  2055ce850 [master]
```

**Comment by milesj** [comment]
@b-dreissigacker It's not all moon commands, just `moon run` or `moon sync hooks`.

**Comment by b-dreissigacker** [comment]
Since it's a bare repo there is no .git folder in /home/benjamin/repo, the contents of this folder is what is usualy in the .git folder. 
There are hooks installed in /home/benjamin/repo/worktrees/551/hooks, but it looks like these are not used by git. 

I think there needs to be a script installed in /home/benjamin/repo/hooks too.
Something along the lines of `$(git rev-parse --git-dir)/hooks/pre-commit` should work to redirect it to the hook in `/home/benjamin/repo/worktrees/<name>`.
