### ISSUE TITLE
[feature] Monorepo root level tasks

### ISSUE THREAD

**Issue by tanepiper** [moonrepo/moon#215]
**Is your feature request related to a problem? Please describe.**

As per the description of moon itself:

> The primary focus of moon is a build system, and for it to operate in any capacity, it requires tasks to run. In moon, a task is an npm binary or system command that is ran as a child process within the context of a project (is the current working directory). Tasks are defined per project with [project.yml](https://moonrepo.dev/docs/config/project), or inherited by all projects with [.moon/project.yml](https://moonrepo.dev/docs/config/global-project).

It seems moon however doesn't have a concept of root level tasks, only project level?  Can the root be set as a project, the docs don't seem to suggest so as I guess you'd also need a `project.yml` there?

**Describe the solution you'd like**

The ability to define tasks in the `workspace.yml` such as running `package.json` tasks or passing local scripts

**Describe alternatives you've considered**

Just run them as package manager tasks or shell scripts - but possibly don't benefit from moons features with these tasks.

**Comment by milesj** [comment]
@tanepiper Yeah theoretically you could create a `project.yml` in the root, and configure `.moon/workspace.yml` as such:

```yaml
projects:
  root: '.'
```

I haven't actually tested this, but I can't think of anything that would stop this from actually working. I'll verify it for the 0.8 release.

**Comment by milesj** [comment]
@tanepiper I've added some docs on creating/using a root-level project: https://moonrepo.dev/docs/guides/root-project

The glob support will be available in the next release.

**Comment by milesj** [comment]
Glob support landed in 9.1.
