### ISSUE TITLE
RFC: Rename project-level `project.yml`.

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#228]
The `project.yml` is rather straight forward, it configures the project. However, this name is _very_ generic, and is also used by other tooling, such as:

- `xcodegen` - https://github.com/yonaskolb/XcodeGen
- DigitalOcean - https://docs.digitalocean.com/products/functions/reference/project-configuration/
- Frontastic - https://docs.frontastic.cloud/v1.1/docs/projectyml

The risk of collision is a non-zero amount. We should potentially rename it?

My only suggestion is `moon.yml`, which would align a bit nicer with `.moon/*.yml` files.

**Comment by glamseam** [comment]
@milesj I think your suggestion is good.
Using the name of the tool might create a file icon in an editor such as VSCode.
That would make it easier to find.

**Comment by milesj** [comment]
@glamseam That's a great point. People do love their icons, myself included.

**Comment by milesj** [comment]
Landing in v0.10.
