### ISSUE TITLE
[bug] Error output is missing when using vue-tsc

### ISSUE THREAD

**Issue by glamseam** [moonrepo/moon#237]
**Describe the bug**

When I run `vue-tsc` as a task from moon, it does not output error details.

**Steps to reproduce**

1. Clone [moonrepo/examples](https://github.com/moonrepo/examples)
2. In project root `npm i`
3. Edit `apps/vue-vite-app/src/App.vue`
```
- import { RouterLink, RouterView } from 'vue-router';
+ import { RouterLin, RouterView } from 'vue-router';
```

**Expected behavior**

Run `npx -w apps/vue-vite-app vue-tsc --noEmit --project tsconfig.vitest.json --composite false`

Normally, `vue-tsc` error output looks like this.

<img width="949" alt="bbb" src="https://user-images.githubusercontent.com/25496839/182749001-c787d2cf-102d-4b24-9aa1-99d2477ac991.png">

however...

Run `npm run moon r vue-vite-app:typecheck`

<img width="942" alt="aaa" src="https://user-images.githubusercontent.com/25496839/182749520-ace2ac78-12a5-477f-9289-766df82d3467.png">

**Environment**

- moon v0.9.0
- npm v8.11.0
- node v16.16.0
- macOS 12.4 (Intel)

**Comment by milesj** [comment]
@glamseam I wonder if the codeframe only appears if it thinks the terminal is a TTY. Since tasks are piped child processes, it may be losing that functionality.

Could you do me a favor and verify if that's true?

**Comment by glamseam** [comment]
@milesj How can I verify it?

**Comment by milesj** [comment]
@glamseam You can probably create a basic Node.js script that runs `vue-tsc` as a child process: https://nodejs.org/api/child_process.html#child_processexecsynccommand-options

```js
console.log(execSync('vue-tsc', ['...args'], { stdio: 'pipe' });
```

**Comment by glamseam** [comment]
@milesj Thank you for the information.

Result

```
{
  status: 2,
  signal: null,
  output: [
    null,
    `src/App.vue(2,10): error TS2724: '"vue-router"' has no exported member named 'RouterLin'. Did you mean 'RouterLink'?\n`,
    ''
  ],
  pid: 40273,
  stdout: `src/App.vue(2,10): error TS2724: '"vue-router"' has no exported member named 'RouterLin'. Did you mean 'RouterLink'?\n`,
  stderr: ''
}
```

**Comment by milesj** [comment]
Thanks, looks to be true. I'll see if there's anything we can do about it.

**Comment by milesj** [comment]
@glamseam I did a bit of digging and I believe this is `tsc` itself: https://github.com/microsoft/TypeScript/issues/30282

Are you able to pass a `--pretty` flag through `vue-tsc`?

**Comment by glamseam** [comment]
@milesj Amazing!!! `--pretty` flag gave me the behavior I was hoping for!

<img width="952" alt="vt" src="https://user-images.githubusercontent.com/25496839/183225270-506011f4-40a5-4249-9fb1-4e4de88d464d.png">

Sorry, I should have done more research before reporting this.
Thank you.

**Comment by milesj** [comment]
@glamseam No worries, this was news to me as well, hah! I'll add this to the docs for future reference.

**Comment by milesj** [comment]
Updated, thanks! https://github.com/moonrepo/moon/commit/a099e04f570b48da30709698cd5599f2af97fdd4
