### ISSUE TITLE
[bug] Moonrepo doesn't detect projects if folders are capitalized.

### ISSUE THREAD

**Issue by NikolaRHristov** [moonrepo/moon#256]
When running moonrepo from the root directory all the projects that have folder's names capitalized are not detected. 

Dependency graph with projects names capitalized

![x](https://user-images.githubusercontent.com/90222871/184360140-286b26ec-78e3-46dc-bc58-e4652f560c5c.svg)

and without

![x](https://user-images.githubusercontent.com/90222871/184360518-b5c46103-1099-4119-8697-21789ff423c5.svg)

Best,
Nikola.

**Comment by milesj** [comment]
@NikolaRHristov How are you configuring the projects? With a map or glob?

Can you paste the output of `moon project-graph`?

**Comment by milesj** [comment]
Trying to reproduce this with no luck. Need more information.

![graphviz(1)](https://user-images.githubusercontent.com/143744/184443116-feeaf17a-8e9b-46d7-b710-56a8be33ff44.png)

**Comment by milesj** [comment]
This is fixed in v0.11.
