### ISSUE TITLE
[question] Task runner glob

### ISSUE THREAD

**Issue by bclark-p44** [moonrepo/moon#340]
I have a monorepo with both apps and packages similar to the examples repo. The apps are deployed using `vercel` and the package's release is managed by `changesets`. I am updating my release GitHub to release the packages, is there a way to only build just the packages? Will the task runner accept a glob for tasks? `yarn moon {packages/*}:build` 

[PR for reference]( https://github.com/project44/manifest/pull/111)

**Comment by milesj** [comment]
@bclark-p44 It unfortunately does not at this time. However, you could create a custom script that calls out to `moon query projects` to achieve what you are looking for. https://moonrepo.dev/docs/commands/query/projects

Something like this:

```ts
const projects = await execa('moon', ['query', 'projects', '--source', '^packages', '--tasks', 'build'], { preferLocal: true });

await execa('moon', ['run', ...projects.map(p => `${p.id}:build`)], { preferLocal: true });
```

**Comment by bclark-p44** [comment]
Great! Thank you
