### ISSUE TITLE
New command: `moon migrate nx-project`

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/moon#374]
A command that would allow one to migrate their NX projects to moon. This can be achieved by leveraging `nx dep-graph` which provides a lot of information about each project.

What do you think about this feature?

If accepted, i would like to make a PR for the same.

**Comment by mi4uu** [comment]
im here just because Im looking for something like this ;) 
hopefully supportning not only fresh nx but something like v14 too xD

**Comment by IgnisDa** [comment]
Hey @mi4uu I have since stopped using Nx, so don't have any motivation to pick this up. You should make a PR for it 😉.

**Comment by milesj** [comment]
We've got an initial version of this now https://moonrepo.dev/blog/moon-v1.22
