### ISSUE TITLE
[feature] Add `format.tabSize` for `.moon/workspace.yml`

### ISSUE THREAD

**Issue by 1aron** [moonrepo/moon#397]
First, excited to discover this very useful tool and am importing its workflow for my project [Master CSS](https://github.com/master-co/css)!

**Is your feature request related to a problem? Please describe.**

Whenever `moon run` is executed it reads and writes the user's config like `tsconfig.json` or `*.yml` and forces to be formatted with `tabSize: 2`, which cannot be customized.

**Describe the solution you'd like**

Provide additional configuration `format.tabSize` in `.moon/workspace.yml` for customization.

<img width="685" alt="Screen Shot 2022-10-29 at 1 43 12 AM" src="https://user-images.githubusercontent.com/33840671/198699468-cdbfbbba-9e65-4660-a7a5-4c7473595a48.png">

**Comment by milesj** [comment]
@1aron I'll look into this, but ideally, I don't need a new setting for it. Do you use `.editorconfig` by chance?

**Comment by 1aron** [comment]
> @1aron I'll look into this, but ideally, I don't need a new setting for it. Do you use `.editorconfig` by chance?

You mean `.editorconfig` if it exists then moon will automatically read its config?

**Comment by milesj** [comment]
@1aron It doesn't right now, but I'd probably base indentation off of it since it's a standard.

**Comment by 1aron** [comment]
@milesj Sounds good! 👍🏻 The feature is necessary.

**Comment by milesj** [comment]
Will land in 0.19 https://github.com/moonrepo/moon/pull/419

**Comment by milesj** [comment]
0.19 released! It's not perfect, but we'll iterate on it over time.
