### ISSUE TITLE
[bug] Running moon in codesandbox ci throws an GLIBC error

### ISSUE THREAD

**Issue by bclark-p44** [moonrepo/moon#409]
**Describe the bug**

Hello,

I'm not sure if this is an issue with moonrepo or codesandbox ci, but when running moon build via yarn in the codesanbox environment the following error is thrown:

```
yarn run moon run :build (in /tmp/4d7ea44c)
/tmp/4d7ea44c/node_modules/@moonrepo/cli/moon: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /tmp/4d7ea44c/node_modules/@moonrepo/cli/moon)
{ Error: Process rejected with status code 1
    at ChildProcess.<anonymous> (/app/dist/utils/exec.js:20:27)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) code: 1 }
/tmp/4d7ea44c/node_modules/@moonrepo/cli/moon: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /tmp/4d7ea44c/node_modules/@moonrepo/cli/moon)
{ Error: Process rejected with status code 1
    at ChildProcess.<anonymous> (/app/dist/utils/exec.js:20:27)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) code: 1 }
```

I'm using yarn 3.2.3 and have moon assign to script as:

```
"moon": "$(yarn bin moon)"
```

**Steps to reproduce**

Here is a link to the codesandbox build:

https://ci.codesandbox.io/status/project44/manifest/pr/147/builds/310618

and the PR in question:

https://github.com/project44/manifest/pull/147

**Expected behavior**

I would assume that the binary when ran via yarn should work in most node environments. 

**Screenshots**

**Environment**

```
node -v (in /tmp/4d7ea44c)
v16.13.0
yarn -v (in /tmp/4d7ea44c)
3.2.3
```

**Additional context**

**Comment by milesj** [comment]
@bclark-p44 This is typically caused by the environment running an old Linux distro, probably Ubuntu 18, and the required libc doesn't exist, or is too old. There's not an easy solution to this, these are the options:

- Run moon and your repo in a Docker container that has the right environment and libs.
- Upgrade the Linux distro to a newer one.
- Try and install newer libc: https://stackoverflow.com/questions/72513993/how-install-glibc-2-29-or-higher-in-ubuntu-18-04

**Comment by milesj** [comment]
Here's some more context on the problem: https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html
