### ISSUE TITLE
[feature] Git hooks

### ISSUE THREAD

**Issue by itsezc** [moonrepo/moon#433]
**Is your feature request related to a problem? Please describe.**

Add and manage git hooks via Moon, this is useful for when you need to setup workflows i.e. commit linting for conventional commits. Additionally, this could be enhanced further on the VSCode extension.

**Describe alternatives you've considered**

Using third party crates / packages, this creates a disconnect in the toolchain.

**Additional context**

Node / Python based git hook packages require additional dependencies to be installed. Having git hooks built-in to Moon reduces complexity. For a full feature comparison, see https://pre-commit.com/ or https://typicode.github.io/husky/#/

**Comment by itsezc** [comment]
A rust implementation could be found here:
https://git.bauke.xyz/Holllo/hooked

**Comment by milesj** [comment]
This is landing in v1.9 today!
