### ISSUE TITLE
`moon run` does not reinstall dependencies if `package.json` is changed

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/moon#453]
Sometimes I change `package.json` of my projects manually. But when I run `moon setup`, it does not run `pnpm install` for me:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/60938164/202363299-bd7a05c1-db9c-4072-b257-7ce75bb1e230.png">

I think it takes only changed lockfiles into account. 

I would like to suggest that changed `package.json` should also be taken into account when determining if `pnpm install` is run by `moon setup`.

**Comment by milesj** [comment]
@IgnisDa I do check for it: https://github.com/moonrepo/moon/blob/master/crates/node/platform/src/actions/install_deps.rs#L128

Can you paste the logs next time this happens.

**Comment by IgnisDa** [comment]
@milesj Here is an example:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/60938164/202493599-30fbbf50-a80e-445f-89c2-0f762c7431a2.png">

I am adding `urql` as a dependency to `apps/website/package.json` but it does not pick up that change.

**Comment by IgnisDa** [comment]
I think I found the problem. Here (https://github.com/IgnisDa/moon/blob/d2a0cb0a1dad87b7fa55a599fdf5acaa5e36764b/crates/cli/src/commands/setup.rs#L22), it is passing `None` as the `context` which causes it to have no touched files.

**Comment by IgnisDa** [comment]
Digging into it, the `has_modified_files` variable (https://github.com/IgnisDa/moon/blob/d2a0cb0a1dad87b7fa55a599fdf5acaa5e36764b/crates/node/platform/src/actions/install_deps.rs#L125) is always set to `false`. [This](https://github.com/IgnisDa/moon/blob/d2a0cb0a1dad87b7fa55a599fdf5acaa5e36764b/crates/node/platform/src/actions/install_deps.rs#L152) line evaluates to `true` because `last_modified` (https://github.com/IgnisDa/moon/blob/d2a0cb0a1dad87b7fa55a599fdf5acaa5e36764b/crates/node/platform/src/actions/install_deps.rs#L143) changes when the lockfile changes.

**Comment by milesj** [comment]
> I think I found the problem. Here (https://github.com/IgnisDa/moon/blob/d2a0cb0a1dad87b7fa55a599fdf5acaa5e36764b/crates/cli/src/commands/setup.rs#L22), it is passing `None` as the `context` which causes it to have no touched files.

Ah that's right. This is working as intended unfortunately. The `setup` command isn't meant to constantly be ran, it's like something you run once while setting up moon, or setting up the toolchain.

You'll need to rely on `moon run` for the install to trigger correctly.

**Comment by IgnisDa** [comment]
Ah okay makes sense. Closing this.

**Comment by IgnisDa** [comment]
@milesj Reopening this because when I change `package.json` manually and then run `moon run visualizer:serve`, it does not pick up changes in the `package.json`.
