### ISSUE TITLE
[feature]  multiple status filters

### ISSUE THREAD

**Issue by tomdavidson** [moonrepo/moon#455]
**Is your feature request related to a problem? Please describe.**

Id like to run a task only on modified and added files.  `--affected` defaults to `--status=all` which includes deleted, untracked and unstaged.

**Describe the solution you'd like**

Support multiple status in the filter such as :

- `--status=added --status=modified` 
- `--status=added,modified`
- `--status={added,modified,!unstaged}`

**Describe alternatives you've considered**

Using git directly rather than moon and scripting out the workspace names to pass to a `moon run task` invocation.

**Comment by milesj** [comment]
This will definitely be possible.

**Comment by milesj** [comment]
Implemented here https://github.com/moonrepo/moon/pull/495

**Comment by milesj** [comment]
Released in 0.21 soon.
