### ISSUE TITLE
[bug] .env file does not break cache when listed as an input

### ISSUE THREAD

**Issue by bryanjswift** [moonrepo/moon#481]
**Describe the bug**

It appears that `.env` file can not be considered an input. Presumably this is related to the handling of the `envFile` option and it defaulting to `.env` (per https://moonrepo.dev/docs/config/project#envfile). Specifying a different, existing file for the `envFile` does not appear to change this behavior.

**Steps to reproduce**

1. Create a task which should rebuild when the `.env` file changes

        tasks:
          env-example:
            command: 'node scripts/env-example.js .env.sample .env'
            inputs:
              - '.env'
              - '.env.sample'
              - 'scripts/env-example.js'
            outputs:
              - 'env-example.out'

2. Execute the task
3. Change the `.env` file
4. Execute the task again
5. The cached output is re-used

**Expected behavior**

The cached output from the first run is not re-used and the script is re-executed

**Environment**

`npx envinfo` is hanging, I'll update if it completes.

**Additional context**

This script is simplified from something my project is doing but it is sufficient to demonstrate the behavior described.

```js
#!/usr/bin/env node
// scripts/env-example.js

const fs = require('node:fs');
const fsp = require('node:fs/promises');
const path = require('node:path');
const readline = require('node:readline');

const cwd = process.cwd();

async function compareEnvFiles(filenames) {
  const sample = path.join(cwd, filenames[0]);
  const environment = path.join(cwd, filenames[1]);
  const out = path.join(cwd, 'env-example.out');
  try {
    await fsp.access(sample, fs.constants.R_OK);
  } catch (e) {
    throw new Error(`${sample} is not a readable file`);
  }
  try {
    await fsp
      .access(environment, fs.constants.R_OK)
      .catch(() => fsp.copyFile(sample, environment));
  } catch (e) {
    // copy sample file
    throw new Error(
      `${environment} is not a readable file and could not be created`
    );
  }
  try {
    const outHandle = await fsp.open(out, 'w');
    const {variables: sampleVariables} = await readVariables(sample);
    const {variables: environmentVariables} = await readVariables(environment);
    const allVariables = sampleVariables.concat(environmentVariables);
    let data = '';
    for (const variable of allVariables) {
      data += `${variable.key}=${variable.value}`;
    }
    await fsp.writeFile(outHandle, Buffer.from(data));
  } catch (e) {
    throw new Error(`${out} is not a writable file`);
  }
}

async function readVariables(filename) {
  const variables = [];
  const optionals = [];
  const rl = readline.createInterface({
    input: fs.createReadStream(filename),
  });
  rl.on('line', (line) => {
    const result = line.match(/^#?([A-Z_]+)=["']?(.*)["']?$/);
    if (result !== null && line.startsWith('#')) {
      optionals.push({key: result[1], value: result[2]});
    } else if (result !== null) {
      variables.push({key: result[1], value: result[2]});
    }
  });
  return new Promise((resolve) => {
    rl.on('close', () => {
      resolve({optionals, variables});
    });
  });
}

async function handleCi(filenames) {
  const envFile = path.join(
    cwd,
    filenames.length === 0 ? '.env' : filenames[1]
  );
  return fsp
    .access(envFile, fs.constants.R_OK)
    .catch(() => fsp.writeFile(envFile, Buffer.from('')));
}

async function main(args) {
  let filenames = [];
  if (typeof process.env.CI !== 'undefined') {
    return handleCi(args);
  } else if (args.length === 0) {
    filenames = ['.env.sample', '.env'];
  } else if (args.length !== 2) {
    throw new Error('Pass the paths to sample and environment files');
  } else {
    filenames = args;
  }
  return compareEnvFiles(filenames);
}

if (require.main === module) {
  main(process.argv.slice(2)).catch((reason) => {
    if (reason instanceof Error) {
      console.error(reason.message);
    } else if (typeof reason === 'string') {
      console.error(reason);
    } else {
      throw reason;
    }
  });
}
```

**Comment by milesj** [comment]
This is surprising since it's even explicitly defined as an input. I wonder if it's because of the leading dot. Will look into.

**Comment by bryanjswift** [comment]
> This is surprising since it's even explicitly defined as an input. I wonder if it's because of the leading dot. Will look into.

For what it's worth, changes to the `.env.sample` and script do trigger rebuilds as expected.

**Comment by milesj** [comment]
Ok that does help narrow it down. I think I have an idea of where to look.

**Comment by milesj** [comment]
@bryanjswift Oh, one thing. Are these files `.gitignored`? If so, that's the problem.

Hashing runs through `git hash-object` and if they are git ignored, I don't receive a hash.

**Comment by milesj** [comment]
Working on this here: https://github.com/moonrepo/moon/pull/482

**Comment by bryanjswift** [comment]
> @bryanjswift Oh, one thing. Are these files `.gitignored`? If so, that's the problem.
> 
> Hashing runs through `git ls-tree` and if they are git ignored, I don't receive a hash. I'm not sure of a way around this off the top of my head, so let me think about it.

Ahh, `.env` is indeed ignored by git via `.gitignore`.

**Comment by milesj** [comment]
Yeah it kind of didn't cross my mind while building it, however...

It looks like `git hash-object` works on ignored files, which is what explicit inputs use. Globs use `git ls-tree` and won't work there, so I believe I have a way around this for now.

**Comment by bryanjswift** [comment]
🎉 thanks for the super fast turn around! I look forward to trying this out!

**Comment by milesj** [comment]
Of course!

Having some release issues right now, so I'll let ya know when it goes through.

**Comment by milesj** [comment]
Ok landed, let me know if it doesn't work!

**Comment by bryanjswift** [comment]
> Ok landed, let me know if it doesn't work!

Initial test indicates it is working as expected, thanks again!
