### ISSUE TITLE
[bug] Symlink of moon binary during installation fails if the home directory is mounted on a seperate partition

### ISSUE THREAD

**Issue by benediktms** [moonrepo/moon#511]
**Describe the bug**

If a user tries to install the moon binary via the script provided in the documentation, but their home directory is not on the same partition as their OS installation the symlink will silently fail (only tested on Linux, unsure how this behaves on different operating systems)

**Steps to reproduce**
- Have a Linux installation where the home directory is mounted on a separate partition
- Install moon
- after the installation attempt to run the `moon` binary

**Expected behavior**
The symlink should be created correctly even if the home directory is located on a separate partition.

- On Linux, manually creating an explicit symlink works, but it has to be an absolute path otherwise running the binary will error with: `too many levels of symbolic links: moon`
```bash
ln -s ~/.moon/tools/moon/latest/moon /usr/local/bin/moon
```

**Comment by milesj** [comment]
So the script is symlinking using absolute paths for both: https://github.com/moonrepo/moon/blob/master/website/static/install.sh#L64

I also updated the script to display a PATH message when symlinking fails. Did you not receive that message?

**Comment by benediktms** [comment]
Tested again, and I received the message, must have missed it the first time/only saw the success message :) But should this script not prompt for sudo permissions?

**Comment by milesj** [comment]
I'm not sure this script should sudo. That's just another can of worms if something goes wrong,

**Comment by benediktms** [comment]
Fair enough, I'll close this issue then since everything is working as intended
