### ISSUE TITLE
[feature] `project` fields in `moon.yml` should be optional

### ISSUE THREAD

**Issue by itsezc** [moonrepo/moon#524]
**Is your feature request related to a problem? Please describe.**

Currently when defining a `project` field, all of its fields need to be filled but this is cumbersome and sometimes not applicable, as such all fields should be optional.

For example not all projects have channels, and there might only be one owner (the organization that the repo belongs to) and therefore it just becomes repetitive.

**Describe the solution you'd like**

All fields should be optional.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by milesj** [comment]
This has landed in v0.22!
