### ISSUE TITLE
[feature] `upgrade` command to the binary

### ISSUE THREAD

**Issue by itsezc** [moonrepo/moon#526]
**Is your feature request related to a problem? Please describe.**

Add the ability to upgrade the moon binary with an `upgrade` command

**Describe the solution you'd like**

The command should check for the latest release of moon and install it, additionally passing a `--nightly` flag should install a nightly version if available.

**Describe alternatives you've considered**

Re-running the install script but this is not good UX

**Additional context**

N/A

**Comment by milesj** [comment]
This is done.
