### ISSUE TITLE
[feature] Universal formatter

### ISSUE THREAD

**Issue by itsezc** [moonrepo/moon#533]
**Is your feature request related to a problem? Please describe.**

Introduce a formatter to the Moon toolchain to replace tools such as Editorconfig.

**Describe the solution you'd like**

Implement a simple universal formatter (similar to Editorconfig) built-in to the Moon toolchain, a new config file maybe added in `.moon/formatter.yml`. This also extends into the VSCode (and potentially other IDEs) extension. 

**Describe alternatives you've considered**

Currently, the go to is using Editorconfig, while this is acceptable it introduces a new dependency which could otherwise be avoided.

**Additional context**

**Comment by milesj** [comment]
Have thought about this a bit and I think `.editorconfig` is best. It's a pretty widely supported standard, and adding a moon specific one probably isn't worth it.
