### ISSUE TITLE
[feature] Task inheritance based on tags

### ISSUE THREAD

**Issue by itsezc** [moonrepo/moon#583]
**Is your feature request related to a problem? Please describe.**

I want to be able to split tasks by the type of project, for instance currently I have many typescript applications, however some are NextJS projects others are SvelteKit while there are other use cases, all different in how each tasks work. I would like to have project categories to split them by, i.e. `svelte-app` or `next-app` and have tasks defined under these, similar to how we can have them configured by language and type currently. This provides a lot of flexibility for how an org would organise their projects.

**Describe the solution you'd like**

Split tasks by `category`, which can be an arbitrary value provided on `<project>/moon.yml` and matched against `.moon/tasks.yml` or `.moon/tasks/<category>.yml`

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by bryanjswift** [comment]
@milesj what if `type` in `moon.yml` wasn't restricted to the four values (https://moonrepo.dev/docs/config/project#type). Then I think `.moon/tasks/<language>-<type>.yml` would satisfy this use case.

**Comment by milesj** [comment]
I'm looking into a tagging system that would help solve this. The tags would also be used to enforce project boundaries and constraints. Is pretty involved so will probably land after v1.

**Comment by RichiCoder1** [comment]
Either tags or types would be great for this! Another example I have is `infra-as-code` projects like CDK or SST which are ostensibly "javascript" projects but which have very different behaviors (diff and deploy).

**Comment by milesj** [comment]
Landed in v1.2!
