### ISSUE TITLE
[bug] operation canceled in github actions

### ISSUE THREAD

**Issue by bclark-p44** [moonrepo/moon#588]
**Describe the bug**

When running `moon ci` via a GitHub action the runner will take about 10 minutes and then fail, reporting `the operation was canceled`. This is a fairly large project with a lot of packages, not sure if that could be the culprit or not. When I run all the applicable scripts locally they run just fine, the scripts being ran are:

- build
- lint
- format (prettier)
- typecheck
- test (jest)

**Steps to reproduce**

Here's a link to a PR presenting the issue:

https://github.com/project44/manifest/pull/211

**Expected behavior**

**Screenshots**

<img width="825" alt="Screenshot 2023-02-01 at 2 54 14 PM" src="https://user-images.githubusercontent.com/98107867/216168148-f15a280c-b067-4389-b488-81c89cfbf0dc.png">

**Environment**

```
node 18
```

**Additional context**

**Comment by milesj** [comment]
My initial thought is maybe there's some task that runs forever (like a dev server) that shouldn't be running in CI.

**Comment by bclark-p44** [comment]
Not seeing any dev tasks running, let me make sure there isn't a hangup in jest. Maybe a test runner is stuck.

**Comment by bclark-p44** [comment]
Mmm, nope removed any tests that may hang, still just getting a random canceled:

<img width="1588" alt="Screenshot 2023-02-01 at 5 38 56 PM" src="https://user-images.githubusercontent.com/98107867/216192420-84428d26-8d2e-4dc8-9f36-b3d125d91de5.png">

**Comment by milesj** [comment]
@bclark-p44 That error looks like its coming from the GH runner itself. Can you re-run the job but with GH debug mode enabled?

**Comment by milesj** [comment]
Also might be a memory issue? https://github.com/actions/runner-images/issues/1918

If you upgrade to v0.22, you can try the new `--concurrency` setting and try reducing to like only running 6 at time.

**Comment by bclark-p44** [comment]
I'll try those and report back! Thanks for the help

**Comment by bclark-p44** [comment]
Looks like `--concurrency` works! Thanks for the quick responses.

**Comment by milesj** [comment]
Awesome, glad that worked!
