### ISSUE TITLE
[feature] Add shortcut commands for common targets

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#61]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Right now to run a build/lint/etc you have to type `moon run <project>:build`. While this isn't too verbose, we should also support shortcuts like `moon build <project>`, `moon lint ...`, `moon format ...`, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by milesj** [comment]
After thinking about this more, I might be against it. In the off chance that we want to support some form of "moon linting", or testing, then I would like to keep `moon lint` around.

**Comment by hustcer** [comment]
How about making `moon r` as a alias of `moon run`?

**Comment by milesj** [comment]
@hustcer That will actually land in the next version.

**Comment by milesj** [comment]
This will most likely not happen, closing.
