### ISSUE TITLE
[feature]  `moon docker setup` command

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/moon#625]
As per the Discord conversation.

> moon setup doesn't install dependencies at all anymore. It was changed a while back.

> Is there a command that does that? Otherwise it hurts caching performance because the build step is always run when project sources change. I think that is necessary since otherwise the docker integration will be feature incomplete.

> We can probably look into a `moon docker setup` or something.

**Comment by IgnisDa** [comment]
@milesj Any updates on this? Otherwise I can work on this. Need it for my docker setup.

**Comment by milesj** [comment]
It won't make it until the next release, so 2 weeks away. Feel free to submit a PR!

**Comment by milesj** [comment]
Started on this here https://github.com/moonrepo/moon/pull/665

**Comment by milesj** [comment]
Landed in 0.26
