### ISSUE TITLE
[bug] `moon query projects --affected` is hanging

### ISSUE THREAD

**Issue by bryanjswift** [moonrepo/moon#628]
**Describe the bug**

When executing `moon query projects --affected` the command doesn't return. It does not appear to be consuming CPU like a running command, it seems to be doing nothing.

**Steps to reproduce**

1. Check out a project with moon setup
2. Optionally make some files dirty by editing them (this doesn't seem to impact behavior)
3. Execute `moon query projects --affected`

**Expected behavior**

A list of projects which have had changes affecting their tasks would be displayed.

**Screenshots**

<img width="1090" alt="Screenshot 2023-02-17 at 16 44 55" src="https://user-images.githubusercontent.com/9911/219799676-512c8cba-7b6a-426a-bfbb-d8cf7fdec8e0.png">

**Environment**

```
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 33.72 MB / 16.00 GB
    Shell: 5.2.15 - /opt/homebrew/bin/bash
  Binaries:
    Node: 16.19.0 - /private/var/folders/q1/8s_w2kc91f5dldbz2ndh5s0r0000gn/T/xfs-49effe0b/node
    Yarn: 3.3.0 - /private/var/folders/q1/8s_w2kc91f5dldbz2ndh5s0r0000gn/T/xfs-49effe0b/yarn
    npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Languages:
    Bash: 5.2.15 - /opt/homebrew/bin/bash
    Go: 1.19.5 - /opt/homebrew/bin/go
    Java: 11.0.17 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.11.2 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.67.1 - /Users/bryanjswift/.cargo/bin/rustc
  npmPackages:
    @graphql-codegen/cli: ^2.16.4 => 2.16.4
    @graphql-codegen/typescript: ^2.8.7 => 2.8.7
    @graphql-codegen/typescript-operations: ^2.5.12 => 2.5.12
    @moonrepo/cli: ^0.24.2 => 0.24.2
    @types/node: ^16.11.62 => 16.18.11
    @typescript-eslint/eslint-plugin: ^5.48.1 => 5.48.1
    @typescript-eslint/parser: ^5.48.1 => 5.48.1
    @vercel/nft: ^0.20.1 => 0.20.1
    esbuild: ^0.17.7 => 0.17.7
    esbuild-node-externals: ^1.4.1 => 1.4.1
    esbuild-plugin-glsl: ^1.1.0 => 1.1.0
    esbuild-plugin-svgr: ^1.0.1 => 1.0.1
    eslint: ^8.31.0 => 8.31.0
    eslint-config-prettier: ^8.6.0 => 8.6.0
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0
    graphql: ^16.6.0 => 16.6.0
    hygen: ^6.2.11 => 6.2.11
    prettier: ^2.7.1 => 2.7.1
    pretty-quick: ^3.1.3 => 3.1.3
    ts-node: ^10.9.1 => 10.9.1
    typescript: ^4.9.4 => 4.9.4
```

**Additional context**

Really what I wanted was to use something like `moon run --affected --remote :test` to execute only the tests that have been impacted by the set of changes. However this seems to cause only the relevant `:test` tasks to execute and skips the dependencies of those `:test` tasks. I was then attempting to explore ways to do what I wanted with the task or project querying tools but they ended up not returning anything. This seems like multiple bugs to me but I am not sure if the behavior of `moon run --affected --remote :test` is expected; however a hanging command seems like a definite bug.

**Comment by bryanjswift** [comment]
> Really what I wanted was to use something like `moon run --affected --remote :test` to execute only the tests that have been impacted by the set of changes. However this seems to cause only the relevant `:test` tasks to execute and skips the dependencies of those `:test` tasks. I was then attempting to explore ways to do what I wanted with the task or project querying tools but they ended up not returning anything. This seems like multiple bugs to me but I am not sure if the behavior of `moon run --affected --remote :test` is expected; however a hanging command seems like a definite bug.

I just tried this again after updating to v0.24.2 and it seems like the behavior I indicated might be fixed in the latest version.

**Comment by milesj** [comment]
Looks like I'm able to reproduce the hanging locally as well. Curious why tests work though...

**Comment by milesj** [comment]
Figured it out https://github.com/moonrepo/moon/pull/629
