### ISSUE TITLE
[bug] Running multiple moon processes at the same time causes race condition on tsconfig.json

### ISSUE THREAD

**Issue by tbezman** [moonrepo/moon#651]
**Describe the bug**

Ok, so at Gallery, we need to run the following processes to get our dev server up and running
- GraphQL Codegen, mostly for test type generation
- Relay Compiler, for our relay usage.
- Next Dev Server

We're using the `concurrently` package to run all of these at once. Two of the above three commands are Moon tasks. It seems like since they both start at the same time, both moon tasks are trying to write to the `tsconfig.json` at the same time and occasionally I'll get this error

You can see the Moon task here https://github.com/gallery-so/gallery/blob/main/apps/web/moon.yml#L32

**Steps to reproduce**

1. Clone the gallery frontend codebase https://github.com/gallery-so/gallery/tree/main
2. Run `moon run web:dev` a few times until the issue happens.

**Expected behavior**

It should not error out

**Screenshots**

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/6754223/221252045-3b92ab4c-564a-4aee-a85b-2f0f7f6420c0.png">

**Environment**

```

  System:
    OS: macOS 13.1
    CPU: (20) arm64 Apple M1 Ultra
    Memory: 924.58 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /private/var/folders/qr/pwndt2n55vs9z6w4dfnh6k440000gn/T/xfs-f78acc88/node
    Yarn: 3.4.1 - /private/var/folders/qr/pwndt2n55vs9z6w4dfnh6k440000gn/T/xfs-f78acc88/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Managers:
    Cargo: 1.67.0 - /opt/homebrew/bin/cargo
    CocoaPods: 1.11.3 - /usr/local/bin/pod
    Homebrew: 4.0.3 - /opt/homebrew/bin/brew
    pip3: 21.2.4 - ~/miniconda3/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem

```

**Additional context**

**Comment by milesj** [comment]
@tbezman Have you tried running everything in parallel using moon?

```
tasks:
  dev:
    command: noop
    deps: 
      - next:dev
      - web:relay-watch
      - web:graphql-codegen-watch
```

**Comment by tbezman** [comment]
If ^^ works I'll eat my sock hold on

**Comment by tbezman** [comment]
Dude, yeah this works. This is so much better than what we were doing before. Thank you!

**Comment by milesj** [comment]
Dope.

Yeah it's a bit hidden feature. I should document it hah.
