### ISSUE TITLE
[bug] Moon can not hash git submodules

### ISSUE THREAD

**Issue by bryanjswift** [moonrepo/moon#652]
**Describe the bug**

`moon run project:task` fails to execute with `fatal: Unable to hash {submodule location}` when the inputs include a submodule

**Steps to reproduce**

1. Clone a repository with moon
2. Add a submodule in the sources of a task
3. Run the moon taks

**Expected behavior**

Task should execute without errors resulting from submodules.

**Environment**

```
  System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 183.60 MB / 16.00 GB
    Shell: 5.2.15 - /usr/local/bin/bash
  Managers:
    Cargo: 1.57.0 - ~/.cargo/bin/cargo
    Homebrew: 4.0.3 - /usr/local/bin/brew
    Maven: 3.9.0 - /usr/local/bin/mvn
    pip3: 22.3.1 - ~/.pyenv/shims/pip3
    RubyGems: 3.0.3 - /Users/bryanjswift/.rbenv/shims/gem
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
  Languages:
    Bash: 5.2.15 - /usr/local/bin/bash
    Go: 1.20.1 - /usr/local/bin/go
    Java: 15.0.2 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Protoc: 3.21.12 - /usr/local/bin/protoc
    Python3: 3.11.2 - /Users/bryanjswift/.pyenv/shims/python3
    Ruby: 2.6.5 - /Users/bryanjswift/.rbenv/shims/ruby
    Rust: 1.57.0 - /Users/bryanjswift/.cargo/bin/rustc
```

**Additional context**

**Comment by milesj** [comment]
@bryanjswift This kind of looks like it's coming from git directly yeah? If you manually run `git hash-object path/to/submodule` does it fail? I haven't used git submodules in years, but this feels like a weird restriction.

**Comment by bryanjswift** [comment]
> @bryanjswift This kind of looks like it's coming from git directly yeah? If you manually run `git hash-object path/to/submodule` does it fail? I haven't used git submodules in years, but this feels like a weird restriction.

Based on the trace logs, which I realize now I did not include, I do think it not possible to use `git hash-objects` on the sub module. An interesting note is that I moved where the sub module was located so it isn’t included in the inputs. I even went so far as to try and explicitly exclude it from inputs and got the same error. Not at my computer now but can follow up with some more details later today.

**Comment by bryanjswift** [comment]
`git hash-object` on the submodule directory does indeed fail

```
at 23:29:38 ❯ git hash-object services/asset-management/verimatrix-streammark
fatal: Unable to hash services/asset-management/verimatrix-streammark
```

This is the relevant trace data but I don't think it indicates anything different than the above `git hash-object` output.

<details>
<summary><code>MOON_LOG=trace moon run asset-management:build</code></summary>

<pre><code>
[trace 23:34:46] moon:action-pipeline:batch:6 Running 4 actions in batch 6
[trace 23:34:46] moon:action-pipeline:batch:6:2 Processing action SyncNodeProject(asset-management)
[debug 23:34:46] moon:action:sync-project Syncing project asset-management
[trace 23:34:46] moon:action-pipeline:batch:6:3 Processing action RunTarget(constructs:build)
[trace 23:34:46] moon:action-pipeline:batch:6:4 Processing action RunTarget(secrets:build)
[debug 23:34:46] moon:node-platform:sync-project Syncing api-types as a dependency to asset-management's package.json
[trace 23:34:46] moon:action-pipeline:batch:6:1 Processing action RunTarget(asset-management-api:build)
[debug 23:34:46] moon:node-platform:sync-project Syncing constructs as a dependency to asset-management's package.json
[trace 23:34:46] moon:cache:item Cache hit for ~/Documents/little-cinema/projects/backstage/.moon/cache/states/asset-management-api/build/lastRun.json, reading
[trace 23:34:46] moon:cache:item Cache hit for ~/Documents/little-cinema/projects/backstage/.moon/cache/states/constructs/build/lastRun.json, reading
[trace 23:34:46] moon:cache:item Cache hit for ~/Documents/little-cinema/projects/backstage/.moon/cache/states/secrets/build/lastRun.json, reading
[debug 23:34:46] moon:action:run-target Running target asset-management-api:build
[debug 23:34:46] moon:node-platform:sync-project Syncing secrets as a dependency to asset-management's package.json
[debug 23:34:46] moon:action:run-target Running target constructs:build
[debug 23:34:46] moon:node-platform:sync-project Syncing lambda-helpers as a dependency to asset-management's package.json
[debug 23:34:46] moon:action:run-target Running target secrets:build
[debug 23:34:46] moon:node-platform:sync-project Syncing pg as a dependency to asset-management's package.json
[debug 23:34:46] moon:node-platform:sync-project Syncing asset-management-api as a dependency to asset-management's package.json
[trace 23:34:46] moon:lang:config Loading ~/Documents/little-cinema/projects/backstage/services/asset-management/tsconfig.json
[trace 23:34:46] moon:action-pipeline:batch:6:2 Processed action SyncNodeProject(asset-management) in 1.17919ms
[trace 23:34:46] moon:utils:process Running command git ls-files --cached --modified --others --full-name --exclude-standard packages/asset-management-api (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:46] moon:utils:process Running command git hash-object --stdin-paths - (truncated files list) (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:46] moon:utils:process Running command git hash-object --stdin-paths - packages/asset-management-api/package.json packages/asset-management-api/tsconfig.json (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:46] moon:lang:config Loading ~/Documents/little-cinema/projects/backstage/packages/asset-management-api/tsconfig.json
[debug 23:34:46] moon:runner Generated hash 50268e4511f775da55c9d207409b6c8ec1f82c9eb4e230b97fbeb5a97a26f03a for target asset-management-api:build
[debug 23:34:46] moon:runner Cache hit for hash 50268e4511f775da55c9d207409b6c8ec1f82c9eb4e230b97fbeb5a97a26f03a, reusing previous build
▪▪▪▪ asset-management-api:build (cached from previous run, 50268e45)
[trace 23:34:46] moon:action-pipeline:batch:6:1 Processed action RunTarget(asset-management-api:build) in 36.384458ms
[trace 23:34:46] moon:utils:process Running command git ls-files --cached --modified --others --full-name --exclude-standard packages/constructs (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:46] moon:utils:process Running command git hash-object --stdin-paths - (truncated files list) (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:46] moon:utils:process Running command git hash-object --stdin-paths - packages/constructs/package.json packages/constructs/tsconfig.json (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:46] moon:lang:config Loading ~/Documents/little-cinema/projects/backstage/packages/constructs/tsconfig.json
[debug 23:34:46] moon:runner Generated hash c370609c235fd9c75c6d166fced706bca581727e613cbadf9cbac9f644e31271 for target constructs:build
[trace 23:34:46] moon:cache Writing hash manifest ~/Documents/little-cinema/projects/backstage/.moon/cache/hashes/c370609c235fd9c75c6d166fced706bca581727e613cbadf9cbac9f644e31271.json
[debug 23:34:46] moon:runner Cache miss for hash c370609c235fd9c75c6d166fced706bca581727e613cbadf9cbac9f644e31271, continuing run
[trace 23:34:46] moon:utils:process Running command git ls-files --cached --modified --others --full-name --exclude-standard packages/secrets (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:46] moon:utils:process Running command git hash-object --stdin-paths - (truncated files list) (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:46] moon:utils:process Running command git hash-object --stdin-paths - packages/secrets/package.json packages/secrets/tsconfig.json (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:46] moon:lang:config Loading ~/Documents/little-cinema/projects/backstage/packages/secrets/tsconfig.json
[debug 23:34:46] moon:runner Generated hash 3c78b95fd31d6923d94aed1d07e382be290e5cd62ee0172ba1be194fd23143c8 for target secrets:build
[debug 23:34:46] moon:runner Cache hit for hash 3c78b95fd31d6923d94aed1d07e382be290e5cd62ee0172ba1be194fd23143c8, reusing previous build
▪▪▪▪ secrets:build (cached from previous run, 3c78b95f)
[trace 23:34:46] moon:action-pipeline:batch:6:4 Processed action RunTarget(secrets:build) in 102.183269ms
[debug 23:34:46] moon:runner Creating constructs:build command (in working directory ~/Documents/little-cinema/projects/backstage/packages/constructs)
[trace 23:34:46] moon:cache:runfile Writing runfile ~/Documents/little-cinema/projects/backstage/.moon/cache/states/constructs/runfile.json
▪▪▪▪ constructs:build
[trace 23:34:46] moon:utils:process Running command ~/.moon/tools/node/16.19.0/shims/node --title constructs:build ../../node_modules/typescript/bin/tsc --build (in ~/Documents/little-cinema/projects/backstage/packages/constructs)
  MOON_PROJECT_SOURCE=packages/constructs
  MOON_WORKING_DIR=/Users/bryanjswift/Documents/little-cinema/projects/backstage
  MOON_TARGET=constructs:build
  MOON_PROJECT_RUNFILE=/Users/bryanjswift/Documents/little-cinema/projects/backstage/.moon/cache/states/constructs/runfile.json
  MOON_PROJECT_ID=constructs
  MOON_WORKSPACE_ROOT=/Users/bryanjswift/Documents/little-cinema/projects/backstage
  MOON_PROJECT_ROOT=/Users/bryanjswift/Documents/little-cinema/projects/backstage/packages/constructs
  MOON_TOOLCHAIN_DIR=/Users/bryanjswift/.moon
  MOON_CACHE_DIR=/Users/bryanjswift/Documents/little-cinema/projects/backstage/.moon/cache
▪▪▪▪ constructs:build (10s 398ms, c370609c)
[trace 23:34:56] moon:cache:item Writing cache ~/Documents/little-cinema/projects/backstage/.moon/cache/states/constructs/build/lastRun.json
[debug 23:34:56] moon:archive:tar Packing tar archive from ~/Documents/little-cinema/projects/backstage/packages/constructs to ~/Documents/little-cinema/projects/backstage/.moon/cache/outputs/c370609c235fd9c75c6d166fced706bca581727e613cbadf9cbac9f644e31271.tar.gz
[trace 23:34:56] moon:archive:tar Packing file ~/Documents/little-cinema/projects/backstage/.moon/cache/states/constructs/build/stderr.log
[trace 23:34:56] moon:archive:tar Packing file ~/Documents/little-cinema/projects/backstage/.moon/cache/states/constructs/build/stdout.log
[trace 23:34:56] moon:archive:tar Packing directory ~/Documents/little-cinema/projects/backstage/packages/constructs/dist
[trace 23:34:56] moon:action-pipeline:batch:6:3 Processed action RunTarget(constructs:build) in 10.532253292s
[trace 23:34:56] moon:action-pipeline:batch:7 Running 1 actions in batch 7
[trace 23:34:56] moon:action-pipeline:batch:7:1 Processing action RunTarget(asset-management:build)
[trace 23:34:56] moon:cache:item Cache miss for ~/Documents/little-cinema/projects/backstage/.moon/cache/states/asset-management/build/lastRun.json, does not exist
[debug 23:34:56] moon:action:run-target Running target asset-management:build
[trace 23:34:56] moon:utils:process Running command git ls-files --cached --modified --others --full-name --exclude-standard services/asset-management (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:56] moon:utils:process Running command git hash-object --stdin-paths - (truncated files list) (in ~/Documents/little-cinema/projects/backstage)
[trace 23:34:57] moon:action-pipeline:batch:7:1 Failed to process action RunTarget(asset-management:build) in 38.892998ms

 ERROR

Process git failed with a 128 exit code.
fatal: Unable to hash services/asset-management/verimatrix-streammark
</code></pre>
</details>

**Comment by milesj** [comment]
Thanks for the information.

It is true that I haven't tested moon with git submodules, but it is something that should be supported. I'll look into but I can't guarantee a timeline. If this is urgent, I believe you'd have to simply ignore it as an input for now.

**Comment by milesj** [comment]
@bryanjswift Is `services/asset-management/verimatrix-streammark` a folder?

I'm trying to reproduce this and hashing files in submodules work fine, and I believe that error is that it's a folder.

**Comment by milesj** [comment]
Looks like I wasn't filtering dirs, fixed: https://github.com/moonrepo/moon/pull/663

**Comment by bryanjswift** [comment]
`services/asset-management/verimatrix-streammark` is indeed a folder. I would have to look at the branch I was on where I encountered this error. The changes aren't in our mainline yet so I can't say for sure which version.

**Comment by milesj** [comment]
Ok landed in v0.25.2. Can you try it again?

**Comment by bryanjswift** [comment]
> Ok landed in v0.25.2. Can you try it again?

I'll give the new version a shot, thanks again for the quick turnaround on a fix.

**Comment by bryanjswift** [comment]
It seems like this is no longer a problem in 0.25.2, closing

**Comment by milesj** [comment]
Awesome, thanks for the report!
