### ISSUE TITLE
[bug] Task Names Don't Allow Non-Alphanumeric Characters

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#691]
**Describe the bug**

As task name cannot contain non alpha-numeric values? This is a _super_ weird requirement coming from the land of NPM scripts.

**Steps to reproduce**

```yml
tasks:
  'db:migrate':
    command: 'goose -allow-missing=true -dir infra/migrations up'
    envFile: true
```

**Expected behavior**

No error, task executes.

**Actual Behavior**

```
 ERROR 

Failed to validate .moon/tasks.yml configuration file.

  ▪ Must be a valid ID (accepts A-Z, a-z, 0-9, . (periods), - (dashes), _ (underscores), /, and must start with a letter) for key "inheritedTasks.tasks.db:migrate" in ../../.moon/tasks.yml YAML Extended file
```

**Screenshots**

**Environment**

Can't seem to run envinfo on an M2

**Additional context**

This is particularly unexpected and bothersome coming from NPM package scripts. Filing as a bug because this seems like an omission rather than a feature that needs to be added.

**Comment by milesj** [comment]
@shellscape Unfortunately `:` will never be supported because that's a moon specific syntax used by targets: https://moonrepo.dev/docs/concepts/target

We suggest using dashes, slashes, or periods instead.

**Comment by shellscape** [comment]
Isn't the syntax <target>:<script>? admittedly I haven't source-dived this one, but on the surface it would see to just require some regex groups.

I'd suggest that `target:db:migrate` has a lot better DX, muscle memory than `target:db.migrate` - and again, that familiarity coming from Node and wanting to capture that ecosystem has a lot of benefit.

**Comment by milesj** [comment]
We aren't supporting `:` because we have plans for an additional format like `project:task:preset`. We wouldn't be able to parse names correctly at that point.

**Comment by shellscape** [comment]
Understood, we can leave it there. Food for thought for the future: it might be [better?] DX to use a flag for something like presets while letting the task name have flexibility.
