### ISSUE TITLE
[bug] Moon cannot find system binary

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#696]
**Describe the bug**

Moon doesn't seem to be able to resolve a system binary.

**Steps to reproduce**

`.moon/workspace.yml`

```yml
# https://moonrepo.dev/docs/config/workspace
$schema: 'https://moonrepo.dev/schemas/workspace.json'

projects:
  - 'apps/*'
  - 'infra/*'
  - 'packages/*'
  - 'services/*'
  - '.'

vcs:
  manager: 'git'
  defaultBranch: 'main'
```

Root `./moon.yml`

```yml
# https://moonrepo.dev/docs/config/tasks
$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  'db-migrate':
    command: 'goose -allow-missing=true -dir infra/migrations up'
    envFile: true
```

Install Go `curl -L https://git.io/vQhTU | bash`
Install Goose `go install github.com/pressly/goose/v3/cmd/goose@latest`

Then run `moon run <rootName>:db-migrate`

**Expected behavior**

Moon finds the binary and runs it

**Actual Behavior**

```
 ERROR  Unable to find a binary for goose. Have you installed the corresponding dependency?
```

**Environment**

MacOs Ventura M2

**Additional context**

**Comment by milesj** [comment]
@shellscape If this project is considered a JS/TS project, it's trying to find the binary in `node_modules`. You'll need to set the task platform to "system" to execute global/system binaries: https://moonrepo.dev/docs/config/project#platform-1

**Comment by shellscape** [comment]
OK, that's not ideal for a Node ecosystem project. package.json script runners (`npm run`, `npx`, `pnpm`, `pnpm exec`, etc) will use `PATH` rather than strictly node_modules. Most (maybe all now?) Node script runners will add `NODE_PATH` to the running process to _also include_ `node_modules/.bin`. That's the expected behavior for anyone coming from managing a monorepo with Nx, lerna, or pnpm.

**Comment by milesj** [comment]
I understand your frustrations but there are a few reasons why it works this way:

- The first being that moon is written in Rust. Because of this, we have no access to Node's module resolution, nor it's "shell" that can handle a `node_modules` binary or a system binary. We have to emulate everything in Rust land.
- Secondly, a lot of this is because of the integrated toolchain. The node tool is in charge of finding and executing npm binaries, while the system tool is in charge of executing system binaries. The tool that's used is based on `platform`, which by default is inferred from the project's `language`. So if you have a project that's executing across language boundaries, you'll need to explicitly set `platform` (unless the bin matches the tool, like go/deno).
- And lastly, moon is closer to bazel than it is nx/lerna/etc. It's definitely a mental model shift, but when you're working on a repo with hundreds of projects or developers, or require multiple languages in a single tool, then it's the best course to take.

**Comment by shellscape** [comment]
No frustrations here, just trying to enumerate nuances.

> Because of this, we have no access to Node's module resolution

Are you speaking to "binaries" in `node_modules/.bin` that are using the Node shebang `#!/usr/bin/env node`?

> We have to emulate everything in Rust land.

I'm completely ignorant to how Rust executes binaries in this context. Is this why `command: 'echo $PATH'` produces `$PATH` instead of the full system PATH variable content?

**Comment by milesj** [comment]
> Are you speaking to "binaries" in node_modules/.bin that are using the Node shebang #!/usr/bin/env node?

We actually don't execute the files in `.bin`, but parse them and resolve their true location, then execute it with that with `node`. https://github.com/moonrepo/moon/blob/master/crates/node/lang/src/node.rs#L50 We do this because we need to be able to pass CLI args to the parent `node` binary, which you can't do by executing the shims/symlinks in `.bin`.

Basically when we encounter a command like `eslint ./src`, we need to find the `eslint` binary (typically the package entry point) ourselves.

> I'm completely ignorant to how Rust executes binaries in this context. Is this why command: 'echo $PATH' produces $PATH instead of the full system PATH variable content?

Yeah, Rust processes are as raw as can be. We don't wrap commands in a shell currently, and have had many discussions about this. We keep going back and forth on what the best approach should be, but it basically boils down to user shell's not being deterministic/hermetic across machines.

Shells can be used manually though: `command: 'bash -c echo $PATH'`.

**Comment by shellscape** [comment]
> We actually don't execute the files in .bin, but parse them and resolve their true location, then execute it with that with node

Fascinating. How do you handle (if at all) binaries (files) in `node_modules/.bin` that use a non-node shebang like `#!/usr/bin/env bash` or pnpm's wrappers e.g. pnpm's wrapper for prettier:

```bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/powella/code/rally/rally/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/Users/powella/code/rally/rally/node_modules/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/prettier@2.8.4/node_modules/prettier/bin-prettier.js" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/prettier@2.8.4/node_modules/prettier/bin-prettier.js" "$@"
fi

```

**Comment by milesj** [comment]
Yeah it's tough, but we basically extract this line `exec node  "$basedir/../../../../node_modules/.pnpm/prettier@2.8.4/node_modules/prettier/bin-prettier.js"`, reduce it to `../../../../node_modules/.pnpm/prettier@2.8.4/node_modules/prettier/bin-prettier.js`, and compose an absolute path from there.

**Comment by shellscape** [comment]
That log is helpful, thanks.

We've spent a good chunk of the day poking at this. On one side, we totally understand what you're going for with how things are setup with regard to running tasks. On the other, we're stuck at not having an analog for how we ran commands in package.json scripts - that's what we _thought_ (incorrectly) we were getting. In our minds, that would have made moon The Perfect:tm: solution. (It's entirely possible we simply just misunderstood) We've been toying with farming out the task running to make, which is still doable but less than ideal, increases complexity and adds another layer of knowledge authors have to have beyond standard bash/sh. The one thing we definitely don't want to do is run everything through Node. That's what we had using `pnpm exec` and `pnpm run` for everything, and we were excited by the prospect of being outside of a Node execution context. We also looked at just writing a bunch of shell scripts, putting them in a directory, and having moon call those, but that defeats the nice single-file organization that moon and make afford. So our options for adopting moon right now are:

- wait until moon adopts a more flexible, bash-compatible task running method
- use make, and introduce another syntax devs have to learn

I'm honestly not sure where we'll land, but it's a hurdle to adoption to be sure.

Tangential task/command feedback:

`moon run app:build -- --force` PNPM and Yarn have both done away with the use of `--` for passing args, and no longer require the use of the `run` keyword. That's worth looking into as a DX improvement. I'm honestly not sure what NPM does anymore because I haven't used it in years and I'm not sure I'd trust anyone who does 😆  We're on the same page that you're targeting more than Node, _but_ but for the Node ecosystem adopting moon, this may seem like a step backwards.

**Comment by milesj** [comment]
This is some great feedback. Is this repository public by chance? Would be nice for me to take a look at it's complexity. If not public, if you know of a similar kind of open source repository, that would be useful to.

With that being said, I'll discuss adding shell for system commands. We kind of treat system commands as escape hatches right now, so I can see shell's falling into that category also.

**Comment by shellscape** [comment]
> Is this repository public by chance?

It's not but I could get you access I'm sure. 

> If not public, if you know of a similar kind of open source repository, that would be useful to.

I setup a similar repo at https://github.com/rollup/plugins, though it doesn't use any system binary files. This is a decent sample of the kind of shenanigans we're up to with package scripts https://github.com/rollup/plugins/blob/master/packages/node-resolve/package.json#L26-L40

Here's the scripts from the root package.json in the repo in question that pnpm runs with the `--workspace-root` flag:

```json
  "scripts": {
    "build:packages": "time pnpm --filter @openbaseio/* build",
    "db:migrate": "[[ -f .env ]] && source .env; goose -allow-missing=true -dir infra/migrations up",
    "db:migrate:down": "[[ -f .env ]] && source .env; goose -dir infra/migrations down",
    "db:migrate:new": "f() { goose -dir infra/migrations create \"${@:2}\" sql; }; f",
    "db:migrate:status": "[[ -f .env ]] && source .env; goose status",
    "deploy:all": "pnpm --recursive deploy",
    "dry": "source .env; NODE_OPTIONS='--max-old-space-size=4096 --unhandled-rejections=strict' ts-node --swc",
    "fix:js": "NODE_OPTIONS=\"--max-old-space-size=16384\" eslint --fix --cache automation cdk infra packages services --ext .js,.ts",
    "lint": "pnpm lint:docs && pnpm --no-bail lint:json && pnpm lint:package && pnpm lint:js",
    "lint:docs": "prettier --write .github/**/*.md **/README.md",
    "lint:js": "NODE_OPTIONS=\"--max-old-space-size=16384\" eslint --cache automation cdk infra packages services --ext .js,.ts",
    "lint:json": "prettier --write .github/**/*.yml **/tsconfig.json **/tsconfig.*.json pnpm-workspace.yaml",
    "lint:package": "prettier --write **/package.json",
    "package:build": "r(){ cd $1; ln -s ../../shared/tsconfig.packages.json tsconfig.json; tsc --project tsconfig.json; rm tsconfig.json; }; r",
    "prepare": "husky install",
    "preservice:deploy": "pnpm build:packages",
    "run:deploy": "time ts-node --swc cdk/deploy.ts",
    "security": "pnpm audit --audit-level=high",
    "service:build": "r(){ cd $1; ln -s ../../shared/tsconfig.json tsconfig.json; tsc --project tsconfig.json; rm tsconfig.json; }; r",
    "service:deploy": "r(){ [[ -f ./.env ]] && source ./.env; cdk deploy --all --require-approval=never -y --app \"pnpm run:deploy $1\" --output cdk.out/$1/$(date +%s); }; r",
    "service:release": "r() { release-package $1 --no-publish --package-path=$(basename $(dirname $2)); }; r",
    "synth": "cdk synth --all --app \"pnpm run:deploy\""
  },
```

You'll see a big mix of shell features as well as node things in there, as well as flag and argument parsing, things to get around CWD issues, and some fancy bash wrapping to get around limitations with package scripts. It's bananas, but it works very well.

_Worth noting that moon's `.env` file support allows us to get rid of `[[ -f .env ]] && source .env;` which is really nice!_

> With that being said, I'll discuss adding shell for system commands.

Dope, appreciate it!

**Comment by shellscape** [comment]
_Dropping this here for folks arriving from search in the future_

Here's our workaround for getting system and node binaries to play nice with Moon (`goose` is a go-installed app):

```makefile
#./.moon/Makefile
# this file contains "system" commands that moon cannot resolve

db.migrate:
	@goose -dir infra/migrations up

db.migrate.down:
	@goose -dir infra/migrations down

db.migrate.new:
	@if [ -z "$(name)" ]; then\
		echo "\n\033[0;31mPlease name the migration by using \033[0m\`moon run rally:db.migrate.new -- name=<name>\`\n";\
		exit 1;\
	fi
	@goose -dir infra/migrations create $(name) sql

db.migrate.status:
	@goose status
```

And our project-root `moon.yml`:

```yml
# https://moonrepo.dev/docs/config/tasks
$schema: 'https://moonrepo.dev/schemas/tasks.json'

env:
  MAKEFILES: './.moon/Makefile'

tasks:
  'db.migrate':
    command: 'make db.migrate'
    envFile: true

  'db.migrate.down':
    command: 'make db.migrate.down'
    envFile: true

  'db.migrate.new':
    command: 'make db.migrate.new name='
    envFile: true

  'db.migrate.status':
    command: 'make db.migrate.status'
    envFile: true
```

_Of note: We were able to leave the `platform: 'system'` property off of the task definitions and it worked as expected._

**Comment by milesj** [comment]
Yeah I'm very familiar with that kind of "scripts soup" as I like to call it. I took a stab at what it would look like in moon.

To start, `build:packages` and `preservice:deploy` _could_ be replaced with `moon run :build`. Right now it will build everything, not just packages, but we are working on a query language to solve this. But also, if you target an individual task `moon run <foo>:build` it will only builds things required.

The `db:*` can be in the root like you've done. One thing I'd like to note here, is that once we have go support (`platform: go`), we'll be able to detect `goose` from `GOBIN`, similar to how we do node module resolution.

The `deploy:all` can be replaced with `moon run :deploy`.

I'm not sure what `dry` is doing. I'm assuming running an `index.ts` script? Could be in the root project.

All of the `lint:*` can be replaced with `format` and `lint` tasks in `.moon/tasks.yml`.

```yml
tasks:
	format:
		command: 'prettier --write .'
	lint:
		command: 'eslint --cache --ext .js,.ts .'
```

The other `service:*` looks to be very unique to your situation, so I'll leave that to you! heh

**Comment by milesj** [comment]
v1 now wraps system tasks in a shell. Can you see if the bin is found now?

**Comment by shellscape** [comment]
I'll check that out this evening!

**Comment by shellscape** [comment]
Resolved in v1 🎉
