### ISSUE TITLE
[feature] Store timestamp in hash file and use it in `moon clean`

### ISSUE THREAD

**Issue by bryanjswift** [moonrepo/moon#709]
**Is your feature request related to a problem? Please describe.**

Currently `moon clean` and the automatic cleanup is not happening in CI/CD environments. This may be specific to my team's setup but as best I can tell the cache files get restored and their modified timestamps are set to "now" (at the time of restore) and so the cleanup doesn't see any of the files as "old" and so the size of the cache grows continuously.

**Describe the solution you'd like**

It would be ideal if the hash file contained a `createdAt` (or maybe `lastUsedAt`) timestamp and the automatic cleanup and `moon clean` commands used this timestamp to determine if the hash and related outputs could be cleaned (I assume they use the same code path).

**Describe alternatives you've considered**

Alternatives would almost certainly involve changing the way my project saves and restores the cache files. This is possible and may even be better. However, it does not seem like using the filesystem timestamps is a safe assumption for a tool used in ephemeral environments because the timestamps may be a lie.

**Additional context**

I have not investigated the `moon clean` or automatic cleanup code paths, I assume they share a bunch of or all logic, and so I am making an assumption that they use the filesystem timestamps based on the absence of timestamps in the hash files and the `moon clean` behavior I am observing in CI.

**Comment by milesj** [comment]
The real solution to this problem is remote caching (https://moonrepo.dev/docs/guides/remote-cache), where artifacts are only downloaded on demand when needed.

With that said, I can look into a smarter clean as it wouldn't hurt.

**Comment by bryanjswift** [comment]
> The real solution to this problem is remote caching (https://moonrepo.dev/docs/guides/remote-cache), where artifacts are only downloaded on demand when needed.

I hear you on that, I can tell you for sure that shipping code artifacts to additional places (especially JS/TS artifacts as they are plain text) is potentially going to meet resistance as a security concern. For example, the team I'm on now isn't doing anything _sensitive_ in the sense of highly secretive but I know I'll meet resistance for a remote caching solution. This conversation about remote caching is one I'm happy to have but is tangential to the feature request so I'll drop it.

**Comment by milesj** [comment]
@bryanjswift When you cache in CI, are you just caching the entire `.moon/cache` folder? Or just `.moon/cache/outputs`?

**Comment by bryanjswift** [comment]
> @bryanjswift When you cache in CI, are you just caching the entire `.moon/cache` folder? Or just `.moon/cache/outputs`?

The entire folder. It seemed to me, without knowing the internals, the hash files would be necessary in order to know the inputs and outputs matched up.

**Comment by milesj** [comment]
@bryanjswift They are not. All that matters is `.moon/cache/outputs`.

With that being said, I've briefly looked into this and it's not possible to include a timestamp in the hash manifest, as that would simply invalidate the contents and generate a unique hash each time.

I've looked into creating a cache tag (similar to https://bford.info/cachedir/) but this also doesn't seem like a viable solution. It would work great for uploading the cache since the file exists and the archive can use it as an input, but not for downloading, since it wouldn't exist and the CI can't reference it as an input. For example, GH actions `hashFile(...)`.

**Comment by bryanjswift** [comment]
It’s possible the use case I’m thinking of isn’t one moon wants to support and that I’m using/storing/restoring the cache in a way that I shouldn’t. I can’t rule it out. Another way for me to say what I’m saying is that I was surprised that `moon clean` was not cleaning up files in my use case but I can definitely see an argument that it _shouldn’t_ because my use case changes modified time stamps. I can also look into creating archives that preserve time stamps so they are accurate when restored.

**Comment by bryanjswift** [comment]
I’m closing this. I have resolved my issue by using an archive format that preserves modified time stamps. Though I ended up filtering out old artifacts on my own as moon clean was not removing them.
