### ISSUE TITLE
[feature]  cli auto discover target scope

### ISSUE THREAD

**Issue by tomdavidson** [moonrepo/moon#719]
**Is your feature request related to a problem? Please describe.**
No, just a convenience.

Sometimes it is a better devx for your cwd to be a single workspace (particularly a shared repo rather than a completed, nx style monorepo).

If I am working in workspace located in `pacer/services/docket-notifications/`, I can not:

`mono run build-app` 
or
`mono run ~:build-app`

I have to 
`moon run docket-notifications:build-app`

**Describe the solution you'd like**

The scope is already known, even in a workspace without its own `moon.yml`   due the cwd being found in the configured workspace. Also, the configuration recognizes `~`, `^`,  and naked tasks. 

Offer a `moon run <task>`  UX by 

Discover the scope ( if the cwd exists in the configured workspace) if non-other is provide in the target via the cli. Support interactions would include:

- `mono run build-app`
- `mono run ~:build-app`
- `mono run ^:build-app`

**Describe alternatives you've considered**

This would offer a more consistent with configuration experience, but its really just convenience. The alternative is to type out the workspace names or perhaps have a narrow enough filter.

**Comment by milesj** [comment]
We've actually been working toward this. We have most of the functionality implemented here: https://github.com/moonrepo/moon/blob/master/crates/core/project-graph/src/project_graph.rs#L80

I'll see how much it'll take to finish.

**Comment by milesj** [comment]
Landed in 1.1 👍
