### ISSUE TITLE
[bug] Intermittently, cached moon outputs get partially restored

### ISSUE THREAD

**Issue by bryanjswift** [moonrepo/moon#735]
**Describe the bug**

I've been encountering this off and on since adopting moon and had been holding off on reporting it until I could see a pattern on when it happens. Unfortunately I still haven't but I want to describe the situation and maybe we can figure it out together.

I have a task `messaging-api:gen-prisma-client` that happens fairly on in my project. The outputs of the task are all sent to a single folder within the source tree of a project. Included in the task outputs are some test files (`.js`, `.d.ts` and `.json` files) and binary files (`.node` extension) . There are only a couple of inputs for the task and they do not change often which means the output for this task can often be restored from cache.

Intermittently, when this task is executed subsequent tasks that depend upon it will fail because a file that is a `.js` output of  the task has invalid syntax. It appears that when restoring the file from cache only part of a memory buffer is flushed to disk because it looks like the `.js` file starts halfway through.

I have not noticed if the partially restored file is always a particular part of the file.

**Steps to reproduce**

I wish I had these ☹️ 

**Expected behavior**

The previous directory would be cleared out or the files would be cleanly replaced.

**Screenshots**

<img width="1072" alt="Screenshot 2023-03-21 at 14 52 24" src="https://user-images.githubusercontent.com/9911/226712061-416d25f4-003f-46bd-bd6a-30ed751e674f.png">

**Environment**

`npx envinfo --system --SDKs --languages --managers --binaries`

```
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 184.09 MB / 16.00 GB
    Shell: 5.2.15 - /opt/homebrew/bin/bash
  Binaries:
    Node: 16.19.0 - ~/.volta/tools/image/node/16.19.0/bin/node
    Yarn: 3.4.1 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    Cargo: 1.68.0 - ~/.cargo/bin/cargo
    Gradle: 8.0.2 - /opt/homebrew/bin/gradle
    Homebrew: 4.0.6 - /opt/homebrew/bin/brew
    Maven: 3.9.1 - /opt/homebrew/bin/mvn
    pip3: 22.3.1 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Languages:
    Bash: 5.2.15 - /opt/homebrew/bin/bash
    Go: 1.20.2 - /opt/homebrew/bin/go
    Java: 11.0.17 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.11.2 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.68.0 - /Users/bryanjswift/.cargo/bin/rustc
```

**Additional context**

The task I mentioned at the start is defined like this, the `:env-compare` task does not get cached (it has `cache: false` in options). 

```yml
  gen-prisma-client:
    command: 'prisma generate --schema=prisma/schema.prisma'
    deps:
      - 'root:env-compare'
    inputs:
      - '/.env'
      - 'prisma/schema.prisma'
    outputs:
      - 'src/generated/prisma-client'
```

The output of the task looks like this:

```
packages/messaging-api/src/generated/prisma-client/
├── index-browser.js
├── index.d.ts
├── index.js
├── libquery_engine-darwin-arm64.dylib.node
├── libquery_engine-rhel-openssl-1.0.x.so.node
├── package.json
├── runtime
│   ├── index-browser.d.ts
│   ├── index-browser.js
│   ├── index.d.ts
│   ├── library.d.ts
│   └── library.js
└── schema.prisma

2 directories, 12 files
```

**Comment by milesj** [comment]
@bryanjswift Is it always a `.js` file that is broken? Or does it randomize between all the files?

**Comment by bryanjswift** [comment]
> @bryanjswift Is it always a `.js` file that is broken? Or does it randomize between all the files?

From what I recall it is always a `.js` file that is broken and manifests as a parse error during the execution of the next step. If other files were broken or partially restored I wouldn't see it until run time (if it were a `.node` file) or TS build time (if it were a `.d.ts` file).

**Comment by bryanjswift** [comment]
For what it is worth, this is easily circumnavigated. If I delete the directory where files are output and rerun my dependent task the process completes successfully. As far as I can tell this only happens when the files are already present in the directory.

**Comment by milesj** [comment]
@bryanjswift One thing that would help when a break occurs, is to manually unpack the `<hash>.tar.gz` file, and inspect the files. If the files are broken in the tarball, then the issue happens during packing, otherwise if they are correct, then it happens during unpacking, and it'll help me figure this out.

**Comment by bryanjswift** [comment]
> @bryanjswift One thing that would help when a break occurs, is to manually unpack the `<hash>.tar.gz` file, and inspect the files. If the files are broken in the tarball, then the issue happens during packing, otherwise if they are correct, then it happens during unpacking, and it'll help me figure this out.

I'm sure that it happens during unpacking because when I delete the existing files but leave the cache intact when I run the task again the files are restored correctly. Because of this, it has been extremely easy to work around.

**Comment by bryanjswift** [comment]
> Good to know, will dig into.

Thanks, I wish I had better steps to reproduce. I know how frustrating intermittent bugs are.

**Comment by milesj** [comment]
@bryanjswift Can you attach the really large js file? Understandable if not.

**Comment by bryanjswift** [comment]
> @bryanjswift Can you attach the really large js file? Understandable if not.

Mind if I send it to you through discord? The outputs for the task in question, I'm pretty sure, only contain type information and a schema of our data model which doesn't seem novel to me so I don't mind sharing but I'd rather not share it publicly by attaching it to a GitHub issue.

**Comment by milesj** [comment]
@bryanjswift Yeah that's fine

**Comment by milesj** [comment]
I've setup a ton of test cases to try and catch this but unfortunately have not been able to reproduce it yet. Will keep trying.

**Comment by bryanjswift** [comment]
> I've setup a ton of test cases to try and catch this but unfortunately have not been able to reproduce it yet. Will keep trying.

I appreciate you working on the test cases and trying to track this down. Since I have had this happen, in fact have it happen semi-regularly do you have any suggestions on how to start investigating on my side the next time it happens?

**Comment by milesj** [comment]
@bryanjswift I suppose when it happens, can you send me the trace logs? you may need to always pass `--log trace` or (`--logFile`).

My current though is that another process is failing, which causes everything to abort midway.

**Comment by bryanjswift** [comment]
I think I found a reliable reproduction when my `.env` file changes. Doing some more investigation.

**Comment by bryanjswift** [comment]
I think the problem is the input hash of the `.env` file is changing but the output hash doesn't change. So the input file is changing but not directly impacting the output files.

**Comment by mrobinsn** [comment]
To provide another data point, I've been running into this issue pretty regularly as well (on multiple versions of moon including v1.6.1). Seemingly at random, moon will fail to correctly hydrate the output from the cache archive. There is no failure or error from moon's perspective, but it's clear that the hydrated file does not match the file stored in the cache archive (`.moon/cache/outputs/<hash>.tar.gz`). This then leads to failures down the task chain when it comes time to execute or consume that output. 

I suspect this might be happening more often than we realize because it can be somewhat insidious if your outputs aren't checked or verified by another process. In the best case, your `moon run` command will fail. In the worst case, you could unknowingly publish corrupted build artifacts.

**Comment by milesj** [comment]
I've gone through the tar Rust code a few times now and haven't found anything. I created an issue on the `tar` library to see if they have any insight into this problem.

**Comment by mrobinsn** [comment]
@milesj I think I see the problem here. In the tree differ logic, there is a bit where if the sizes are the same it falls back to a byte level equality check. That involves _reading_ from the source tar, which advances its file pointer, so when you land back into the untar logic after some portion of the source,dest files were not equal, it will only extract data starting from that position. This explains the behavior in the Discord thread where the hydrated files were missing some number of bytes at the beginning. 

It might also explain why this happens so rarely and inconsistently. It would only happen when the source and destination both exist, are exactly the same size, but differ in content (but not fully).

**Comment by milesj** [comment]
Released a patch, let me know if it crops up again.

**Comment by bryanjswift** [comment]
I can't say conclusively this if fixed because I didn't have a consistently reproducible case but since updating the moon version to 1.7.3 I have not encountered this issue in situations where I historically have.

**Comment by bryanjswift** [comment]
I'm pretty confident this is resolved. It's been more than a week since I've seen the error reported in this issue. I'm closing it. Thanks @mrobinsn for investigating and @milesj for fixing!
