### ISSUE TITLE
[bug] Moon hangs indefinitely when run outside a moon workspace

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/moon#757]
If I try to run a `moon run <target>` command outside a moon project, moon hangs indefinitely.
![image](https://user-images.githubusercontent.com/60938164/228716820-e0b90ba9-cd08-46b8-87c4-709f8c58d4af.png)

**Comment by milesj** [comment]
This seems very odd. Does it happen in other folder besides `/tmp`?

**Comment by IgnisDa** [comment]
Yes it happens in $HOME as well.

**Comment by milesj** [comment]
Found it.
