### ISSUE TITLE
[bug] V1.1.0 profile file is not generated `moon run --profile=cpu pkg-a:build --log=trace -u`

### ISSUE THREAD

**Issue by SoonIter** [moonrepo/moon#770]
**Describe the bug**

profile file is not generated

**Steps to reproduce**

**Expected behavior**
generated the cpu profile file

**Screenshots**
![image](https://user-images.githubusercontent.com/79413249/229708092-3959bf46-a28a-40ec-91f2-656bc0bf0960.png)
![image](https://user-images.githubusercontent.com/79413249/229708130-bc782328-2998-4bf5-b486-b9015d263d7f.png)

**Environment**

```

```

**Additional context**

I'll check this tonight. It's okay to assign it to me.

**Comment by milesj** [comment]
Can you paste the `--log trace` output?

**Comment by milesj** [comment]
Yeah profiling requires the binary in question to support it natively. I can probably look into this logging a warning for tasks that don't support it.
