### ISSUE TITLE
[bug] Using `@files(..)` incurs a heavy performance hit

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#771]
I've noticed that any time my `moon.yml` files change, the next `moon run ..` takes ~30s before it even executes the task.

I added some extra debug logging to a local copy of `moon` to track down what is going on and found that my heavy use of the `@files(..)` token function is the culprit. 

This is happening during the project graph evaluation:
1. moon goes to expand the project graph [here](https://github.com/moonrepo/moon/blob/v1.0.2/crates/core/project-graph/src/project_builder.rs#L202)
2. That ends up calling into the token resolver [here](https://github.com/moonrepo/moon/blob/v1.0.2/crates/core/project-graph/src/token_resolver.rs#L149)
3. Which then ends up walking the file tree to resolve the paths for each file in the group [here](https://github.com/moonrepo/moon/blob/v1.0.2/crates/core/task/src/file_group.rs#L77)

On my system, for the file group I'm using, this takes ~250ms, which on it's own, is fine. However, I have >100 tasks defined which all use this same file group, and moon seems to expand each one in sequence (serially) which is how it ends up appearing hung for ~30s.

Example runtime using `@files(myGroup)`:
```
moon run :my-task  18.16s user 9.87s system 98% cpu 28.407 total
```

If I instead use `@group(myGroup)`:
```
moon run :my-task  1.36s user 0.87s system 100% cpu 2.226 total
```

Using `@group(..)` in place of `@files(..)` seems to be a valid work around when defining inputs.

**Comment by milesj** [comment]
Great debugging. Let me see if I can add some caching around this.
