### ISSUE TITLE
[feature] wildcards to execute command across several projects

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#785]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use a wildcard character to execute an inherited command on multiple projects.

**Describe the solution you'd like**

```
moon run svc-*:build
```

and

```yml
build:
  command: ...
  deps:
    - 'svc-*:build'
```

**Describe alternatives you've considered**

Creating a task like `build.all` with a bare command that just echos something, and includes all of the projects I want to run as `deps`. It's not fun to keep up to date. 

**Additional context**

**Comment by milesj** [comment]
With 1.3, you can now do `moon run :build --query "project~svc-*"`.

As for wildcards in `deps`, I'm not sure that will be possible. That requires eager loading all projects into the graph and then doing a secondary pass. Our graph currently operates in a lazy mode.

**Comment by shellscape** [comment]
Circling back to this. a command with the query like the one above works well for a CI environment in which we're building all services in the repo for a sanity check. It's _serviceable_ in the context of something like building all of the monorepo packages as a dependency step for building a single service, but it's moon-running-moon at that point, and not entirely ideal.

**Comment by milesj** [comment]
Supported via tags in v1.11 https://moonrepo.dev/blog/moon-v1.11#unlocked-features
