### ISSUE TITLE
[feature] use project alias in task `deps`

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#786]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use a project alias in the `deps` section for a task. Consider a `packages/log` directory in a monorepo root. The package is named `@scope/log` but due to the directory structure, moon has indexed this with the name `log`. `log:build` will work in the deps but `'@scope/log:build'` will not.

However, from the CLI `moon run @scope/log:build` does work, indicating that moon is able to run tasks based on project alias.

**Describe the solution you'd like**

Use `{projectAlias}:{task}` in `deps`

**Describe alternatives you've considered**

n/a

**Additional context**

**Comment by milesj** [comment]
Aliases _should_ work here, or at least they did. Maybe it broke, I'll look into.

**Comment by milesj** [comment]
I have a test for this here that passes correctly: https://github.com/moonrepo/moon/blob/master/crates/cli/tests/dep_graph_test.rs#L122

**Comment by shellscape** [comment]
OK we'll close this for now and I'll try and track down the environment cause.
