### ISSUE TITLE
[bug][v1.1.1] `MOON_COLOR=2` env is regarded as bool arg and not work

### ISSUE THREAD

**Issue by SoonIter** [moonrepo/moon#787]
**Describe the bug**
v1.1.1

**Steps to reproduce**

`MOON_COLOR=2 moon run pkg-a:build`

**Expected behavior**

As expected in the document

**Screenshots**
<img width="804" alt="image" src="https://user-images.githubusercontent.com/79413249/232437884-e00ed726-910d-4dc8-aef6-3036b51bc640.png">

**Environment**

```

```

**Additional context**

**Comment by milesj** [comment]
Fixed in v1.2.
