### ISSUE TITLE
[feature] mark input(s) as optional

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#791]
**Is your feature request related to a problem? Please describe.**

I'd like to have the ability to set inputs and mark them as "optional." e.g. They might be there, and if they are, use them. Otherwise, ignore. Currently we get a warning like:

```
[ warn 2023-04-18 10:04:38] moon:project:db:build Attempted to hash input packages/thing/batman but it does not exist, skipping
```

This would be most useful when constructing a root task that takes into consideration all possible inputs for the base command. For example; building packages and services within a repo - it's likely that services may have additional files to consider for deployment, IoC, etc that packages do not. This feature would prevent having to append inputs in each service directory.

**Describe the solution you'd like**

A delimiter like `^` or some such to denote that the input is optional and will not generate a warning.

**Describe alternatives you've considered**

We currently have to append to `inputs` in each directory that differs from the minimum need for the task. In this case it's a `build` command. As the number of services grows, we'll be copying and pasting `moon.yml` files into many directories.

**Additional context**

**Comment by milesj** [comment]
Typically using globs is the approach for making something optional. Can that be done here?

**Comment by shellscape** [comment]
In this use case we're targeting a `schema.prisma` file. It may or may not be there, depending on the service. How would we accomplish that with globs without overriding inputs in each project which had the file?

**Comment by milesj** [comment]
I'd personally use `*.prisma` but I understand your point here.

**Comment by milesj** [comment]
Been thinking about this a bit more. Supporting a new syntax for inputs would entirely over-complicate many layers of moon, and isn't worth it just to silence a warning. At minimum I think a setting like `hasher.allowMissingInputs` may be best here.

**Comment by shellscape** [comment]
That would work as well. There's prior art in prettier and eslint for a setting like that

**Comment by shellscape** [comment]
Thanks 🙏 🥳
