### ISSUE TITLE
[feature] project tags shorthand

### ISSUE THREAD

**Issue by theoephraim** [moonrepo/moon#803]
**Is your feature request related to a problem? Please describe.**

Would be nice to be able to have a shorthand for multiple projects based on tags, both when running tasks and declaring dependencies.

This would allow me to keep task names consistent (ex: "build") but still target subgroups of projects more easily.

**Describe the solution you'd like**

Probably makes sense to use the syntax of `#tag`, so for example `moon run #frontend:dev`

**Additional context**

While it could also make sense to have shorthands for project language and type, users could always add redundant tags if they needed to target things that way. Or it could also make sense to automatically apply those redundant tags, ie a project with language of "rust" gets a tag of "rust" automatically...

somewhat related / similar to https://github.com/moonrepo/moon/issues/785

**Comment by milesj** [comment]
Love it. Will look into it for an upcoming release.

**Comment by milesj** [comment]
For now, in 1.3, you can now do `moon run :build --query "tag=frontend"`.

**Comment by theoephraim** [comment]
nice - will play around with it

**Comment by milesj** [comment]
Started working on this but it looks like `#` isn't allowed in bash args 😢 

Only characters that seem acceptable are `@` or `%`...

**Comment by milesj** [comment]
Added support for this, but only in run contexts. It's not possible in config contexts unless we redo the project graph.
