### ISSUE TITLE
[feature] Better Invalid Config Clues

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#807]
**Is your feature request related to a problem? Please describe.**

When we screw up our moon config files, we get an error message that looks like this:

```
 ERROR 

Failed to validate .moon/tasks.yml configuration file.

  ▪ An npm/system command is required
  ```

**Describe the solution you'd like**

I'd love to know where the problem is in the file, in addition to the task name which is invalid

**Describe alternatives you've considered**

😢 using git bisect and other tools to figure out where the bad change is/was

**Additional context**

In this scenario, the following block had bad indentation:

```
    options:
      runDepsInParallel: false
```

That didn't make the YAML invalid, but moon saw `options:` as a task def with no command.

**Comment by milesj** [comment]
Enabling some strict validation that will help.

The other problem is confusing. Sometimes it shows "An npm/system command is required for key "project.tasks.test.command"" and sometimes it doesn't. All of this is abstracted away from us. I don't really like that config package we're using, but migrating is a lot of work.

**Comment by milesj** [comment]
Improved in 1.7.
