### ISSUE TITLE
[bug] critical error w/ parallel deps

### ISSUE THREAD

**Issue by tbezman** [moonrepo/moon#855]
**Describe the bug**

I think there's a regression in the latest version. 

There's a critical error when running tasks with parallel deps. This worked fine in 1.3.1

**Steps to reproduce**

1. Clone the branch from this PR https://github.com/gallery-so/gallery/pull/1564
2. `moon run web:dev`

**Expected behavior**

Moon should run Next, Relay, and GraphQL Codegen in parallel

**Screenshots**

<img width="1244" alt="image" src="https://github.com/moonrepo/moon/assets/6754223/812f8876-97fc-4d4f-9f77-fa41fda7c04a">

**Environment**

This command just hangs for me on MacOS. https://github.com/tabrindle/envinfo/commit/7fe97eab8054a2ea81d822eeba79aff0b4afd9c9 . I'm not sure if this landed but you might want to put a different tool in the template.

```

```

**Additional context**

**Comment by milesj** [comment]
Discussed this in Discord, but for anyone else who comes to this issue, the fix was to ensure `local: true` was defined for all persistent tasks.
