### ISSUE TITLE
Test Failure: test runs_tasks_from_multiple_project 

### ISSUE THREAD

**Issue by darkone23** [moonrepo/moon#858]
I am working on packaging a nix flake for moon since I wanted to use it on my nixos machine.

I can run 'cargo build' and get a working `target/debug/moon` but when I run `cargo check` I get a test failure:

```
     Running tests/check_test.rs (target/debug/deps/check_test-a1f4c3bab8ea4b14)

running 7 tests
test runs_on_all_projects_from_root_directory ... ok
test runs_tasks_in_project ... ok
test runs_for_all_projects_even_when_not_in_root_dir ... ok
test forces_cache_to_write_only ... ok
test runs_tasks_in_project_using_cwd ... ok
test creates_run_report ... ok
test runs_tasks_from_multiple_project ... FAILED

failures:

---- runs_tasks_from_multiple_project stdout ----
thread 'runs_tasks_from_multiple_project' panicked at 'assertion failed: predicate::str::contains(\"base:standard\").eval(&output)', crates/cli/tests/check_test.rs:72:5
```

Is this just on my machine? 

Thanks!

**Comment by darkone23** [comment]
My nix flake is over at https://github.com/darkone23/moon/blob/nix-flake/flake.nix

In a checkout of that branch:

"nix develop" gets me all the build dependencies and I can run "cargo make test" but I still get failures like:

```
Summary [   4.133s] 143/1172 tests run: 135 passed, 8 failed, 0 skipped
        FAIL [   2.481s] moon_cli::check_test runs_tasks_from_multiple_project
        FAIL [   1.512s] moon_cli::docker_test prune_node::focuses_for_npm
        FAIL [   1.379s] moon_cli::docker_test prune_node::focuses_for_pnpm
        FAIL [   1.238s] moon_cli::docker_test prune_node::focuses_for_yarn
        FAIL [   1.199s] moon_cli::docker_test prune_node::focuses_for_yarn1
        FAIL [   1.521s] moon_cli::docker_test setup_node::installs_npm
        FAIL [   0.536s] moon_cli::docker_test setup_node::installs_pnpm
        FAIL [   0.305s] moon_cli::docker_test setup_node::installs_yarn
  ```

I'm wondering if I should skip the tests in my case or if there is something wrong with my build or what...

Any guidance is appreciated - cheers!

**Comment by milesj** [comment]
@darkone23 To debug these, you can add a `assert.debug()` after this call: https://github.com/moonrepo/moon/blob/0b0163586ea6bb57a10de2a7c02d59b53dde0791/crates/cli/tests/check_test.rs#L66

It will dump a bunch of information.

**Comment by darkone23** [comment]
Thank you. That helps and I can see that this is an issue on my end. 

```
$ /home/xxxxxx/.proto/tools/node/18.0.0/bin/node --version
bash: /home/xxxxxx/.proto/tools/node/18.0.0/bin/node: cannot execute: required file not found
```

This is probably because that install of node is expecting system libraries that nixos is not providing. 

I will close this issue and do more digging on my journey to get moon working on nixos.

Thanks again for your help.
