### ISSUE TITLE
[feature] Support for systems without dynamic libraries

### ISSUE THREAD

**Issue by darkone23** [moonrepo/moon#860]
**Is your feature request related to a problem? Please describe.**

Hello again,

I run NixOS as my operating system and was interested in using moon.
I eventually realized it did not work because the operating system does not have the shared libraries the node binaries require.

My system statically links everything so there are no dynamic libraries - so when proto pulls node (and probably other) tarballs they do not work out of the box.

**Describe the solution you'd like**

It would be great if it just worked, I don't think that is very possible the way things are set up today.

**Describe alternatives you've considered**

Maybe there could be some command line flag to say 'skip toolchain' or something. 
It is not much of an option to erase the toolchain.yml definition since other project users might rely on them. 

Today if a project uses moon and I want to contribute - I cannot because the toolchain setup part of moon is broken for me.

Thanks!

**Comment by milesj** [comment]
@darkone23 The toolchain downloading/installing piece is pretty hard-coded into the moon and can't be disabled outright.

 However, you can ignore that part by not declaring the `version` fields in `.moon/toolchain.yml`. That would rely on `node` already existing in the environment, instead of attempting to install it.

**Comment by darkone23** [comment]
I was able to succesfully get moon working on my machine - and to build a project that is managed by moon - woohoo!

I will close out this ticket since it is probably too strange and large a request - I appreciate your support and guidance along the way

For any future eyes: my workaround to get moon working on nixos:

I used the library [nix-ld](https://github.com/Mic92/nix-ld) to support the dynamic binaries pulled in by moon.
