### ISSUE TITLE
[feature] workspace defaults: outputStyle

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#881]
**Is your feature request related to a problem? Please describe.**

I would like the ability to set workspace defaults for task options. The primary workspace that I'm using moon in has `outputStyle: 'stream'` set for nearly every task, as the team prefers to see output immediately. 

**Describe the solution you'd like**

Perhaps a `workspaceDefaults:` key at the top of `.moon/tasks.yml`

**Describe alternatives you've considered**

Oodles of copy/paste.

**Additional context**

**Comment by milesj** [comment]
@shellscape The only tasks that don't show output immediately are transient dependencies of a task. What's so important about seeing their running output and not the final output?

**Comment by shellscape** [comment]
For instance, a CDK deployment. These tend to run long if there is a failure, while it waits for AWS to roll back. If the output is immediately available in the terminal, we can terminate the terminal process and go about our business while the rollback happens async. The same is true in CI; rather than burn minutes, we can cancel a workflow.

We also like to see output immediately for build tasks using bundlers; webpack, vite, esbuild, rollup, etc all have useful diagnostics to stdout in realtime.

Default task options in general seems like a good idea (I bet there's footguns) and there's a lot of prior art for that in the Node ecosystem.

**Comment by milesj** [comment]
FWIW, CI should always stream output: https://github.com/moonrepo/moon/blob/master/crates/core/runner/src/runner.rs#L532

**Comment by shellscape** [comment]
Interesting. We just updated to 1.7 so I'll experiment to see how it behaves.

**Comment by milesj** [comment]
As a stopgap, I'm adding a `MOON_OUTPUT_STYLE` env var in 1.8. Will look into a longer-term solution.

**Comment by milesj** [comment]
You can now do this in 1.20: https://moonrepo.dev/blog/moon-v1.20#configure-default-options-for-tasks
