### ISSUE TITLE
[bug] `$projectRoot` is rendered with a leading tilde

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#888]
**Describe the bug**

The `$projectRoot` variable is being rendered with a leading tilde (~) when interpolated. This is causing issues with third parties which do not automatically expand paths. (e.g. most node package CLIs)

Using bash to expand the result is yielding a negative DX as it requires changing the paradigm of how the task command is constructed.

**Steps to reproduce**

Using a moon task:

```yml
  test:
    command: ava $projectRoot
    inputs:
      - src
      - test
```

Yields:

```
[DEBUG 10:47:22] moon_process::command_inspector  Running command node --title svc-test:test ../../node_modules/ava/entrypoints/cli.mjs ~/code/test/services/svc-test
```

Update: I upgraded to 1.7.1 to see if that had an effect and it looks like there's some more info, but the same bug:

```
[DEBUG 10:56:47] moon_process::command_inspector  Running command node --title svc-test:test ../../node_modules/ava/entrypoints/cli.mjs ~/code/test/services/svc-test  env_vars={"MOON_PROJECT_SOURCE": "services/svc-test", "MOON_CACHE_DIR": "/Users/user/code/test/.moon/cache", "MOON_TARGET": "svc-test:test", "MOON_PROJECT_RUNFILE": "/Users/user/code/test/.moon/cache/states/svc-test/runfile.json", "MOON_PROJECT_ID": "svc-test", "MOON_WORKSPACE_ROOT": "/Users/user/code/test", "MOON_PROJECT_ROOT": "/Users/user/code/test/services/svc-test", "MOON_TOOLCHAIN_DIR": "/Users/user/.proto", "MOON_WORKING_DIR": "/Users/user/code/test/services/svc-test"} working_dir=/Users/user/code/test/services/svc-test
```

Note that the `MOON_PROJECT_ROOT` environment variable is correct but the interpolation result is not. 

**Expected behavior**

I expected moon to render `Users/user/code/test/services/svc-test`

As an aside; it would be very helpful and useful if the release notes could list the actual things fixed, and link back to their respective PRs/commits. I had looked there before opening this bug and couldn't determine quickly if it had already been addressed in 1.7.1. 

**Screenshots**

n/a

**Environment**

```
MacOS Ventura 13.3.1 (22E261)
Moon 1.7.0
```

**Additional context**

**Comment by milesj** [comment]
@shellscape The logs always replace the home dir with ~. Is this actually happening when the task is executed?

**Comment by shellscape** [comment]
yeah I added some logging to Ava's source and it was receiving the tilde

**Comment by milesj** [comment]
@shellscape I can't seem to reproduce this 🤔 

```yaml
tasks:
  tilde:
    command: 'echo "$projectRoot"'
```

```
▪▪▪▪ website:tilde
echo /Users/miles/Projects/moon/website (in ./website)
/Users/miles/Projects/moon/website
▪▪▪▪ website:tilde (6ms, 6a6c0645)
```

**Comment by shellscape** [comment]
Super weird. I'll nuke a few things and see if I can track down the cause.

**Comment by milesj** [comment]
@shellscape Did you ever figure this out?

**Comment by shellscape** [comment]
not as yet. traveling this week so I'm on pause.

**Comment by milesj** [comment]
Closing this. Let me know if it's still a problem in v1.11.

**Comment by shellscape** [comment]
Will do. We're upgrading later this week.
