### ISSUE TITLE
[feature] Allow to install specific version of moon

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#908]
Currently one can only install latest version..

For example here is how a specific version of k3s can be installed. https://docs.k3s.io/upgrades/manual

```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=vX.Y.Z-rc1 sh -
```

This was useful when sometime I need to downgrade to test if it is an issue with newer version of moon or older version of moon.

**Comment by milesj** [comment]
@prabirshrestha The install script actually supports passing an arg, but I'm not really sure what the syntax would be when piping.

```shell 
curl -fsSL https://moonrepo.dev/install/moon.sh | bash "x.x.x" # ???
```

Supporting an env var wouldn't hurt either.

**Comment by milesj** [comment]
I believe the syntax is:

```
curl -fsSL https://moonrepo.dev/install/moon.sh | bash -s -- x.x.x
```
