### ISSUE TITLE
[feature] Allow to specify moon version range

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#909]
Allow to specify moon version range in `.moon/toolchain.yml`

```yaml
moon:
   version: '>=1.7.3'
```

Currently it does look in package.json `@moonrepo/cli` but if I'm not using any node projects there is no way to be explicit about this.

**Comment by milesj** [comment]
@prabirshrestha We do have a setting for this, probably not in the best location: https://moonrepo.dev/docs/config/workspace#versionconstraint
