### ISSUE TITLE
[bug] Failed to execute npm and stream output.

### ISSUE THREAD

**Issue by usperry** [moonrepo/moon#913]
**Describe the bug**
when I execute `moon run :build` in the Windows Power Shell I get the following error:

```
npm install --no-audit --no-fund (in workspace)
[ERROR 2023-06-13 21:55:25] log  Encountered a critical error, aborting the action pipeline  log.target="moon:action-pipeline:batch:4" log.module_path="moon_action_pipeline::pipeline" log.file="crates\\core\\action-pipeline\\src\\pipeline.rs" log.line=216
Error:   × Failed to execute npm and stream output.
```

See trace in log.txt attachement
[log.txt](https://github.com/moonrepo/moon/files/11738812/log.txt)

`npm install` works by it self 

**Expected behavior**

**Environment**
```
  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.02 GB / 15.56 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.34.1.
  SDKs:
    Windows SDK:
      AllowAllTrustedApps: Enabled
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: AI-221.6008.13.2211.9619390
    VSCode: 1.78.2 - C:\Users\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.1.32328.378 (Visual Studio Community 2022)
  Languages:
    Java: 17.0.2
    Python: 3.9.10
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.22621.1
```

**Comment by usperry** [comment]
Hi @milesj thanks for your answer

npm vesion 9.3.1

after running `npm install --no-audit --no-fund` this was the output:
```
PS C:\Users\project> npm install --no-audit --no-fund
up to date in 619ms
```

**Comment by milesj** [comment]
@usperry Are you using the toolchain stuff? What's in `toolchain.yml`?

**Comment by usperry** [comment]
Yes, I have toolchain configured. I attached the file as txt here

[toolchain.txt](https://github.com/moonrepo/moon/files/11748666/toolchain.txt)

**Comment by usperry** [comment]
This is what the log says

```
[TRACE 19:20:14] log  Failed to process action InstallNodeDeps(18.16.0) in 4.7978ms  log.target="moon:action-pipeline:batch:4:2" log.module_path="moon_action_pipeline::processor" log.file="crates\\core\\action-pipeline\\src\\processor.rs" log.line=219
[ERROR 19:20:14] log  Encountered a critical error, aborting the action pipeline  log.target="moon:action-pipeline:batch:4" log.module_path="moon_action_pipeline::pipeline" log.file="crates\\core\\action-pipeline\\src\\pipeline.rs" log.line=216
```

**Comment by milesj** [comment]
I noticed we're not bubbling up the process error, fixing now. Hopefully that will let us know what's going on.

https://github.com/moonrepo/moon/pull/917

**Comment by milesj** [comment]
@usperry  Can you try 1.8.1 and see if it bubbles up a useful error?

**Comment by usperry** [comment]
Hi milesj,
I updated moon, but didn't have time to analyze it yet. Plan is to try it tomorrow.
Sorry for the delay

**Comment by usperry** [comment]
Hi milesj,
so I updated and get a better error answer this time: 
```
npm install --no-audit --no-fund (in workspace)
Error:   × Failed to execute npm and stream output.
  │
  │ program not found
```


I checked the execution path of `node.exe` in the trace and the file definitally exists in that folder and I can execute it manually: `C:\\Users\\evama\\.proto\\tools\\node\\18.16.0\\node.exe`.
```
[DEBUG 21:11:21] moon_process::command_inspector  Running command npm install --no-audit --no-fund  env_vars={"PROTO_NODE_BIN": "C:\\Users\\evama\\.proto\\tools\\node\\18.16.0\\node.exe"} working_dir=C:\Users\evama\project
[TRACE 21:11:21] log  Failed to process action InstallNodeDeps(18.16.0) in 6.0551ms  log.target="moon:action-pipeline:batch:4:2" log.module_path="moon_action_pipeline::processor" log.file="crates\\core\\action-pipeline\\src\\processor.rs" log.line=219
[ERROR 21:11:21] log  Encountered a critical error, aborting the action pipeline  log.target="moon:action-pipeline:batch:4" log.module_path="moon_action_pipeline::pipeline" log.file="crates\\core\\action-pipeline\\src\\pipeline.rs" log.line=216
```

Is it possible to skip the node installation, as I already have it installed (via nvm)

HERE THE FULL TRACE: [log.txt](https://github.com/moonrepo/moon/files/11873223/log.txt)

![image](https://github.com/moonrepo/moon/assets/9696397/2b4bff99-db3b-4605-b8cf-1a1e20c276cc)

**Comment by milesj** [comment]
@usperry So it's erroring on `npm` missing. Is that available on `PATH`? I see you're on windows, what's the value of `PATHEXT`?

I think the only solution for now is to comment out the `node` setting entirely in `toolchain.yml`.

**Comment by usperry** [comment]
@milesj `npm `is in the path `C:\Users\evama\.proto\tools\node\18.16.0\node_modules\npm`

I only have `nvm `set in my path variables
![image](https://github.com/moonrepo/moon/assets/9696397/8a1ec430-175d-4b33-9769-ecbc3076df1e)

I added the version now to the `toolchain.yml` file: `npm: { version: "9.5.1" }`
Now I have new errors, but am proceeding 😉
I have to check what's going on. Might be a mistake on my side. I'll report soon 🙂

**Comment by milesj** [comment]
Yeah, it looks like `npm` cannot be found on `PATH`. The `C:\Users\evama\.proto\tools\node\18.16.0\node_modules\npm` path isn't looked at.

You can try adding `C:\Users\evama\.proto\bin` to `PATH`, or ensure that nvm is installing npm and that it can be found.

**Comment by usperry** [comment]
Thank you, now it works
