### ISSUE TITLE
[feature] Remote cache without moonbase account

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#915]
Is it possible to have remote cache similar to how Rush does it as mentioned [here](https://rushjs.io/pages/maintainer/build_cache/).

* Directly depend on Azure blobs or AWS S3 then use native expiration it supports. S3 compatibility can be useful for self-hosted scenarios too.
* Allow CI to write to cache but devs in local can only read from cache.

**Comment by milesj** [comment]
The goal is to support different cloud providers through moonbase, but it's low priority at the moment.

**Comment by akshat99812** [comment]
@milesj @prabirshrestha I am new to open source I want to contribute to this repo ,would be a great help if you can guide how do I start

**Comment by doron-cohen** [comment]
This is required for the organization I work for. I would not be allowed to store cached artifacts outside our cloud accounts. Even if they are encrypted the process with infosec will take months. NX has this built in.

**Comment by milesj** [comment]
We're planning on supporting bazel remote APIs, which would enable [bazel-remote](https://github.com/buchgr/bazel-remote) and other services. We will retire moonbase at some point.

**Comment by doron-cohen** [comment]
@milesj could you please share when supporting an open source / S3 cache is planned to? This is a blocker to start using moon in our repo

**Comment by milesj** [comment]
Unfortunately there is no timeframe.

**Comment by milesj** [comment]
@DialLuesebrink Interesting approach, never tried it or accounted for it, so not entirely sure if it would work.

**Comment by MrLuxyfer** [comment]
I would assume that this might require minor changes on how the files are written though in order to work properly. Eg if the file is copied with the proper name already while someone elese tries to unpack the file. Thus the files should be written with a different name like xxxxx.tar.gz.tmp until they are fully written and then renamed to xxxxx.tar.gz . Thus all reads have the finished file.

**Comment by milesj** [comment]
Bazel REAPI support landed in v1.30 https://moonrepo.dev/blog/moon-v1.30#unstable-self-hosted-remote-caching
