### ISSUE TITLE
[bug] Shell variable expansion doesn't work in task commands

### ISSUE THREAD

**Issue by ilyasotkov** [moonrepo/moon#925]
**Describe the bug**

Shell variable expansion is broken in task command strings

**Steps to reproduce**

1. Create a new project with this `moon.yml`:
```yaml
tasks:
  build:
    command: echo $SHELL
    options:
      shell: true
```
2. `moon r build`
3. See literally `$SHELL` printed, not the value of the environment variable

Can work around by doing this

```diff
tasks:
  build:
-   command: echo $USER
+   command: sh -c "echo $USER"
    options:
      shell: true
```

**Expected behavior**

As a user I want to be able to just copypaste my shell scripts into YAML multiline string and expect it to work

**Screenshots**

**Environment**

moon 1.8.1, tried on macOS 12.6 and debian 12

```
  System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 1.03 GB / 3.83 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    npm: 8.19.4 - /usr/local/bin/npm
  Managers:
    Apt: 2.6.1 - /usr/bin/apt
    Cargo: 1.70.0 - ~/.cargo/bin/cargo
  Utilities:
    Git: 2.39.2 - /usr/bin/git
  Languages:
    Bash: 5.2.15 - /usr/bin/bash
    Perl: 5.36.0 - /usr/bin/perl
    Rust: 1.70.0 - /root/.cargo/bin/rustc
```

**Additional context**

There is a similar issue about nested execution https://github.com/moonrepo/moon/issues/889, but it's not even filed as a bug

**Comment by milesj** [comment]
@ilyasotkov `shell: true` wraps the command with `bash -c` so this is weird. Does `--log trace` reveal what command is actually running?

**Comment by ilyasotkov** [comment]
@milesj I guess it's an issue with single quotes (instead of double) wrapped around the command, which makes it a string literal and disables shell expansions.

```
[DEBUG 02:28:03] moon_process::command_inspector  Running command /bin/bash -c 'sh -c '\''echo $SHELL'\'''  env_vars={"MOON_PROJECT_SOURCE": "apps/my-app", "MOON_CACHE_DIR": "/workspace/.moon/cache", "MOON_TARGET": "my-app:build", "MOON_PROJECT_RUNFILE": "/workspace/.moon/cache/states/my-app/runfile.json", "MOON_PROJECT_ID": "my-app", "MOON_WORKSPACE_ROOT": "/workspace", "MOON_PROJECT_ROOT": "/workspace/apps/my-app", "MOON_TOOLCHAIN_DIR": "/root/.proto", "MOON_WORKING_DIR": "/workspace"} working_dir=/workspace/apps/my-app
/bin/bash
```

**Comment by milesj** [comment]
Yeah that's weird. Let me dig into further.
