### ISSUE TITLE
[feature] task option `cache` diverged from CLI option `cache`

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#936]
Not marking this one a bug because it could be intentional. Not really a feature but more of an enhancement.

**Is your feature request related to a problem? Please describe.**

The task option [`cache`](https://moonrepo.dev/docs/config/project#cache) is a strict `true`/`false` boolean.
The CLI option [`cache`](https://moonrepo.dev/docs/commands/overview#caching) accepts an array of valid string values.

This is a bit confusing for DX

**Describe the solution you'd like**

It would be cool if both options accepted the same values. There'd be no cognitive overhead to executing a task on the CLI versus authoring a task in yaml

**Describe alternatives you've considered**

Obtain a bigger brain for myself.

**Additional context**

**Comment by shellscape** [comment]
do those values have the same effect on the CLI?

**Comment by milesj** [comment]
They do, but that's assuming hashes constantly match.

**Comment by shellscape** [comment]
I've developed some muscle memory for the differences 😆  so it's no longer the problem that it was initially. We can close this if you're good to.
