### ISSUE TITLE
[feature] Make `moon ci` output more readable when it fails

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#944]
Currently when `moon ci` fails in a large project, it can be hard to find the actual error message since it's buried in the failed target's output. You have to grep through for each failed target name to find where its output is in the giant log file and start scanning from there to find the issue.

Could `moon ci` be changed so that during failure there is some kind of additional summary printed that includes the output of the failed commands? This could be optional behavior, but would be super useful for debugging failed runs.

**Comment by milesj** [comment]
Will land in the next release: https://github.com/moonrepo/moon/pull/950

**Comment by iyefrat** [comment]
Would it be possible to also get a summary on `moon check`?

**Comment by milesj** [comment]
Landed in v1.10!
