### ISSUE TITLE
[bug] Cannot run moon with a cache if working dir has changed

### ISSUE THREAD

**Issue by philippeauriach** [moonrepo/moon#964]
**Describe the bug**

We are building our project using AWS Amplify, which change the working directory each time it is ran. For example, our last build ran in `/codebuild/output/src861264759/src/project-name`.

We wanted to take advantage of the moon cache by using the moon cache from the previous run, but it fails with the following trace:
<details><summary>Trace</summary>
<pre>
2023-07-06T13:08:59.398Z [INFO]: moon run one-projet:one-task
2023-07-06T13:09:00.098Z [WARNING]: Error:   × Main thread panicked.
2023-07-06T13:09:00.100Z [WARNING]: ├─▶ at /app/crates/core/runner/src/inputs_collector.rs:123:75
                                    ╰─▶ called `Result::unwrap()` on an `Err` value: StripPrefixError(())
                                    0: 0x55f878f0e051 - <unresolved>
                                    1: 0x55f878f09e14 - <unresolved>
                                    2: 0x55f878f061d2 - <unresolved>
                                    3: 0x55f878f052f4 - <unresolved>
                                    4: 0x55f878e8418f - <unresolved>
                                    5: 0x55f8792fd3e2 - <unresolved>
                                    6: 0x55f8792fe1ca - <unresolved>
                                    7: 0x55f878f0f15b - <unresolved>
                                    8: 0x55f879309308 - <unresolved>
                                    9: 0x55f879308f84 - <unresolved>
                                    10: 0x55f879308ee6 - <unresolved>
                                    11: 0x55f879308ed1 - <unresolved>
                                    12: 0x55f878d3e7c2 - <unresolved>
                                    13: 0x55f878d3eb42 - <unresolved>
                                    14: 0x55f878d87fd9 - <unresolved>
                                    15: 0x55f878d6d6dc - <unresolved>
                                    16: 0x55f878d7ac8c - <unresolved>
                                    17: 0x55f878d7a045 - <unresolved>
                                    18: 0x55f878da4492 - <unresolved>
                                    19: 0x55f879381cb0 - <unresolved>
                                    20: 0x55f87938b4aa - <unresolved>
                                    21: 0x55f879385a92 - <unresolved>
                                    22: 0x55f87938575f - <unresolved>
                                    23: 0x55f879385f0f - <unresolved>
                                    24: 0x55f87930ba45 - <unresolved>
                                    25: 0x7fd8fdd2cfd4 - <unresolved>
                                    26: 0x7fd8fddac820 - clone
                                    27:        0x0 - <unresolved>
                                    help: set the `RUST_BACKTRACE=1` environment variable to display a
                                    backtrace.
2023-07-06T13:09:00.120Z [WARNING]: ./node_modules/.bin/moon: line 13:  1035 Aborted                 (core dumped) "$basedir/../@moonrepo/cli/moon" "$@"
2023-07-06T13:09:00.129Z [INFO]: ELIFECYCLE  Command failed with exit code 134.
2023-07-06T13:09:00.140Z [ERROR]: !!! Build failed
2023-07-06T13:09:00.141Z [ERROR]: !!! Non-Zero Exit Code detected
</pre>
</details> 

**Steps to reproduce**

1. Create a simple project with a simple task, with a file as includes
2. Run the task once to populate the moon cache
3. Move your project to another folder (keeping all files including moon cache)
4. Run the same command, you get the crash

We found in the cache `runfile.json` files a particular `root` key, pointing to the absolute root path of the folder. Maybe they could be stored using a "relative to .moon folder" path ?

**Expected behavior**

We expect moon to run, without crashing. It should at least consider the cache obsolete and rerun the task (maybe by explaining why ?), but the best would be to not rerun the task as the files and dist are here.

**Environment**

<details><summary>Env</summary>
<pre>
```
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 11.18 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.asdf/installs/nodejs/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.16.0/.npm/bin/yarn
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.6.5 - ~/Library/pnpm/pnpm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/xxx/.asdf/shims/pod
    Homebrew: 4.0.26 - /opt/homebrew/bin/brew
    pip3: 22.0.4 - ~/.asdf/shims/pip3
    RubyGems: 3.3.7 - /Users/xxx/.asdf/shims/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 14.0.3 - /usr/bin/gcc
    Git: 2.39.2 - /usr/bin/git
    Clang: 14.0.3 - /usr/bin/clang
    Curl: 7.88.1 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Docker: 23.0.5 - /usr/local/bin/docker
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    VSCode: 1.79.2 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.11 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python: 3.8.13 - /Users/xxx/.asdf/shims/python
    Python3: 3.8.13 - /Users/xxx/.asdf/shims/python3
    Ruby: 3.1.2 - /Users/xxx/.asdf/shims/ruby
```
</pre>
</details>

**Comment by philippeauriach** [comment]
We are using moon 1.9.2
That might explain the issue, I will try with only those folders persisted. Sorry if I missed that, but is it documented somewhere?
Thanks !

**Comment by philippeauriach** [comment]
Thanks, it works great by keeping only `.moon/cache/{hashes,outputs}` in the cache!

**Comment by milesj** [comment]
@philippeauriach Awesome!
