### ISSUE TITLE
[bug] fatal: could not open '.moon/toolchain.yml' for reading: No such file or directory

### ISSUE THREAD

**Issue by macthestack** [moonrepo/moon#966]
After updating to 1.9.x I get the following error:

fatal: could not open '.moon/toolchain.yml' for reading: No such file or directory

It's clearly there after being created by the moon init process itself.

Not sure if this is a bug or just me but hopefully someone can shed some light.

(I'm on a mac m1)

**Comment by milesj** [comment]
@macthestack What does `--log trace` show? Does that file have correct ownership?

**Comment by macthestack** [comment]
Hi @milesj ,

I realized that the problem was that I wasn't in my .git root. I was using it in a monorepo and initialized moon a bit down the tree.

I still think I have a valid use case but my problem is solved for now. Please close or keep open as you see fit.

Thanks!

**Comment by milesj** [comment]
Yeah that should work. I'll investigate.

**Comment by milesj** [comment]
I found the problem but it looks to be an actual bug in `git`.

```
$ git hash-object .moon/toolchain.yml
5eba7fa33caa6b6c7571c196feac8cf0b9341f6e

$ echo .moon/toolchain.yml | git hash-object --stdin-paths
fatal: could not open '.moon/toolchain.yml' for reading: No such file or directory
```
