### ISSUE TITLE
[bug] toolchain problems

### ISSUE THREAD

**Issue by macthestack** [moonrepo/moon#969]
I'm trying to run upx on my binary but...

...I get this if I have don't have rust in my toolchain:

`Error:   × Platform rust is not supported. Has it been configured or enabled?`

...I get this if I have rust in my toolchain:

`Error:   × Unable to find a Cargo binary for upx. Have you installed the corresponding dependency?`

**Comment by macthestack** [comment]
Adding `platform: 'system'`to my task solved the problem. Thank you cheatsheet :)

**Comment by milesj** [comment]
@macthestack Did you have a `Cargo.toml` file or something similar in the folder? Curious how it detected Rust.

**Comment by macthestack** [comment]
@milesj yeah, that's right.
